using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using GlobalData.Country;

namespace GlobalData.Currency
{
    public static class GdCurrencyFiatList
    {
        /// <summary>
        /// Complete country data parsed from CSV to C# code
        /// </summary>
        private static Dictionary<string, GdCurrencyFiat> GdCurrencyFiatListDict { get; } = GetCurrencyFiatList();

        public static Dictionary<string, GdCurrencyFiat> GetCurrencyFiatList()
        {
            Dictionary<string, GdCurrencyFiat> fiatList = new();
            // Generated by SQL Code from gd_counrties
            /*
             SET SESSION group_concat_max_len = 1000000;
             SELECT  -- cur.id,code,
	            concat(
                    concat('fiatList.Add(Iso3FiatCodes.', cur.code,', new GdCurrencyFiat { Code = Iso3FiatCodes.', cur.code,', Name = "', REGEXP_REPLACE(cur.name, '\\([A-Z]{3}\\)',''),'", DecimalCount = ', cur.decimal_count,', Symbol = "', IFNULL(cur.symbol,'null') ,'", Countries = new List<GdCountryIso2Code>() { '),
                    concat(IFNULL(CONCAT('GdCountryIso2Code.FromString(Iso3Codes.', GROUP_CONCAT(gd_countries.country_code_iso2 SEPARATOR  '), GdCountryIso2Code.FromString(Iso2Codes.'), ')'), ''),' }});')
                    )
            FROM `gd_currencies` cur
            LEFT JOIN `gd_countries` ON gd_countries.currency=cur.code
            group by cur.code
            */

            fiatList.Add(Iso3FiatCodes.ABK, new GdCurrencyFiat { Code = Iso3FiatCodes.ABK, Name = "Abkhazian Apsar", DecimalCount = 0, Symbol = "null", Countries = new List<GdCountryIso2Code>() { GdCountryIso2Code.FromString(Iso2Codes.AB) } });
            fiatList.Add(Iso3FiatCodes.AED, new GdCurrencyFiat { Code = Iso3FiatCodes.AED, Name = "UAE Dirham", DecimalCount = 2, Symbol = "AED", Countries = new List<GdCountryIso2Code>() { GdCountryIso2Code.FromString(Iso2Codes.AE) } });
            fiatList.Add(Iso3FiatCodes.AFN, new GdCurrencyFiat { Code = Iso3FiatCodes.AFN, Name = "Afghanistan Afghani", DecimalCount = 2, Symbol = "افغانۍ", Countries = new List<GdCountryIso2Code>() { GdCountryIso2Code.FromString(Iso2Codes.AF) } });
            fiatList.Add(Iso3FiatCodes.ALL, new GdCurrencyFiat { Code = Iso3FiatCodes.ALL, Name = "Albanian Lek", DecimalCount = 2, Symbol = "Lek", Countries = new List<GdCountryIso2Code>() { GdCountryIso2Code.FromString(Iso2Codes.AL) } });
            fiatList.Add(Iso3FiatCodes.AMD, new GdCurrencyFiat { Code = Iso3FiatCodes.AMD, Name = "Armenian dram", DecimalCount = 0, Symbol = "֏", Countries = new List<GdCountryIso2Code>() { GdCountryIso2Code.FromString(Iso2Codes.AM) } });
            fiatList.Add(Iso3FiatCodes.ANG, new GdCurrencyFiat { Code = Iso3FiatCodes.ANG, Name = "Neth Antilles Guilder", DecimalCount = 2, Symbol = "?", Countries = new List<GdCountryIso2Code>() { GdCountryIso2Code.FromString(Iso2Codes.AN), GdCountryIso2Code.FromString(Iso2Codes.SX) } });
            fiatList.Add(Iso3FiatCodes.AOA, new GdCurrencyFiat { Code = Iso3FiatCodes.AOA, Name = "Angolan kwanza", DecimalCount = 2, Symbol = "Kz", Countries = new List<GdCountryIso2Code>() { GdCountryIso2Code.FromString(Iso2Codes.AO) } });
            fiatList.Add(Iso3FiatCodes.ARS, new GdCurrencyFiat { Code = Iso3FiatCodes.ARS, Name = "Argentine Peso", DecimalCount = 2, Symbol = "$", Countries = new List<GdCountryIso2Code>() { GdCountryIso2Code.FromString(Iso2Codes.AR) } });
            fiatList.Add(Iso3FiatCodes.AUD, new GdCurrencyFiat { Code = Iso3FiatCodes.AUD, Name = "Australian Dollar", DecimalCount = 2, Symbol = "$", Countries = new List<GdCountryIso2Code>() { GdCountryIso2Code.FromString(Iso2Codes.AU), GdCountryIso2Code.FromString(Iso2Codes.CX), GdCountryIso2Code.FromString(Iso2Codes.CC), GdCountryIso2Code.FromString(Iso2Codes.KI), GdCountryIso2Code.FromString(Iso2Codes.NR), GdCountryIso2Code.FromString(Iso2Codes.NF), GdCountryIso2Code.FromString(Iso2Codes.TV) } });
            fiatList.Add(Iso3FiatCodes.AWG, new GdCurrencyFiat { Code = Iso3FiatCodes.AWG, Name = "Aruba Florin", DecimalCount = 2, Symbol = "?", Countries = new List<GdCountryIso2Code>() { GdCountryIso2Code.FromString(Iso2Codes.AW) } });
            fiatList.Add(Iso3FiatCodes.AZN, new GdCurrencyFiat { Code = Iso3FiatCodes.AZN, Name = "Azerbaijani Manat", DecimalCount = 2, Symbol = "₼", Countries = new List<GdCountryIso2Code>() { } });
            fiatList.Add(Iso3FiatCodes.BAM, new GdCurrencyFiat { Code = Iso3FiatCodes.BAM, Name = "Bosnia and Herzegovina Convert", DecimalCount = 2, Symbol = "KM", Countries = new List<GdCountryIso2Code>() { GdCountryIso2Code.FromString(Iso2Codes.BA) } });
            fiatList.Add(Iso3FiatCodes.BBD, new GdCurrencyFiat { Code = Iso3FiatCodes.BBD, Name = "Barbados Dollar", DecimalCount = 2, Symbol = "$", Countries = new List<GdCountryIso2Code>() { GdCountryIso2Code.FromString(Iso2Codes.BB) } });
            fiatList.Add(Iso3FiatCodes.BDT, new GdCurrencyFiat { Code = Iso3FiatCodes.BDT, Name = "Bangladesh Taka", DecimalCount = 2, Symbol = "BDT", Countries = new List<GdCountryIso2Code>() { GdCountryIso2Code.FromString(Iso2Codes.BD) } });
            fiatList.Add(Iso3FiatCodes.BGN, new GdCurrencyFiat { Code = Iso3FiatCodes.BGN, Name = "Bulgarian Lev", DecimalCount = 2, Symbol = "null", Countries = new List<GdCountryIso2Code>() { GdCountryIso2Code.FromString(Iso2Codes.BG) } });
            fiatList.Add(Iso3FiatCodes.BHD, new GdCurrencyFiat { Code = Iso3FiatCodes.BHD, Name = "Bahraini Dinar", DecimalCount = 2, Symbol = "BHD", Countries = new List<GdCountryIso2Code>() { GdCountryIso2Code.FromString(Iso2Codes.BH) } });
            fiatList.Add(Iso3FiatCodes.BIF, new GdCurrencyFiat { Code = Iso3FiatCodes.BIF, Name = "Burundi Franc", DecimalCount = 2, Symbol = "BIF", Countries = new List<GdCountryIso2Code>() { GdCountryIso2Code.FromString(Iso2Codes.BI) } });
            fiatList.Add(Iso3FiatCodes.BMD, new GdCurrencyFiat { Code = Iso3FiatCodes.BMD, Name = "Bermuda Dollar", DecimalCount = 2, Symbol = "$", Countries = new List<GdCountryIso2Code>() { GdCountryIso2Code.FromString(Iso2Codes.BM) } });
            fiatList.Add(Iso3FiatCodes.BND, new GdCurrencyFiat { Code = Iso3FiatCodes.BND, Name = "Brunei Dollar", DecimalCount = 2, Symbol = "$", Countries = new List<GdCountryIso2Code>() { GdCountryIso2Code.FromString(Iso2Codes.BN) } });
            fiatList.Add(Iso3FiatCodes.BOB, new GdCurrencyFiat { Code = Iso3FiatCodes.BOB, Name = "Bolivian Boliviano", DecimalCount = 2, Symbol = "$b", Countries = new List<GdCountryIso2Code>() { GdCountryIso2Code.FromString(Iso2Codes.BO) } });
            fiatList.Add(Iso3FiatCodes.BRL, new GdCurrencyFiat { Code = Iso3FiatCodes.BRL, Name = "Brazilian Real", DecimalCount = 2, Symbol = "R$", Countries = new List<GdCountryIso2Code>() { GdCountryIso2Code.FromString(Iso2Codes.BR) } });
            fiatList.Add(Iso3FiatCodes.BSD, new GdCurrencyFiat { Code = Iso3FiatCodes.BSD, Name = "Bahamian Dollar", DecimalCount = 2, Symbol = "$", Countries = new List<GdCountryIso2Code>() { GdCountryIso2Code.FromString(Iso2Codes.BS) } });
            fiatList.Add(Iso3FiatCodes.BTN, new GdCurrencyFiat { Code = Iso3FiatCodes.BTN, Name = "Bhutan Ngultrum", DecimalCount = 2, Symbol = "BTN", Countries = new List<GdCountryIso2Code>() { GdCountryIso2Code.FromString(Iso2Codes.BT) } });
            fiatList.Add(Iso3FiatCodes.BWP, new GdCurrencyFiat { Code = Iso3FiatCodes.BWP, Name = "Botswana Pula", DecimalCount = 2, Symbol = "P", Countries = new List<GdCountryIso2Code>() { GdCountryIso2Code.FromString(Iso2Codes.BW) } });
            fiatList.Add(Iso3FiatCodes.BYR, new GdCurrencyFiat { Code = Iso3FiatCodes.BYR, Name = "Belarus Ruble", DecimalCount = 2, Symbol = "null", Countries = new List<GdCountryIso2Code>() { GdCountryIso2Code.FromString(Iso2Codes.BY) } });
            fiatList.Add(Iso3FiatCodes.BZD, new GdCurrencyFiat { Code = Iso3FiatCodes.BZD, Name = "Belize Dollar", DecimalCount = 2, Symbol = "BZ$", Countries = new List<GdCountryIso2Code>() { GdCountryIso2Code.FromString(Iso2Codes.BZ) } });
            fiatList.Add(Iso3FiatCodes.CAD, new GdCurrencyFiat { Code = Iso3FiatCodes.CAD, Name = "Canadian Dollar", DecimalCount = 2, Symbol = "$", Countries = new List<GdCountryIso2Code>() { GdCountryIso2Code.FromString(Iso2Codes.CA) } });
            fiatList.Add(Iso3FiatCodes.CHF, new GdCurrencyFiat { Code = Iso3FiatCodes.CHF, Name = "Swiss Franc", DecimalCount = 2, Symbol = "CHF", Countries = new List<GdCountryIso2Code>() { GdCountryIso2Code.FromString(Iso2Codes.LI), GdCountryIso2Code.FromString(Iso2Codes.CH) } });
            fiatList.Add(Iso3FiatCodes.CLP, new GdCurrencyFiat { Code = Iso3FiatCodes.CLP, Name = "Chilean Peso", DecimalCount = 2, Symbol = "$", Countries = new List<GdCountryIso2Code>() { GdCountryIso2Code.FromString(Iso2Codes.CL) } });
            fiatList.Add(Iso3FiatCodes.CNY, new GdCurrencyFiat { Code = Iso3FiatCodes.CNY, Name = "Chinese Yuan", DecimalCount = 2, Symbol = "?", Countries = new List<GdCountryIso2Code>() { GdCountryIso2Code.FromString(Iso2Codes.CN) } });
            fiatList.Add(Iso3FiatCodes.COP, new GdCurrencyFiat { Code = Iso3FiatCodes.COP, Name = "Colombian Peso", DecimalCount = 2, Symbol = "$", Countries = new List<GdCountryIso2Code>() { GdCountryIso2Code.FromString(Iso2Codes.CO) } });
            fiatList.Add(Iso3FiatCodes.CRC, new GdCurrencyFiat { Code = Iso3FiatCodes.CRC, Name = "Costa Rica Colon", DecimalCount = 2, Symbol = "&#8353;", Countries = new List<GdCountryIso2Code>() { GdCountryIso2Code.FromString(Iso2Codes.CR) } });
            fiatList.Add(Iso3FiatCodes.CUP, new GdCurrencyFiat { Code = Iso3FiatCodes.CUP, Name = "Cuban Peso", DecimalCount = 2, Symbol = "&#8369;", Countries = new List<GdCountryIso2Code>() { GdCountryIso2Code.FromString(Iso2Codes.CU) } });
            fiatList.Add(Iso3FiatCodes.CVE, new GdCurrencyFiat { Code = Iso3FiatCodes.CVE, Name = "Cape Verde Escudo", DecimalCount = 2, Symbol = "$", Countries = new List<GdCountryIso2Code>() { GdCountryIso2Code.FromString(Iso2Codes.CV) } });
            fiatList.Add(Iso3FiatCodes.CZK, new GdCurrencyFiat { Code = Iso3FiatCodes.CZK, Name = "Czech Koruna", DecimalCount = 2, Symbol = "K&#269;", Countries = new List<GdCountryIso2Code>() { GdCountryIso2Code.FromString(Iso2Codes.CZ) } });
            fiatList.Add(Iso3FiatCodes.DJF, new GdCurrencyFiat { Code = Iso3FiatCodes.DJF, Name = "Dijibouti Franc", DecimalCount = 2, Symbol = "null", Countries = new List<GdCountryIso2Code>() { GdCountryIso2Code.FromString(Iso2Codes.DJ) } });
            fiatList.Add(Iso3FiatCodes.DKK, new GdCurrencyFiat { Code = Iso3FiatCodes.DKK, Name = "Danish Krone", DecimalCount = 2, Symbol = "kr", Countries = new List<GdCountryIso2Code>() { GdCountryIso2Code.FromString(Iso2Codes.DK), GdCountryIso2Code.FromString(Iso2Codes.FO), GdCountryIso2Code.FromString(Iso2Codes.GL) } });
            fiatList.Add(Iso3FiatCodes.DOP, new GdCurrencyFiat { Code = Iso3FiatCodes.DOP, Name = "Dominican Peso", DecimalCount = 2, Symbol = "RD$", Countries = new List<GdCountryIso2Code>() { GdCountryIso2Code.FromString(Iso2Codes.DO) } });
            fiatList.Add(Iso3FiatCodes.DZD, new GdCurrencyFiat { Code = Iso3FiatCodes.DZD, Name = "Algerian Dinar", DecimalCount = 2, Symbol = "DZD", Countries = new List<GdCountryIso2Code>() { GdCountryIso2Code.FromString(Iso2Codes.DZ) } });
            fiatList.Add(Iso3FiatCodes.EGP, new GdCurrencyFiat { Code = Iso3FiatCodes.EGP, Name = "Egyptian Pound", DecimalCount = 2, Symbol = "?", Countries = new List<GdCountryIso2Code>() { GdCountryIso2Code.FromString(Iso2Codes.EG) } });
            fiatList.Add(Iso3FiatCodes.ERN, new GdCurrencyFiat { Code = Iso3FiatCodes.ERN, Name = "Eritrean Nakfa", DecimalCount = 2, Symbol = "Nkf", Countries = new List<GdCountryIso2Code>() { GdCountryIso2Code.FromString(Iso2Codes.ER) } });
            fiatList.Add(Iso3FiatCodes.ETB, new GdCurrencyFiat { Code = Iso3FiatCodes.ETB, Name = "Ethiopian Birr", DecimalCount = 0, Symbol = "ETB", Countries = new List<GdCountryIso2Code>() { GdCountryIso2Code.FromString(Iso2Codes.ET) } });
            fiatList.Add(Iso3FiatCodes.EUR, new GdCurrencyFiat { Code = Iso3FiatCodes.EUR, Name = "Euro", DecimalCount = 2, Symbol = "€", Countries = new List<GdCountryIso2Code>() { GdCountryIso2Code.FromString(Iso2Codes.AD), GdCountryIso2Code.FromString(Iso2Codes.AT), GdCountryIso2Code.FromString(Iso2Codes.BE), GdCountryIso2Code.FromString(Iso2Codes.CY), GdCountryIso2Code.FromString(Iso2Codes.EE), GdCountryIso2Code.FromString(Iso2Codes.FI), GdCountryIso2Code.FromString(Iso2Codes.FR), GdCountryIso2Code.FromString(Iso2Codes.GF), GdCountryIso2Code.FromString(Iso2Codes.DE), GdCountryIso2Code.FromString(Iso2Codes.GR), GdCountryIso2Code.FromString(Iso2Codes.GP), GdCountryIso2Code.FromString(Iso2Codes.VA), GdCountryIso2Code.FromString(Iso2Codes.IE), GdCountryIso2Code.FromString(Iso2Codes.IT), GdCountryIso2Code.FromString(Iso2Codes.LT), GdCountryIso2Code.FromString(Iso2Codes.LU), GdCountryIso2Code.FromString(Iso2Codes.MT), GdCountryIso2Code.FromString(Iso2Codes.MQ), GdCountryIso2Code.FromString(Iso2Codes.YT), GdCountryIso2Code.FromString(Iso2Codes.MC), GdCountryIso2Code.FromString(Iso2Codes.NL), GdCountryIso2Code.FromString(Iso2Codes.PT), GdCountryIso2Code.FromString(Iso2Codes.RE), GdCountryIso2Code.FromString(Iso2Codes.PM), GdCountryIso2Code.FromString(Iso2Codes.SM), GdCountryIso2Code.FromString(Iso2Codes.SK), GdCountryIso2Code.FromString(Iso2Codes.SI), GdCountryIso2Code.FromString(Iso2Codes.ES), GdCountryIso2Code.FromString(Iso2Codes.ME), GdCountryIso2Code.FromString(Iso2Codes.XK) } });
            fiatList.Add(Iso3FiatCodes.FJD, new GdCurrencyFiat { Code = Iso3FiatCodes.FJD, Name = "Fijian Dollar", DecimalCount = 2, Symbol = "FJ$", Countries = new List<GdCountryIso2Code>() { GdCountryIso2Code.FromString(Iso2Codes.FJ) } });
            fiatList.Add(Iso3FiatCodes.FKP, new GdCurrencyFiat { Code = Iso3FiatCodes.FKP, Name = "Falkland Islands Pound", DecimalCount = 2, Symbol = "£", Countries = new List<GdCountryIso2Code>() { GdCountryIso2Code.FromString(Iso2Codes.FK) } });
            fiatList.Add(Iso3FiatCodes.GBP, new GdCurrencyFiat { Code = Iso3FiatCodes.GBP, Name = "British Pound", DecimalCount = 2, Symbol = "£", Countries = new List<GdCountryIso2Code>() { GdCountryIso2Code.FromString(Iso2Codes.GS), GdCountryIso2Code.FromString(Iso2Codes.GB), GdCountryIso2Code.FromString(Iso2Codes.GG), GdCountryIso2Code.FromString(Iso2Codes.IM), GdCountryIso2Code.FromString(Iso2Codes.JE), GdCountryIso2Code.FromString(Iso2Codes.TA) } });
            fiatList.Add(Iso3FiatCodes.GEL, new GdCurrencyFiat { Code = Iso3FiatCodes.GEL, Name = "Georgian Lari", DecimalCount = 2, Symbol = "ლარი", Countries = new List<GdCountryIso2Code>() { GdCountryIso2Code.FromString(Iso2Codes.GE) } });
            fiatList.Add(Iso3FiatCodes.GHS, new GdCurrencyFiat { Code = Iso3FiatCodes.GHS, Name = "Ghanaian Cedi", DecimalCount = 2, Symbol = "GH₵", Countries = new List<GdCountryIso2Code>() { GdCountryIso2Code.FromString(Iso2Codes.GH) } });
            fiatList.Add(Iso3FiatCodes.GIP, new GdCurrencyFiat { Code = Iso3FiatCodes.GIP, Name = "Gibraltar Pound", DecimalCount = 2, Symbol = "?", Countries = new List<GdCountryIso2Code>() { GdCountryIso2Code.FromString(Iso2Codes.GI) } });
            fiatList.Add(Iso3FiatCodes.GMD, new GdCurrencyFiat { Code = Iso3FiatCodes.GMD, Name = "Gambian Dalasi", DecimalCount = 2, Symbol = "GMD", Countries = new List<GdCountryIso2Code>() { GdCountryIso2Code.FromString(Iso2Codes.GM) } });
            fiatList.Add(Iso3FiatCodes.GNF, new GdCurrencyFiat { Code = Iso3FiatCodes.GNF, Name = "Guinea Franc", DecimalCount = 2, Symbol = "GNF", Countries = new List<GdCountryIso2Code>() { GdCountryIso2Code.FromString(Iso2Codes.GN) } });
            fiatList.Add(Iso3FiatCodes.GTQ, new GdCurrencyFiat { Code = Iso3FiatCodes.GTQ, Name = "Guatemala Quetzal", DecimalCount = 2, Symbol = "Q", Countries = new List<GdCountryIso2Code>() { GdCountryIso2Code.FromString(Iso2Codes.GT) } });
            fiatList.Add(Iso3FiatCodes.GWP, new GdCurrencyFiat { Code = Iso3FiatCodes.GWP, Name = "Guinea-Bissau peso", DecimalCount = 2, Symbol = null, Countries = new List<GdCountryIso2Code>() { GdCountryIso2Code.FromString(Iso2Codes.GW) } });
            fiatList.Add(Iso3FiatCodes.GYD, new GdCurrencyFiat { Code = Iso3FiatCodes.GYD, Name = "Guyana Dollar", DecimalCount = 2, Symbol = "$", Countries = new List<GdCountryIso2Code>() { GdCountryIso2Code.FromString(Iso2Codes.GY) } });
            fiatList.Add(Iso3FiatCodes.HKD, new GdCurrencyFiat { Code = Iso3FiatCodes.HKD, Name = "Hong Kong Dollar", DecimalCount = 2, Symbol = "$", Countries = new List<GdCountryIso2Code>() { GdCountryIso2Code.FromString(Iso2Codes.HK) } });
            fiatList.Add(Iso3FiatCodes.HNL, new GdCurrencyFiat { Code = Iso3FiatCodes.HNL, Name = "Honduras Lempira", DecimalCount = 2, Symbol = "L", Countries = new List<GdCountryIso2Code>() { GdCountryIso2Code.FromString(Iso2Codes.HN) } });
            fiatList.Add(Iso3FiatCodes.HRK, new GdCurrencyFiat { Code = Iso3FiatCodes.HRK, Name = "Croatian Kuna", DecimalCount = 2, Symbol = "null", Countries = new List<GdCountryIso2Code>() { GdCountryIso2Code.FromString(Iso2Codes.HR) } });
            fiatList.Add(Iso3FiatCodes.HTG, new GdCurrencyFiat { Code = Iso3FiatCodes.HTG, Name = "Haiti Gourde", DecimalCount = 2, Symbol = "HTG", Countries = new List<GdCountryIso2Code>() { GdCountryIso2Code.FromString(Iso2Codes.HT) } });
            fiatList.Add(Iso3FiatCodes.HUF, new GdCurrencyFiat { Code = Iso3FiatCodes.HUF, Name = "Hungarian ForINT", DecimalCount = 2, Symbol = "Ft", Countries = new List<GdCountryIso2Code>() { GdCountryIso2Code.FromString(Iso2Codes.HU) } });
            fiatList.Add(Iso3FiatCodes.IDR, new GdCurrencyFiat { Code = Iso3FiatCodes.IDR, Name = "Indonesian Rupiah", DecimalCount = 0, Symbol = "Rp", Countries = new List<GdCountryIso2Code>() { GdCountryIso2Code.FromString(Iso2Codes.ID) } });
            fiatList.Add(Iso3FiatCodes.ILS, new GdCurrencyFiat { Code = Iso3FiatCodes.ILS, Name = "Israeli Shekel", DecimalCount = 2, Symbol = "&#8362;", Countries = new List<GdCountryIso2Code>() { GdCountryIso2Code.FromString(Iso2Codes.IL) } });
            fiatList.Add(Iso3FiatCodes.INR, new GdCurrencyFiat { Code = Iso3FiatCodes.INR, Name = "Indian Rupee", DecimalCount = 2, Symbol = "INR", Countries = new List<GdCountryIso2Code>() { GdCountryIso2Code.FromString(Iso2Codes.IN) } });
            fiatList.Add(Iso3FiatCodes.IQD, new GdCurrencyFiat { Code = Iso3FiatCodes.IQD, Name = "Iraqi Dinar", DecimalCount = 2, Symbol = "ع.د", Countries = new List<GdCountryIso2Code>() { GdCountryIso2Code.FromString(Iso2Codes.IQ) } });
            fiatList.Add(Iso3FiatCodes.IRR, new GdCurrencyFiat { Code = Iso3FiatCodes.IRR, Name = "Iranian Rial", DecimalCount = 0, Symbol = "ریال", Countries = new List<GdCountryIso2Code>() { GdCountryIso2Code.FromString(Iso2Codes.IR) } });
            fiatList.Add(Iso3FiatCodes.ISK, new GdCurrencyFiat { Code = Iso3FiatCodes.ISK, Name = "Iceland Krona", DecimalCount = 2, Symbol = "null", Countries = new List<GdCountryIso2Code>() { GdCountryIso2Code.FromString(Iso2Codes.IS) } });
            fiatList.Add(Iso3FiatCodes.JMD, new GdCurrencyFiat { Code = Iso3FiatCodes.JMD, Name = "Jamaican Dollar", DecimalCount = 2, Symbol = "J$", Countries = new List<GdCountryIso2Code>() { GdCountryIso2Code.FromString(Iso2Codes.JM) } });
            fiatList.Add(Iso3FiatCodes.JOD, new GdCurrencyFiat { Code = Iso3FiatCodes.JOD, Name = "Jordanian Dinar", DecimalCount = 2, Symbol = "JOD", Countries = new List<GdCountryIso2Code>() { GdCountryIso2Code.FromString(Iso2Codes.JO) } });
            fiatList.Add(Iso3FiatCodes.JPY, new GdCurrencyFiat { Code = Iso3FiatCodes.JPY, Name = "Japanese Yen", DecimalCount = 0, Symbol = "?", Countries = new List<GdCountryIso2Code>() { GdCountryIso2Code.FromString(Iso2Codes.JP) } });
            fiatList.Add(Iso3FiatCodes.KES, new GdCurrencyFiat { Code = Iso3FiatCodes.KES, Name = "Kenyan Shilling", DecimalCount = 2, Symbol = "KES", Countries = new List<GdCountryIso2Code>() { GdCountryIso2Code.FromString(Iso2Codes.KE) } });
            fiatList.Add(Iso3FiatCodes.KGS, new GdCurrencyFiat { Code = Iso3FiatCodes.KGS, Name = "Kyrgyzstani som", DecimalCount = 2, Symbol = "С̲ ", Countries = new List<GdCountryIso2Code>() { GdCountryIso2Code.FromString(Iso2Codes.KG) } });
            fiatList.Add(Iso3FiatCodes.KHR, new GdCurrencyFiat { Code = Iso3FiatCodes.KHR, Name = "Cambodia Riel", DecimalCount = 2, Symbol = "៛", Countries = new List<GdCountryIso2Code>() { GdCountryIso2Code.FromString(Iso2Codes.KH) } });
            fiatList.Add(Iso3FiatCodes.KMF, new GdCurrencyFiat { Code = Iso3FiatCodes.KMF, Name = "Comoros Franc", DecimalCount = 2, Symbol = "KMF", Countries = new List<GdCountryIso2Code>() { GdCountryIso2Code.FromString(Iso2Codes.KM) } });
            fiatList.Add(Iso3FiatCodes.KRW, new GdCurrencyFiat { Code = Iso3FiatCodes.KRW, Name = "South Korean Won", DecimalCount = 2, Symbol = "₩", Countries = new List<GdCountryIso2Code>() { GdCountryIso2Code.FromString(Iso2Codes.KR) } });
            fiatList.Add(Iso3FiatCodes.KWD, new GdCurrencyFiat { Code = Iso3FiatCodes.KWD, Name = "Kuwaiti Dinar", DecimalCount = 2, Symbol = "د.ك", Countries = new List<GdCountryIso2Code>() { GdCountryIso2Code.FromString(Iso2Codes.KW) } });
            fiatList.Add(Iso3FiatCodes.KPW, new GdCurrencyFiat { Code = Iso3FiatCodes.KPW, Name = "North Korean Won", DecimalCount = 2, Symbol = "₩", Countries = new List<GdCountryIso2Code>() { GdCountryIso2Code.FromString(Iso2Codes.KP) } });
            fiatList.Add(Iso3FiatCodes.KYD, new GdCurrencyFiat { Code = Iso3FiatCodes.KYD, Name = "Cayman Islands Dollar", DecimalCount = 2, Symbol = "$", Countries = new List<GdCountryIso2Code>() { GdCountryIso2Code.FromString(Iso2Codes.KY) } });
            fiatList.Add(Iso3FiatCodes.KZT, new GdCurrencyFiat { Code = Iso3FiatCodes.KZT, Name = "Kazakhstan Tenge", DecimalCount = 2, Symbol = "₸", Countries = new List<GdCountryIso2Code>() { GdCountryIso2Code.FromString(Iso2Codes.KZ) } });
            fiatList.Add(Iso3FiatCodes.LAK, new GdCurrencyFiat { Code = Iso3FiatCodes.LAK, Name = "Lao Kip", DecimalCount = 2, Symbol = "&#8365;", Countries = new List<GdCountryIso2Code>() { GdCountryIso2Code.FromString(Iso2Codes.LA) } });
            fiatList.Add(Iso3FiatCodes.LBP, new GdCurrencyFiat { Code = Iso3FiatCodes.LBP, Name = "Lebanese Pound", DecimalCount = 2, Symbol = "?", Countries = new List<GdCountryIso2Code>() { GdCountryIso2Code.FromString(Iso2Codes.LB) } });
            fiatList.Add(Iso3FiatCodes.LKR, new GdCurrencyFiat { Code = Iso3FiatCodes.LKR, Name = "Sri Lanka Rupee", DecimalCount = 2, Symbol = "&#8360;", Countries = new List<GdCountryIso2Code>() { GdCountryIso2Code.FromString(Iso2Codes.LK) } });
            fiatList.Add(Iso3FiatCodes.LRD, new GdCurrencyFiat { Code = Iso3FiatCodes.LRD, Name = "Liberian Dollar", DecimalCount = 2, Symbol = "LD$", Countries = new List<GdCountryIso2Code>() { GdCountryIso2Code.FromString(Iso2Codes.LR) } });
            fiatList.Add(Iso3FiatCodes.LSL, new GdCurrencyFiat { Code = Iso3FiatCodes.LSL, Name = "Lesotho Loti", DecimalCount = 2, Symbol = "LSL", Countries = new List<GdCountryIso2Code>() { GdCountryIso2Code.FromString(Iso2Codes.LS) } });
            fiatList.Add(Iso3FiatCodes.LTL, new GdCurrencyFiat { Code = Iso3FiatCodes.LTL, Name = "Lithuanian Lita", DecimalCount = 2, Symbol = "null", Countries = new List<GdCountryIso2Code>() { } });
            fiatList.Add(Iso3FiatCodes.LVL, new GdCurrencyFiat { Code = Iso3FiatCodes.LVL, Name = "Latvian Lat", DecimalCount = 2, Symbol = "null", Countries = new List<GdCountryIso2Code>() { GdCountryIso2Code.FromString(Iso2Codes.LV) } });
            fiatList.Add(Iso3FiatCodes.LYD, new GdCurrencyFiat { Code = Iso3FiatCodes.LYD, Name = "Libyan Dinar", DecimalCount = 2, Symbol = "LYD", Countries = new List<GdCountryIso2Code>() { GdCountryIso2Code.FromString(Iso2Codes.LY) } });
            fiatList.Add(Iso3FiatCodes.MAD, new GdCurrencyFiat { Code = Iso3FiatCodes.MAD, Name = "Moroccan Dirham", DecimalCount = 2, Symbol = "MAD", Countries = new List<GdCountryIso2Code>() { GdCountryIso2Code.FromString(Iso2Codes.MA), GdCountryIso2Code.FromString(Iso2Codes.EH) } });
            fiatList.Add(Iso3FiatCodes.MDL, new GdCurrencyFiat { Code = Iso3FiatCodes.MDL, Name = "Moldovan Leu", DecimalCount = 2, Symbol = "null", Countries = new List<GdCountryIso2Code>() { GdCountryIso2Code.FromString(Iso2Codes.MD) } });
            fiatList.Add(Iso3FiatCodes.MGF, new GdCurrencyFiat { Code = Iso3FiatCodes.MGF, Name = "Malagasy Franc", DecimalCount = 2, Symbol = "MF", Countries = new List<GdCountryIso2Code>() { GdCountryIso2Code.FromString(Iso2Codes.MG) } });
            fiatList.Add(Iso3FiatCodes.MKD, new GdCurrencyFiat { Code = Iso3FiatCodes.MKD, Name = "Macedonian Denar", DecimalCount = 2, Symbol = "null", Countries = new List<GdCountryIso2Code>() { GdCountryIso2Code.FromString(Iso2Codes.MK) } });
            fiatList.Add(Iso3FiatCodes.MMK, new GdCurrencyFiat { Code = Iso3FiatCodes.MMK, Name = "Myanmar Kyat", DecimalCount = 2, Symbol = "K", Countries = new List<GdCountryIso2Code>() { GdCountryIso2Code.FromString(Iso2Codes.MM) } });
            fiatList.Add(Iso3FiatCodes.MNT, new GdCurrencyFiat { Code = Iso3FiatCodes.MNT, Name = "Mongolian Tugrik", DecimalCount = 2, Symbol = "&#8366;", Countries = new List<GdCountryIso2Code>() { GdCountryIso2Code.FromString(Iso2Codes.MN) } });
            fiatList.Add(Iso3FiatCodes.MOP, new GdCurrencyFiat { Code = Iso3FiatCodes.MOP, Name = "Macau Pataca", DecimalCount = 2, Symbol = "MOP", Countries = new List<GdCountryIso2Code>() { GdCountryIso2Code.FromString(Iso2Codes.MO) } });
            fiatList.Add(Iso3FiatCodes.MRO, new GdCurrencyFiat { Code = Iso3FiatCodes.MRO, Name = "Mauritania Ougulya", DecimalCount = 2, Symbol = "MRO", Countries = new List<GdCountryIso2Code>() { GdCountryIso2Code.FromString(Iso2Codes.MR) } });
            fiatList.Add(Iso3FiatCodes.MUR, new GdCurrencyFiat { Code = Iso3FiatCodes.MUR, Name = "Mauritius Rupee", DecimalCount = 2, Symbol = "&#8360;", Countries = new List<GdCountryIso2Code>() { GdCountryIso2Code.FromString(Iso2Codes.MU) } });
            fiatList.Add(Iso3FiatCodes.MVR, new GdCurrencyFiat { Code = Iso3FiatCodes.MVR, Name = "Maldives Rufiyaa", DecimalCount = 2, Symbol = "MVR", Countries = new List<GdCountryIso2Code>() { GdCountryIso2Code.FromString(Iso2Codes.MV) } });
            fiatList.Add(Iso3FiatCodes.MWK, new GdCurrencyFiat { Code = Iso3FiatCodes.MWK, Name = "Malawi Kwacha", DecimalCount = 2, Symbol = "MWK", Countries = new List<GdCountryIso2Code>() { GdCountryIso2Code.FromString(Iso2Codes.MW) } });
            fiatList.Add(Iso3FiatCodes.MXN, new GdCurrencyFiat { Code = Iso3FiatCodes.MXN, Name = "Mexican Peso", DecimalCount = 2, Symbol = "null", Countries = new List<GdCountryIso2Code>() { GdCountryIso2Code.FromString(Iso2Codes.MX) } });
            fiatList.Add(Iso3FiatCodes.MYR, new GdCurrencyFiat { Code = Iso3FiatCodes.MYR, Name = "Malaysian Ringgit", DecimalCount = 2, Symbol = "RM", Countries = new List<GdCountryIso2Code>() { GdCountryIso2Code.FromString(Iso2Codes.MY) } });
            fiatList.Add(Iso3FiatCodes.MZM, new GdCurrencyFiat { Code = Iso3FiatCodes.MZM, Name = "Mozambican Metical", DecimalCount = 2, Symbol = "MT", Countries = new List<GdCountryIso2Code>() { GdCountryIso2Code.FromString(Iso2Codes.MZ) } });
            fiatList.Add(Iso3FiatCodes.NAD, new GdCurrencyFiat { Code = Iso3FiatCodes.NAD, Name = "Namibian Dollar", DecimalCount = 2, Symbol = "null", Countries = new List<GdCountryIso2Code>() { GdCountryIso2Code.FromString(Iso2Codes.NA) } });
            fiatList.Add(Iso3FiatCodes.NGN, new GdCurrencyFiat { Code = Iso3FiatCodes.NGN, Name = "Nigerian Naira", DecimalCount = 2, Symbol = "₦", Countries = new List<GdCountryIso2Code>() { GdCountryIso2Code.FromString(Iso2Codes.NG) } });
            fiatList.Add(Iso3FiatCodes.NIO, new GdCurrencyFiat { Code = Iso3FiatCodes.NIO, Name = "Nicaragua Cordoba", DecimalCount = 2, Symbol = "null", Countries = new List<GdCountryIso2Code>() { GdCountryIso2Code.FromString(Iso2Codes.NI) } });
            fiatList.Add(Iso3FiatCodes.NOK, new GdCurrencyFiat { Code = Iso3FiatCodes.NOK, Name = "Norwegian Krone", DecimalCount = 2, Symbol = "kr", Countries = new List<GdCountryIso2Code>() { GdCountryIso2Code.FromString(Iso2Codes.AQ), GdCountryIso2Code.FromString(Iso2Codes.NO) } });
            fiatList.Add(Iso3FiatCodes.NPR, new GdCurrencyFiat { Code = Iso3FiatCodes.NPR, Name = "Nepalese Rupee", DecimalCount = 2, Symbol = "&#8360;", Countries = new List<GdCountryIso2Code>() { GdCountryIso2Code.FromString(Iso2Codes.NP) } });
            fiatList.Add(Iso3FiatCodes.NZD, new GdCurrencyFiat { Code = Iso3FiatCodes.NZD, Name = "New Zealand Dollar", DecimalCount = 2, Symbol = "$", Countries = new List<GdCountryIso2Code>() { GdCountryIso2Code.FromString(Iso2Codes.CK), GdCountryIso2Code.FromString(Iso2Codes.NZ), GdCountryIso2Code.FromString(Iso2Codes.NU), GdCountryIso2Code.FromString(Iso2Codes.PN), GdCountryIso2Code.FromString(Iso2Codes.TK) } });
            fiatList.Add(Iso3FiatCodes.OMR, new GdCurrencyFiat { Code = Iso3FiatCodes.OMR, Name = "Omani Rial", DecimalCount = 2, Symbol = "&#65020;", Countries = new List<GdCountryIso2Code>() { GdCountryIso2Code.FromString(Iso2Codes.OM) } });
            fiatList.Add(Iso3FiatCodes.PAB, new GdCurrencyFiat { Code = Iso3FiatCodes.PAB, Name = "Panama Balboa", DecimalCount = 2, Symbol = "B/.", Countries = new List<GdCountryIso2Code>() { GdCountryIso2Code.FromString(Iso2Codes.PA) } });
            fiatList.Add(Iso3FiatCodes.PEN, new GdCurrencyFiat { Code = Iso3FiatCodes.PEN, Name = "Peruvian Nuevo Sol", DecimalCount = 2, Symbol = "S/.", Countries = new List<GdCountryIso2Code>() { GdCountryIso2Code.FromString(Iso2Codes.PE) } });
            fiatList.Add(Iso3FiatCodes.PGK, new GdCurrencyFiat { Code = Iso3FiatCodes.PGK, Name = "Papua New Guinea Kina", DecimalCount = 2, Symbol = "PGK", Countries = new List<GdCountryIso2Code>() { GdCountryIso2Code.FromString(Iso2Codes.PG) } });
            fiatList.Add(Iso3FiatCodes.PHP, new GdCurrencyFiat { Code = Iso3FiatCodes.PHP, Name = "Philippine Peso", DecimalCount = 2, Symbol = "Php", Countries = new List<GdCountryIso2Code>() { GdCountryIso2Code.FromString(Iso2Codes.PH) } });
            fiatList.Add(Iso3FiatCodes.PKR, new GdCurrencyFiat { Code = Iso3FiatCodes.PKR, Name = "Pakistani Rupee", DecimalCount = 2, Symbol = "&#8360;", Countries = new List<GdCountryIso2Code>() { GdCountryIso2Code.FromString(Iso2Codes.PK) } });
            fiatList.Add(Iso3FiatCodes.PLN, new GdCurrencyFiat { Code = Iso3FiatCodes.PLN, Name = "Polish Zloty", DecimalCount = 2, Symbol = "z&#322;", Countries = new List<GdCountryIso2Code>() { GdCountryIso2Code.FromString(Iso2Codes.PL) } });
            fiatList.Add(Iso3FiatCodes.PYG, new GdCurrencyFiat { Code = Iso3FiatCodes.PYG, Name = "Paraguayan Guarani", DecimalCount = 2, Symbol = "Gs", Countries = new List<GdCountryIso2Code>() { GdCountryIso2Code.FromString(Iso2Codes.PY) } });
            fiatList.Add(Iso3FiatCodes.QAR, new GdCurrencyFiat { Code = Iso3FiatCodes.QAR, Name = "Qatar Rial", DecimalCount = 2, Symbol = "&#65020;", Countries = new List<GdCountryIso2Code>() { GdCountryIso2Code.FromString(Iso2Codes.QA) } });
            fiatList.Add(Iso3FiatCodes.RON, new GdCurrencyFiat { Code = Iso3FiatCodes.RON, Name = "Romanian New Leu", DecimalCount = 2, Symbol = "lei", Countries = new List<GdCountryIso2Code>() { GdCountryIso2Code.FromString(Iso2Codes.RO) } });
            fiatList.Add(Iso3FiatCodes.RSD, new GdCurrencyFiat { Code = Iso3FiatCodes.RSD, Name = "Serbian Dinar", DecimalCount = 2, Symbol = "дин", Countries = new List<GdCountryIso2Code>() { GdCountryIso2Code.FromString(Iso2Codes.RS) } });
            fiatList.Add(Iso3FiatCodes.RUB, new GdCurrencyFiat { Code = Iso3FiatCodes.RUB, Name = "Russian Rouble", DecimalCount = 2, Symbol = "&#1088;&#1091;&#1073", Countries = new List<GdCountryIso2Code>() { GdCountryIso2Code.FromString(Iso2Codes.RU) } });
            fiatList.Add(Iso3FiatCodes.RWF, new GdCurrencyFiat { Code = Iso3FiatCodes.RWF, Name = "Rwanda Franc", DecimalCount = 2, Symbol = "RWF", Countries = new List<GdCountryIso2Code>() { GdCountryIso2Code.FromString(Iso2Codes.RW) } });
            fiatList.Add(Iso3FiatCodes.SAR, new GdCurrencyFiat { Code = Iso3FiatCodes.SAR, Name = "Saudi Arabian Riyal", DecimalCount = 2, Symbol = "&#65020;", Countries = new List<GdCountryIso2Code>() { GdCountryIso2Code.FromString(Iso2Codes.SA) } });
            fiatList.Add(Iso3FiatCodes.SBD, new GdCurrencyFiat { Code = Iso3FiatCodes.SBD, Name = "Solomon Islands Dollar", DecimalCount = 2, Symbol = "SI$", Countries = new List<GdCountryIso2Code>() { GdCountryIso2Code.FromString(Iso2Codes.SB) } });
            fiatList.Add(Iso3FiatCodes.SDG, new GdCurrencyFiat { Code = Iso3FiatCodes.SDG, Name = "Sudanese Pound", DecimalCount = 2, Symbol = "£SD", Countries = new List<GdCountryIso2Code>() { GdCountryIso2Code.FromString(Iso2Codes.SD) } });
            fiatList.Add(Iso3FiatCodes.SCR, new GdCurrencyFiat { Code = Iso3FiatCodes.SCR, Name = "Seychelles Rupee", DecimalCount = 2, Symbol = "&#8360;", Countries = new List<GdCountryIso2Code>() { GdCountryIso2Code.FromString(Iso2Codes.SC) } });
            fiatList.Add(Iso3FiatCodes.SEK, new GdCurrencyFiat { Code = Iso3FiatCodes.SEK, Name = "Swedish Krona", DecimalCount = 2, Symbol = "kr", Countries = new List<GdCountryIso2Code>() { GdCountryIso2Code.FromString(Iso2Codes.SE) } });
            fiatList.Add(Iso3FiatCodes.SGD, new GdCurrencyFiat { Code = Iso3FiatCodes.SGD, Name = "Singapore Dollar", DecimalCount = 2, Symbol = "$", Countries = new List<GdCountryIso2Code>() { GdCountryIso2Code.FromString(Iso2Codes.SG) } });
            fiatList.Add(Iso3FiatCodes.SHP, new GdCurrencyFiat { Code = Iso3FiatCodes.SHP, Name = "St Helena Pound", DecimalCount = 2, Symbol = "?", Countries = new List<GdCountryIso2Code>() { GdCountryIso2Code.FromString(Iso2Codes.SH), GdCountryIso2Code.FromString(Iso2Codes.AC) } });
            fiatList.Add(Iso3FiatCodes.SIT, new GdCurrencyFiat { Code = Iso3FiatCodes.SIT, Name = "Slovenian Tolar", DecimalCount = 2, Symbol = "null", Countries = new List<GdCountryIso2Code>() { } });
            fiatList.Add(Iso3FiatCodes.SLL, new GdCurrencyFiat { Code = Iso3FiatCodes.SLL, Name = "Sierra Leone Leone", DecimalCount = 2, Symbol = "SLL", Countries = new List<GdCountryIso2Code>() { GdCountryIso2Code.FromString(Iso2Codes.SL) } });
            fiatList.Add(Iso3FiatCodes.SOS, new GdCurrencyFiat { Code = Iso3FiatCodes.SOS, Name = "Somali Shilling", DecimalCount = 2, Symbol = "S", Countries = new List<GdCountryIso2Code>() { GdCountryIso2Code.FromString(Iso2Codes.SO) } });
            fiatList.Add(Iso3FiatCodes.SRG, new GdCurrencyFiat { Code = Iso3FiatCodes.SRG, Name = "Surinamese Guilder", DecimalCount = 2, Symbol = "fl", Countries = new List<GdCountryIso2Code>() { GdCountryIso2Code.FromString(Iso2Codes.SR) } });
            fiatList.Add(Iso3FiatCodes.SSP, new GdCurrencyFiat { Code = Iso3FiatCodes.SSP, Name = "South Sudanese Pound", DecimalCount = 2, Symbol = "SS£", Countries = new List<GdCountryIso2Code>() { GdCountryIso2Code.FromString(Iso2Codes.SS) } });
            fiatList.Add(Iso3FiatCodes.STD, new GdCurrencyFiat { Code = Iso3FiatCodes.STD, Name = "Sao Tome Dobra", DecimalCount = 2, Symbol = "STD", Countries = new List<GdCountryIso2Code>() { GdCountryIso2Code.FromString(Iso2Codes.ST) } });
            fiatList.Add(Iso3FiatCodes.SYP, new GdCurrencyFiat { Code = Iso3FiatCodes.SYP, Name = "Syrian Pound", DecimalCount = 2, Symbol = "?", Countries = new List<GdCountryIso2Code>() { GdCountryIso2Code.FromString(Iso2Codes.SY) } });
            fiatList.Add(Iso3FiatCodes.SZL, new GdCurrencyFiat { Code = Iso3FiatCodes.SZL, Name = "Swaziland Lilageni", DecimalCount = 2, Symbol = "SZL", Countries = new List<GdCountryIso2Code>() { GdCountryIso2Code.FromString(Iso2Codes.SZ) } });
            fiatList.Add(Iso3FiatCodes.THB, new GdCurrencyFiat { Code = Iso3FiatCodes.THB, Name = "Thai Baht", DecimalCount = 2, Symbol = "฿", Countries = new List<GdCountryIso2Code>() { GdCountryIso2Code.FromString(Iso2Codes.TH) } });
            fiatList.Add(Iso3FiatCodes.TJS, new GdCurrencyFiat { Code = Iso3FiatCodes.TJS, Name = "Tajikistani Somoni", DecimalCount = 2, Symbol = "SM", Countries = new List<GdCountryIso2Code>() { GdCountryIso2Code.FromString(Iso2Codes.TJ) } });
            fiatList.Add(Iso3FiatCodes.TMM, new GdCurrencyFiat { Code = Iso3FiatCodes.TMM, Name = "Turkmenistani Manat", DecimalCount = 2, Symbol = "m", Countries = new List<GdCountryIso2Code>() { GdCountryIso2Code.FromString(Iso2Codes.TJ) } });
            fiatList.Add(Iso3FiatCodes.TND, new GdCurrencyFiat { Code = Iso3FiatCodes.TND, Name = "Tunisian Dinar", DecimalCount = 2, Symbol = "TND", Countries = new List<GdCountryIso2Code>() { GdCountryIso2Code.FromString(Iso2Codes.TN) } });
            fiatList.Add(Iso3FiatCodes.TOP, new GdCurrencyFiat { Code = Iso3FiatCodes.TOP, Name = "Tonga Paanga", DecimalCount = 2, Symbol = "TOP", Countries = new List<GdCountryIso2Code>() { GdCountryIso2Code.FromString(Iso2Codes.TO) } });
            fiatList.Add(Iso3FiatCodes.TRY, new GdCurrencyFiat { Code = Iso3FiatCodes.TRY, Name = "Turkish Lira", DecimalCount = 2, Symbol = "TL", Countries = new List<GdCountryIso2Code>() { GdCountryIso2Code.FromString(Iso2Codes.TR) } });
            fiatList.Add(Iso3FiatCodes.TTD, new GdCurrencyFiat { Code = Iso3FiatCodes.TTD, Name = "Trinidad&Tobago Dollar", DecimalCount = 2, Symbol = "TT$", Countries = new List<GdCountryIso2Code>() { GdCountryIso2Code.FromString(Iso2Codes.TT) } });
            fiatList.Add(Iso3FiatCodes.TWD, new GdCurrencyFiat { Code = Iso3FiatCodes.TWD, Name = "Taiwan Dollar", DecimalCount = 2, Symbol = "NT$", Countries = new List<GdCountryIso2Code>() { GdCountryIso2Code.FromString(Iso2Codes.TW) } });
            fiatList.Add(Iso3FiatCodes.TZS, new GdCurrencyFiat { Code = Iso3FiatCodes.TZS, Name = "Tanzanian Shilling", DecimalCount = 2, Symbol = "TZS", Countries = new List<GdCountryIso2Code>() { GdCountryIso2Code.FromString(Iso2Codes.TZ) } });
            fiatList.Add(Iso3FiatCodes.UAH, new GdCurrencyFiat { Code = Iso3FiatCodes.UAH, Name = "Ukraine Hryvnia", DecimalCount = 2, Symbol = "null", Countries = new List<GdCountryIso2Code>() { GdCountryIso2Code.FromString(Iso2Codes.UA) } });
            fiatList.Add(Iso3FiatCodes.UGX, new GdCurrencyFiat { Code = Iso3FiatCodes.UGX, Name = "Ugandan Shilling", DecimalCount = 2, Symbol = "null", Countries = new List<GdCountryIso2Code>() { GdCountryIso2Code.FromString(Iso2Codes.UG) } });
            fiatList.Add(Iso3FiatCodes.USD, new GdCurrencyFiat { Code = Iso3FiatCodes.USD, Name = "U.S. Dollar", DecimalCount = 2, Symbol = "$", Countries = new List<GdCountryIso2Code>() { GdCountryIso2Code.FromString(Iso2Codes.AS), GdCountryIso2Code.FromString(Iso2Codes.IO), GdCountryIso2Code.FromString(Iso2Codes.EC), GdCountryIso2Code.FromString(Iso2Codes.SV), GdCountryIso2Code.FromString(Iso2Codes.GU), GdCountryIso2Code.FromString(Iso2Codes.MH), GdCountryIso2Code.FromString(Iso2Codes.FM), GdCountryIso2Code.FromString(Iso2Codes.MP), GdCountryIso2Code.FromString(Iso2Codes.PW), GdCountryIso2Code.FromString(Iso2Codes.PR), GdCountryIso2Code.FromString(Iso2Codes.TC), GdCountryIso2Code.FromString(Iso2Codes.US), GdCountryIso2Code.FromString(Iso2Codes.VG), GdCountryIso2Code.FromString(Iso2Codes.VI), GdCountryIso2Code.FromString(Iso2Codes.XN), GdCountryIso2Code.FromString(Iso2Codes.TL), GdCountryIso2Code.FromString(Iso2Codes.GO) } });
            fiatList.Add(Iso3FiatCodes.UYU, new GdCurrencyFiat { Code = Iso3FiatCodes.UYU, Name = "Uruguayan New Peso", DecimalCount = 2, Symbol = "null", Countries = new List<GdCountryIso2Code>() { GdCountryIso2Code.FromString(Iso2Codes.UY) } });
            fiatList.Add(Iso3FiatCodes.UZS, new GdCurrencyFiat { Code = Iso3FiatCodes.UZS, Name = "Uzbekistani Soʻm", DecimalCount = 2, Symbol = "сум", Countries = new List<GdCountryIso2Code>() { GdCountryIso2Code.FromString(Iso2Codes.UZ) } });
            fiatList.Add(Iso3FiatCodes.VES, new GdCurrencyFiat { Code = Iso3FiatCodes.VES, Name = "Venezuelan Bolívar", DecimalCount = 2, Symbol = "Bs.S", Countries = new List<GdCountryIso2Code>() { GdCountryIso2Code.FromString(Iso2Codes.VE) } });
            fiatList.Add(Iso3FiatCodes.VND, new GdCurrencyFiat { Code = Iso3FiatCodes.VND, Name = "Vietnam Dong", DecimalCount = 2, Symbol = "&#8363;", Countries = new List<GdCountryIso2Code>() { GdCountryIso2Code.FromString(Iso2Codes.VN) } });
            fiatList.Add(Iso3FiatCodes.VUV, new GdCurrencyFiat { Code = Iso3FiatCodes.VUV, Name = "Vanuatu Vatu", DecimalCount = 2, Symbol = "VUV", Countries = new List<GdCountryIso2Code>() { GdCountryIso2Code.FromString(Iso2Codes.VU) } });
            fiatList.Add(Iso3FiatCodes.WST, new GdCurrencyFiat { Code = Iso3FiatCodes.WST, Name = "Samoa Tala", DecimalCount = 2, Symbol = "WST", Countries = new List<GdCountryIso2Code>() { GdCountryIso2Code.FromString(Iso2Codes.WS) } });
            fiatList.Add(Iso3FiatCodes.XAF, new GdCurrencyFiat { Code = Iso3FiatCodes.XAF, Name = "CFA Franc (BEAC)", DecimalCount = 2, Symbol = "null", Countries = new List<GdCountryIso2Code>() { GdCountryIso2Code.FromString(Iso2Codes.BJ), GdCountryIso2Code.FromString(Iso2Codes.BF), GdCountryIso2Code.FromString(Iso2Codes.CM), GdCountryIso2Code.FromString(Iso2Codes.CF), GdCountryIso2Code.FromString(Iso2Codes.TD), GdCountryIso2Code.FromString(Iso2Codes.CG), GdCountryIso2Code.FromString(Iso2Codes.CI), GdCountryIso2Code.FromString(Iso2Codes.GQ), GdCountryIso2Code.FromString(Iso2Codes.GA), GdCountryIso2Code.FromString(Iso2Codes.ML), GdCountryIso2Code.FromString(Iso2Codes.TG) } });
            fiatList.Add(Iso3FiatCodes.XAU, new GdCurrencyFiat { Code = Iso3FiatCodes.XAU, Name = "Gold Ounces", DecimalCount = 2, Symbol = "null", Countries = new List<GdCountryIso2Code>() { } });
            fiatList.Add(Iso3FiatCodes.XCD, new GdCurrencyFiat { Code = Iso3FiatCodes.XCD, Name = "East Caribbean Dollar", DecimalCount = 2, Symbol = "null", Countries = new List<GdCountryIso2Code>() { GdCountryIso2Code.FromString(Iso2Codes.AI), GdCountryIso2Code.FromString(Iso2Codes.DM), GdCountryIso2Code.FromString(Iso2Codes.GD), GdCountryIso2Code.FromString(Iso2Codes.MS), GdCountryIso2Code.FromString(Iso2Codes.KN), GdCountryIso2Code.FromString(Iso2Codes.LC), GdCountryIso2Code.FromString(Iso2Codes.VC) } });
            fiatList.Add(Iso3FiatCodes.XOF, new GdCurrencyFiat { Code = Iso3FiatCodes.XOF, Name = "CFA Franc (BCEAO)", DecimalCount = 2, Symbol = "null", Countries = new List<GdCountryIso2Code>() { GdCountryIso2Code.FromString(Iso2Codes.NE), GdCountryIso2Code.FromString(Iso2Codes.SN) } });
            fiatList.Add(Iso3FiatCodes.XPF, new GdCurrencyFiat { Code = Iso3FiatCodes.XPF, Name = "Pacific Franc", DecimalCount = 2, Symbol = "null", Countries = new List<GdCountryIso2Code>() { GdCountryIso2Code.FromString(Iso2Codes.PF), GdCountryIso2Code.FromString(Iso2Codes.NC), GdCountryIso2Code.FromString(Iso2Codes.WF) } });
            fiatList.Add(Iso3FiatCodes.YER, new GdCurrencyFiat { Code = Iso3FiatCodes.YER, Name = "Yemen Riyal", DecimalCount = 2, Symbol = "&#65020;", Countries = new List<GdCountryIso2Code>() { GdCountryIso2Code.FromString(Iso2Codes.YE) } });
            fiatList.Add(Iso3FiatCodes.ZAR, new GdCurrencyFiat { Code = Iso3FiatCodes.ZAR, Name = "South African Rand", DecimalCount = 2, Symbol = "R", Countries = new List<GdCountryIso2Code>() { GdCountryIso2Code.FromString(Iso2Codes.ZA) } });
            fiatList.Add(Iso3FiatCodes.ZMW, new GdCurrencyFiat { Code = Iso3FiatCodes.ZMW, Name = "Zambian Kwacha", DecimalCount = 2, Symbol = "ZMK", Countries = new List<GdCountryIso2Code>() { GdCountryIso2Code.FromString(Iso2Codes.ZM) } });
            fiatList.Add(Iso3FiatCodes.ZWD, new GdCurrencyFiat { Code = Iso3FiatCodes.ZWD, Name = "Zimbabwean dollar", DecimalCount = 2, Symbol = "$", Countries = new List<GdCountryIso2Code>() { GdCountryIso2Code.FromString(Iso2Codes.ZW) } });

            return fiatList;
        }



        static GdCurrencyFiatList()
        {
            List<GdCountry> list = new List<GdCountry>()
            {

            };
        }

        /// <summary>
        /// Get a GdCountry by Iso2 Code.
        /// </summary>
        /// <param name="gdCountryCode"></param>
        /// <returns>Instance of GdCountry</returns>
        public static GdCurrencyFiat Get(GdCurrencyFiatCode gdCountryCode)
        {
            if (GdCurrencyFiatListDict.TryGetValue(gdCountryCode.Code, out GdCurrencyFiat value))
                return value;

            throw new Exception("Bad Country Code");
        }

        public static GdCurrencyFiat[] GetAll()
        {
            return GdCurrencyFiatListDict.Values.ToArray();
        }
    }
}
