using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace GlobalData.Currency
{
    public static class Iso3FiatCodes
    {
        // Generated by SQL:
        /*
        SELECT CONCAT('/// <summary>', CHARACTER(13),
              '/// ',REGEXP_REPLACE(cur.name, '\\([A-Z]{3}\\)',''), CHARACTER(13),
              '/// </summary>', CHARACTER(13),
              'public const string ', `code`, ' = "',`code`,'";', CHARACTER(13), CHARACTER(13))
        FROM gd_currencies cur
        ORDER BY code		  
	
        */
        #region 3 Letter Code
        /// <summary>
        /// Abkhazian Apsar
        /// </summary>
        public const string ABK = "ABK";

        /// <summary>
        /// UAE Dirham 
        /// </summary>
        public const string AED = "AED";

        /// <summary>
        /// Afghanistan Afghani
        /// </summary>
        public const string AFN = "AFN";

        /// <summary>
        /// Albanian Lek 
        /// </summary>
        public const string ALL = "ALL";

        /// <summary>
        /// Abkhazian apsar
        /// </summary>
        public const string AMD = "AMD";

        /// <summary>
        /// Neth Antilles Guilder 
        /// </summary>
        public const string ANG = "ANG";

        /// <summary>
        /// Angola Kwanza
        /// </summary>
        public const string AOA = "AOA";

        /// <summary>
        /// Argentine Peso 
        /// </summary>
        public const string ARS = "ARS";

        /// <summary>
        /// Australian Dollar 
        /// </summary>
        public const string AUD = "AUD";

        /// <summary>
        /// Aruba Florin 
        /// </summary>
        public const string AWG = "AWG";

        /// <summary>
        /// Azerbaijani Manat
        /// </summary>
        public const string AZN = "AZN";

        /// <summary>
        /// Bosnia and Herzegovina Convertible Mark
        /// </summary>
        public const string BAM = "BAM";

        /// <summary>
        /// Barbados Dollar 
        /// </summary>
        public const string BBD = "BBD";

        /// <summary>
        /// Bangladesh Taka 
        /// </summary>
        public const string BDT = "BDT";

        /// <summary>
        /// Bulgarian Lev 
        /// </summary>
        public const string BGN = "BGN";

        /// <summary>
        /// Bahraini Dinar 
        /// </summary>
        public const string BHD = "BHD";

        /// <summary>
        /// Burundi Franc 
        /// </summary>
        public const string BIF = "BIF";

        /// <summary>
        /// Bermuda Dollar 
        /// </summary>
        public const string BMD = "BMD";

        /// <summary>
        /// Brunei Dollar 
        /// </summary>
        public const string BND = "BND";

        /// <summary>
        /// Bolivian Boliviano 
        /// </summary>
        public const string BOB = "BOB";

        /// <summary>
        /// Brazilian Real 
        /// </summary>
        public const string BRL = "BRL";

        /// <summary>
        /// Bahamian Dollar 
        /// </summary>
        public const string BSD = "BSD";

        /// <summary>
        /// Bhutan Ngultrum 
        /// </summary>
        public const string BTN = "BTN";

        /// <summary>
        /// Botswana Pula
        /// </summary>
        public const string BWP = "BWP";

        /// <summary>
        /// Belarus Ruble 
        /// </summary>
        public const string BYR = "BYR";

        /// <summary>
        /// Belize Dollar 
        /// </summary>
        public const string BZD = "BZD";

        /// <summary>
        /// Canadian Dollar 
        /// </summary>
        public const string CAD = "CAD";

        /// <summary>
        /// Congolese Franc
        /// </summary>
        public const string CDF = "CDF";

        /// <summary>
        /// Swiss Franc 
        /// </summary>
        public const string CHF = "CHF";

        /// <summary>
        /// Chilean Peso 
        /// </summary>
        public const string CLP = "CLP";

        /// <summary>
        /// Chinese Yuan 
        /// </summary>
        public const string CNY = "CNY";

        /// <summary>
        /// Colombian Peso 
        /// </summary>
        public const string COP = "COP";

        /// <summary>
        /// Costa Rica Colon 
        /// </summary>
        public const string CRC = "CRC";

        /// <summary>
        /// Cuban Peso 
        /// </summary>
        public const string CUP = "CUP";

        /// <summary>
        /// Cape Verde Escudo
        /// </summary>
        public const string CVE = "CVE";

        /// <summary>
        /// Czech Koruna 
        /// </summary>
        public const string CZK = "CZK";

        /// <summary>
        /// Dijibouti Franc 
        /// </summary>
        public const string DJF = "DJF";

        /// <summary>
        /// Danish Krone 
        /// </summary>
        public const string DKK = "DKK";

        /// <summary>
        /// Dominican Peso 
        /// </summary>
        public const string DOP = "DOP";

        /// <summary>
        /// Algerian Dinar 
        /// </summary>
        public const string DZD = "DZD";

        /// <summary>
        /// Egyptian Pound 
        /// </summary>
        public const string EGP = "EGP";

        /// <summary>
        /// Eritrean Nakfa
        /// </summary>
        public const string ERN = "ERN";

        /// <summary>
        /// Ethiopian Birr 
        /// </summary>
        public const string ETB = "ETB";

        /// <summary>
        /// Euro 
        /// </summary>
        public const string EUR = "EUR";

        /// <summary>
        /// Fijian Dollar
        /// </summary>
        public const string FJD = "FJD";

        /// <summary>
        /// Falkland Islands Pound 
        /// </summary>
        public const string FKP = "FKP";

        /// <summary>
        /// British Pound 
        /// </summary>
        public const string GBP = "GBP";

        /// <summary>
        /// Georgian Lari 
        /// </summary>
        public const string GEL = "GEL";

        /// <summary>
        /// Ghanaian Cedi
        /// </summary>
        public const string GHS = "GHS";


        /// <summary>
        /// Gibraltar Pound 
        /// </summary>
        public const string GIP = "GIP";

        /// <summary>
        /// Gambian Dalasi 
        /// </summary>
        public const string GMD = "GMD";

        /// <summary>
        /// Guinea Franc 
        /// </summary>
        public const string GNF = "GNF";

        /// <summary>
        /// Guatemala Quetzal 
        /// </summary>
        public const string GTQ = "GTQ";

        /// <summary>
        /// Guinea-Bissau peso
        /// </summary>
        public const string GWP = "GWP";

        /// <summary>
        /// Guyana Dollar 
        /// </summary>
        public const string GYD = "GYD";

        /// <summary>
        /// Hong Kong Dollar 
        /// </summary>
        public const string HKD = "HKD";

        /// <summary>
        /// Honduras Lempira 
        /// </summary>
        public const string HNL = "HNL";

        /// <summary>
        /// Croatian Kuna 
        /// </summary>
        public const string HRK = "HRK";

        /// <summary>
        /// Haiti Gourde 
        /// </summary>
        public const string HTG = "HTG";

        /// <summary>
        /// Hungarian ForINT 
        /// </summary>
        public const string HUF = "HUF";

        /// <summary>
        /// Indonesian Rupiah 
        /// </summary>
        public const string IDR = "IDR";

        /// <summary>
        /// Israeli Shekel 
        /// </summary>
        public const string ILS = "ILS";

        /// <summary>
        /// Indian Rupee 
        /// </summary>
        public const string INR = "INR";

        /// <summary>
        /// Iraqi Dinar
        /// </summary>
        public const string IQD = "IQD";

        /// <summary>
        /// Iran Rial 
        /// </summary>
        public const string IRR = "IRR";

        /// <summary>
        /// Iceland Krona 
        /// </summary>
        public const string ISK = "ISK";

        /// <summary>
        /// Jamaican Dollar 
        /// </summary>
        public const string JMD = "JMD";

        /// <summary>
        /// Jordanian Dinar 
        /// </summary>
        public const string JOD = "JOD";

        /// <summary>
        /// Japanese Yen 
        /// </summary>
        public const string JPY = "JPY";

        /// <summary>
        /// Kenyan Shilling 
        /// </summary>
        public const string KES = "KES";

        /// <summary>
        /// Kyrgyzstani Som
        /// </summary>
        public const string KGS = "KGS";

        /// <summary>
        /// Cambodia Riel 
        /// </summary>
        public const string KHR = "KHR";

        /// <summary>
        /// Comoros Franc 
        /// </summary>
        public const string KMF = "KMF";

        /// <summary>
        /// Korean Won 
        /// </summary>
        public const string KRW = "KRW";

        /// <summary>
        /// Kuwaiti Dinar 
        /// </summary>
        public const string KWD = "KWD";

        /// <summary>
        /// North Korean Won 
        /// </summary>
        public const string KPW = "KPW";

        /// <summary>
        /// Cayman Islands Dollar 
        /// </summary>
        public const string KYD = "KYD";

        /// <summary>
        /// Kazakhstan Tenge 
        /// </summary>
        public const string KZT = "KZT";

        /// <summary>
        /// Lao Kip 
        /// </summary>
        public const string LAK = "LAK";

        /// <summary>
        /// Lebanese Pound 
        /// </summary>
        public const string LBP = "LBP";

        /// <summary>
        /// Sri Lanka Rupee 
        /// </summary>
        public const string LKR = "LKR";

        /// <summary>
        /// Lesotho Loti 
        /// </summary>
        public const string LSL = "LSL";

        /// <summary>
        /// Liberian Dollar
        /// </summary>
        public const string LRD = "LRD";

        /// <summary>
        /// Lithuanian Lita 
        /// </summary>
        public const string LTL = "LTL";

        /// <summary>
        /// Latvian Lat 
        /// </summary>
        public const string LVL = "LVL";

        /// <summary>
        /// Libyan Dinar 
        /// </summary>
        public const string LYD = "LYD";

        /// <summary>
        /// Moroccan Dirham 
        /// </summary>
        public const string MAD = "MAD";

        /// <summary>
        /// Moldovan Leu 
        /// </summary>
        public const string MDL = "MDL";

        /// <summary>
        /// Malagasy Franc
        /// </summary>
        public const string MGF = "MGF";

        /// <summary>
        /// Macedonian Denar 
        /// </summary>
        public const string MKD = "MKD";

        /// <summary>
        /// Myanmar Kyat
        /// </summary>
        public const string MMK = "MMK";
        
        /// <summary>
        /// Mongolian Tugrik 
        /// </summary>
        public const string MNT = "MNT";

        /// <summary>
        /// Macau Pataca 
        /// </summary>
        public const string MOP = "MOP";

        /// <summary>
        /// Mauritania Ougulya 
        /// </summary>
        public const string MRO = "MRO";

        /// <summary>
        /// Mauritius Rupee 
        /// </summary>
        public const string MUR = "MUR";

        /// <summary>
        /// Maldives Rufiyaa 
        /// </summary>
        public const string MVR = "MVR";

        /// <summary>
        /// Malawi Kwacha 
        /// </summary>
        public const string MWK = "MWK";

        /// <summary>
        /// Mexican Peso 
        /// </summary>
        public const string MXN = "MXN";

        /// <summary>
        /// Malaysian Ringgit 
        /// </summary>
        public const string MYR = "MYR";

        /// <summary>
        /// Mozambican Metical
        /// </summary>
        public const string MZM = "MZM";
        
        /// <summary>
        /// Namibian Dollar 
        /// </summary>
        public const string NAD = "NAD";

        /// <summary>
        /// Nigerian Naira 
        /// </summary>
        public const string NGN = "NGN";

        /// <summary>
        /// Nicaragua Cordoba 
        /// </summary>
        public const string NIO = "NIO";

        /// <summary>
        /// Norwegian Krone 
        /// </summary>
        public const string NOK = "NOK";

        /// <summary>
        /// Nepalese Rupee 
        /// </summary>
        public const string NPR = "NPR";

        /// <summary>
        /// New Zealand Dollar 
        /// </summary>
        public const string NZD = "NZD";

        /// <summary>
        /// Omani Rial 
        /// </summary>
        public const string OMR = "OMR";

        /// <summary>
        /// Panama Balboa 
        /// </summary>
        public const string PAB = "PAB";

        /// <summary>
        /// Peruvian Nuevo Sol 
        /// </summary>
        public const string PEN = "PEN";

        /// <summary>
        /// Papua New Guinea Kina 
        /// </summary>
        public const string PGK = "PGK";

        /// <summary>
        /// Philippine Peso 
        /// </summary>
        public const string PHP = "PHP";

        /// <summary>
        /// Pakistani Rupee 
        /// </summary>
        public const string PKR = "PKR";

        /// <summary>
        /// Polish Zloty 
        /// </summary>
        public const string PLN = "PLN";

        /// <summary>
        /// Paraguayan Guarani 
        /// </summary>
        public const string PYG = "PYG";

        /// <summary>
        /// Qatar Rial 
        /// </summary>
        public const string QAR = "QAR";

        /// <summary>
        /// Romanian New Leu 
        /// </summary>
        public const string RON = "RON";

        /// <summary>
        /// Serbian Dinar
        /// </summary>
        public const string RSD = "RSD";

        /// <summary>
        /// Russian Rouble 
        /// </summary>
        public const string RUB = "RUB";

        /// <summary>
        /// Rwanda Franc 
        /// </summary>
        public const string RWF = "RWF";

        /// <summary>
        /// Saudi Arabian Riyal 
        /// </summary>
        public const string SAR = "SAR";

        /// <summary>
        /// Solomon Islands Dollar
        /// </summary>
        public const string SBD = "SBD";

        /// <summary>
        /// Sudanese Pound
        /// </summary>
        public const string SDG = "SDG";

        /// <summary>
        /// Seychelles Rupee 
        /// </summary>
        public const string SCR = "SCR";

        /// <summary>
        /// Swedish Krona 
        /// </summary>
        public const string SEK = "SEK";

        /// <summary>
        /// Singapore Dollar 
        /// </summary>
        public const string SGD = "SGD";

        /// <summary>
        /// St Helena Pound 
        /// </summary>
        public const string SHP = "SHP";

        /// <summary>
        /// Slovenian Tolar 
        /// </summary>
        public const string SIT = "SIT";

        /// <summary>
        /// Sierra Leone Leone 
        /// </summary>
        public const string SLL = "SLL";

        /// <summary>
        /// Somali Shilling 
        /// </summary>
        public const string SOS = "SOS";

        /// <summary>
        /// Surinamese Guilder 
        /// </summary>
        public const string SRG = "SRG";

        /// <summary>
        /// South Sudanese Pound
        /// </summary>
        public const string SSP = "SSP";

        /// <summary>
        /// Sao Tome Dobra 
        /// </summary>
        public const string STD = "STD";

        /// <summary>
        /// Syrian Pound 
        /// </summary>
        public const string SYP = "SYP";

        /// <summary>
        /// Swaziland Lilageni 
        /// </summary>
        public const string SZL = "SZL";

        /// <summary>
        /// Thai Baht 
        /// </summary>
        public const string THB = "THB";

        /// <summary>
        /// Tajikistani Somoni
        /// </summary>
        public const string TJS = "TJS";

        /// <summary>
        /// Turkmenistani Manat
        /// </summary>
        public const string TMM = "TMM";
        
        /// <summary>
        /// Tunisian Dinar 
        /// </summary>
        public const string TND = "TND";
        
        /// <summary>
        /// Tonga Paanga 
        /// </summary>
        public const string TOP = "TOP";

        /// <summary>
        /// Turkish Lira 
        /// </summary>
        public const string TRY = "TRY";

        /// <summary>
        /// Trinidad & Tobago Dollar 
        /// </summary>
        public const string TTD = "TTD";

        /// <summary>
        /// Taiwan Dollar 
        /// </summary>
        public const string TWD = "TWD";

        /// <summary>
        /// Tanzanian Shilling 
        /// </summary>
        public const string TZS = "TZS";

        /// <summary>
        /// Ukraine Hryvnia 
        /// </summary>
        public const string UAH = "UAH";

        /// <summary>
        /// Ugandan Shilling 
        /// </summary>
        public const string UGX = "UGX";

        /// <summary>
        /// U.S. Dollar 
        /// </summary>
        public const string USD = "USD";

        /// <summary>
        /// Uruguayan New Peso 
        /// </summary>
        public const string UYU = "UYU";

        /// <summary>
        /// Uzbekistani Soʻm
        /// </summary>
        public const string UZS = "UZS";

        /// <summary>
        /// Vietnam Dong 
        /// </summary>
        public const string VND = "VND";

        /// <summary>
        /// Venezuelan Bolívar 
        /// </summary>
        public const string VES = "VES";

        /// <summary>
        /// Vanuatu Vatu 
        /// </summary>
        public const string VUV = "VUV";

        /// <summary>
        /// Samoa Tala 
        /// </summary>
        public const string WST = "WST";

        /// <summary>
        /// CFA Franc (BEAC) 
        /// </summary>
        public const string XAF = "XAF";

        /// <summary>
        /// Gold Ounces 
        /// </summary>
        public const string XAU = "XAU";

        /// <summary>
        /// East Caribbean Dollar 
        /// </summary>
        public const string XCD = "XCD";

        /// <summary>
        /// CFA Franc (BCEAO) 
        /// </summary>
        public const string XOF = "XOF";

        /// <summary>
        /// Pacific Franc 
        /// </summary>
        public const string XPF = "XPF";

        /// <summary>
        /// Yemen Riyal 
        /// </summary>
        public const string YER = "YER";

        /// <summary>
        /// South African Rand 
        /// </summary>
        public const string ZAR = "ZAR";

        /// <summary>
        /// Zambian Kwacha 
        /// </summary>
        public const string ZMW = "ZMW";

        /// <summary>
        /// Zimbabwean Dollar
        /// </summary>
        public const string ZWD = "ZWD";
        #endregion

        // Generate Fullname by SQL
        /*
        SELECT CONCAT('/// <summary>', CHARACTER(13),
              '/// ',REGEXP_REPLACE(cur.name, '\\([A-Z]{3}\\)',''), CHARACTER(13),
              '/// </summary>', CHARACTER(13),
              'public const string ', REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(cur.name,'.',''), '&', '_And_'), ',', '') , ' ', '_') , '(', '') , ')', '') , '-', '_'), ' = "',`code`,'";', CHARACTER(13), CHARACTER(13))
        FROM gd_currencies cur
        ORDER BY `code`
        
        */
        #region Fullname
        /// <summary>
        /// Abkhazian Apsar
        /// </summary>
        public const string Abkhazian_Apsar = "ABK";

        /// <summary>
        /// UAE Dirham 
        /// </summary>
        public const string UAE_Dirham_AED = "AED";

        /// <summary>
        /// Afghanistan Afghani
        /// </summary>
        public const string Afghanistan_Afghani = "AFN";

        /// <summary>
        /// Albanian Lek 
        /// </summary>
        public const string Albanian_Lek_ALL = "ALL";

        /// <summary>
        /// Armenian dram
        /// </summary>
        public const string Armenian_dram = "AMD";

        /// <summary>
        /// Neth Antilles Guilder 
        /// </summary>
        public const string Neth_Antilles_Guilder_ANG = "ANG";

        /// <summary>
        /// Angolan kwanza
        /// </summary>
        public const string Angolan_kwanza = "AOA";

        /// <summary>
        /// Argentine Peso 
        /// </summary>
        public const string Argentine_Peso_ARS = "ARS";

        /// <summary>
        /// Australian Dollar 
        /// </summary>
        public const string Australian_Dollar_AUD = "AUD";

        /// <summary>
        /// Aruba Florin 
        /// </summary>
        public const string Aruba_Florin_AWG = "AWG";

        /// <summary>
        /// Azerbaijani Manat
        /// </summary>
        public const string Azerbaijani_Manat = "AZN";

        /// <summary>
        /// Bosnia and Herzegovina Convert
        /// </summary>
        public const string Bosnia_and_Herzegovina_Convert = "BAM";

        /// <summary>
        /// Barbados Dollar 
        /// </summary>
        public const string Barbados_Dollar_BBD = "BBD";

        /// <summary>
        /// Bangladesh Taka 
        /// </summary>
        public const string Bangladesh_Taka_BDT = "BDT";

        /// <summary>
        /// Bulgarian Lev 
        /// </summary>
        public const string Bulgarian_Lev_BGN = "BGN";

        /// <summary>
        /// Bahraini Dinar 
        /// </summary>
        public const string Bahraini_Dinar_BHD = "BHD";

        /// <summary>
        /// Burundi Franc 
        /// </summary>
        public const string Burundi_Franc_BIF = "BIF";

        /// <summary>
        /// Bermuda Dollar 
        /// </summary>
        public const string Bermuda_Dollar_BMD = "BMD";

        /// <summary>
        /// Brunei Dollar 
        /// </summary>
        public const string Brunei_Dollar_BND = "BND";

        /// <summary>
        /// Bolivian Boliviano 
        /// </summary>
        public const string Bolivian_Boliviano_BOB = "BOB";

        /// <summary>
        /// Brazilian Real 
        /// </summary>
        public const string Brazilian_Real_BRL = "BRL";

        /// <summary>
        /// Bahamian Dollar 
        /// </summary>
        public const string Bahamian_Dollar_BSD = "BSD";

        /// <summary>
        /// Bhutan Ngultrum 
        /// </summary>
        public const string Bhutan_Ngultrum_BTN = "BTN";

        /// <summary>
        /// Botswana Pula
        /// </summary>
        public const string Botswana_Pula = "BWP";

        /// <summary>
        /// Belarus Ruble 
        /// </summary>
        public const string Belarus_Ruble_BYR = "BYR";

        /// <summary>
        /// Belize Dollar 
        /// </summary>
        public const string Belize_Dollar_BZD = "BZD";

        /// <summary>
        /// Canadian Dollar 
        /// </summary>
        public const string Canadian_Dollar_CAD = "CAD";

        /// <summary>
        /// Swiss Franc 
        /// </summary>
        public const string Swiss_Franc_CHF = "CHF";

        /// <summary>
        /// Chilean Peso 
        /// </summary>
        public const string Chilean_Peso_CLP = "CLP";

        /// <summary>
        /// Chinese Yuan 
        /// </summary>
        public const string Chinese_Yuan_CNY = "CNY";

        /// <summary>
        /// Colombian Peso 
        /// </summary>
        public const string Colombian_Peso_COP = "COP";

        /// <summary>
        /// Costa Rica Colon 
        /// </summary>
        public const string Costa_Rica_Colon_CRC = "CRC";

        /// <summary>
        /// Cuban Peso 
        /// </summary>
        public const string Cuban_Peso_CUP = "CUP";

        /// <summary>
        /// Cape Verde Escudo
        /// </summary>
        public const string Cape_Verde_Escudo = "CVE";

        /// <summary>
        /// Czech Koruna 
        /// </summary>
        public const string Czech_Koruna_CZK = "CZK";

        /// <summary>
        /// Dijibouti Franc 
        /// </summary>
        public const string Dijibouti_Franc_DJF = "DJF";

        /// <summary>
        /// Danish Krone 
        /// </summary>
        public const string Danish_Krone_DKK = "DKK";

        /// <summary>
        /// Dominican Peso 
        /// </summary>
        public const string Dominican_Peso_DOP = "DOP";

        /// <summary>
        /// Algerian Dinar 
        /// </summary>
        public const string Algerian_Dinar_DZD = "DZD";

        /// <summary>
        /// Egyptian Pound 
        /// </summary>
        public const string Egyptian_Pound_EGP = "EGP";

        /// <summary>
        /// Eritrean Nakfa
        /// </summary>
        public const string Eritrean_Nakfa = "ERN";

        /// <summary>
        /// Ethiopian Birr 
        /// </summary>
        public const string Ethiopian_Birr_ETB = "ETB";

        /// <summary>
        /// Euro 
        /// </summary>
        public const string Euro_EUR = "EUR";

        /// <summary>
        /// Fijian Dollar
        /// </summary>
        public const string Fijian_Dollar = "FJD";

        /// <summary>
        /// Falkland Islands Pound 
        /// </summary>
        public const string Falkland_Islands_Pound_FKP = "FKP";

        /// <summary>
        /// British Pound 
        /// </summary>
        public const string British_Pound_GBP = "GBP";

        /// <summary>
        /// Georgian Lari 
        /// </summary>
        public const string Georgian_Lari_GEL = "GEL";

        /// <summary>
        /// Gibraltar Pound 
        /// </summary>
        public const string Gibraltar_Pound_GIP = "GIP";

        /// <summary>
        /// Gambian Dalasi 
        /// </summary>
        public const string Gambian_Dalasi_GMD = "GMD";

        /// <summary>
        /// Guinea Franc 
        /// </summary>
        public const string Guinea_Franc_GNF = "GNF";

        /// <summary>
        /// Guatemala Quetzal 
        /// </summary>
        public const string Guatemala_Quetzal_GTQ = "GTQ";

        /// <summary>
        /// Guyana Dollar 
        /// </summary>
        public const string Guyana_Dollar_GYD = "GYD";

        /// <summary>
        /// Hong Kong Dollar 
        /// </summary>
        public const string Hong_Kong_Dollar_HKD = "HKD";

        /// <summary>
        /// Honduras Lempira 
        /// </summary>
        public const string Honduras_Lempira_HNL = "HNL";

        /// <summary>
        /// Croatian Kuna 
        /// </summary>
        public const string Croatian_Kuna_HRK = "HRK";

        /// <summary>
        /// Haiti Gourde 
        /// </summary>
        public const string Haiti_Gourde_HTG = "HTG";

        /// <summary>
        /// Hungarian ForINT 
        /// </summary>
        public const string Hungarian_ForINT_HUF = "HUF";

        /// <summary>
        /// Indonesian Rupiah 
        /// </summary>
        public const string Indonesian_Rupiah_IDR = "IDR";

        /// <summary>
        /// Israeli Shekel 
        /// </summary>
        public const string Israeli_Shekel_ILS = "ILS";

        /// <summary>
        /// Indian Rupee 
        /// </summary>
        public const string Indian_Rupee_INR = "INR";

        /// <summary>
        /// Iraqi Dinar
        /// </summary>
        public const string Iraqi_Dinar = "IQD";

        /// <summary>
        /// Iran Rial 
        /// </summary>
        public const string Iran_Rial_IRR = "IRR";

        /// <summary>
        /// Iceland Krona 
        /// </summary>
        public const string Iceland_Krona_ISK = "ISK";

        /// <summary>
        /// Jamaican Dollar 
        /// </summary>
        public const string Jamaican_Dollar_JMD = "JMD";

        /// <summary>
        /// Jordanian Dinar 
        /// </summary>
        public const string Jordanian_Dinar_JOD = "JOD";

        /// <summary>
        /// Japanese Yen 
        /// </summary>
        public const string Japanese_Yen_JPY = "JPY";

        /// <summary>
        /// Kenyan Shilling 
        /// </summary>
        public const string Kenyan_Shilling_KES = "KES";

        /// <summary>
        /// Cambodia Riel 
        /// </summary>
        public const string Cambodia_Riel_KHR = "KHR";

        /// <summary>
        /// Comoros Franc 
        /// </summary>
        public const string Comoros_Franc_KMF = "KMF";

        /// <summary>
        /// Korean Won 
        /// </summary>
        public const string Korean_Won_KRW = "KRW";

        /// <summary>
        /// Kuwaiti Dinar 
        /// </summary>
        public const string Kuwaiti_Dinar_KWD = "KWD";

        /// <summary>
        /// Cayman Islands Dollar 
        /// </summary>
        public const string Cayman_Islands_Dollar_KYD = "KYD";

        /// <summary>
        /// Kazakhstan Tenge 
        /// </summary>
        public const string Kazakhstan_Tenge_KZT = "KZT";

        /// <summary>
        /// Lao Kip 
        /// </summary>
        public const string Lao_Kip_LAK = "LAK";

        /// <summary>
        /// Lebanese Pound 
        /// </summary>
        public const string Lebanese_Pound_LBP = "LBP";

        /// <summary>
        /// Sri Lanka Rupee 
        /// </summary>
        public const string Sri_Lanka_Rupee_LKR = "LKR";

        /// <summary>
        /// Lesotho Loti 
        /// </summary>
        public const string Lesotho_Loti_LSL = "LSL";

        /// <summary>
        /// Lithuanian Lita 
        /// </summary>
        public const string Lithuanian_Lita_LTL = "LTL";

        /// <summary>
        /// Latvian Lat 
        /// </summary>
        public const string Latvian_Lat_LVL = "LVL";

        /// <summary>
        /// Libyan Dinar 
        /// </summary>
        public const string Libyan_Dinar_LYD = "LYD";

        /// <summary>
        /// Moroccan Dirham 
        /// </summary>
        public const string Moroccan_Dirham_MAD = "MAD";

        /// <summary>
        /// Moldovan Leu 
        /// </summary>
        public const string Moldovan_Leu_MDL = "MDL";

        /// <summary>
        /// Macedonian Denar 
        /// </summary>
        public const string Macedonian_Denar_MKD = "MKD";

        /// <summary>
        /// Mongolian Tugrik 
        /// </summary>
        public const string Mongolian_Tugrik_MNT = "MNT";

        /// <summary>
        /// Macau Pataca 
        /// </summary>
        public const string Macau_Pataca_MOP = "MOP";

        /// <summary>
        /// Mauritania Ougulya 
        /// </summary>
        public const string Mauritania_Ougulya_MRO = "MRO";

        /// <summary>
        /// Mauritius Rupee 
        /// </summary>
        public const string Mauritius_Rupee_MUR = "MUR";

        /// <summary>
        /// Maldives Rufiyaa 
        /// </summary>
        public const string Maldives_Rufiyaa_MVR = "MVR";

        /// <summary>
        /// Malawi Kwacha 
        /// </summary>
        public const string Malawi_Kwacha_MWK = "MWK";

        /// <summary>
        /// Mexican Peso 
        /// </summary>
        public const string Mexican_Peso_MXN = "MXN";

        /// <summary>
        /// Malaysian Ringgit 
        /// </summary>
        public const string Malaysian_Ringgit_MYR = "MYR";

        /// <summary>
        /// Namibian Dollar 
        /// </summary>
        public const string Namibian_Dollar_NAD = "NAD";

        /// <summary>
        /// Nigerian Naira 
        /// </summary>
        public const string Nigerian_Naira_NGN = "NGN";

        /// <summary>
        /// Nicaragua Cordoba 
        /// </summary>
        public const string Nicaragua_Cordoba_NIO = "NIO";

        /// <summary>
        /// Norwegian Krone 
        /// </summary>
        public const string Norwegian_Krone_NOK = "NOK";

        /// <summary>
        /// Nepalese Rupee 
        /// </summary>
        public const string Nepalese_Rupee_NPR = "NPR";

        /// <summary>
        /// New Zealand Dollar 
        /// </summary>
        public const string New_Zealand_Dollar_NZD = "NZD";

        /// <summary>
        /// Omani Rial 
        /// </summary>
        public const string Omani_Rial_OMR = "OMR";

        /// <summary>
        /// Panama Balboa 
        /// </summary>
        public const string Panama_Balboa_PAB = "PAB";

        /// <summary>
        /// Peruvian Nuevo Sol 
        /// </summary>
        public const string Peruvian_Nuevo_Sol_PEN = "PEN";

        /// <summary>
        /// Papua New Guinea Kina 
        /// </summary>
        public const string Papua_New_Guinea_Kina_PGK = "PGK";

        /// <summary>
        /// Philippine Peso 
        /// </summary>
        public const string Philippine_Peso_PHP = "PHP";

        /// <summary>
        /// Pakistani Rupee 
        /// </summary>
        public const string Pakistani_Rupee_PKR = "PKR";

        /// <summary>
        /// Polish Zloty 
        /// </summary>
        public const string Polish_Zloty_PLN = "PLN";

        /// <summary>
        /// Paraguayan Guarani 
        /// </summary>
        public const string Paraguayan_Guarani_PYG = "PYG";

        /// <summary>
        /// Qatar Rial 
        /// </summary>
        public const string Qatar_Rial_QAR = "QAR";

        /// <summary>
        /// Romanian New Leu 
        /// </summary>
        public const string Romanian_New_Leu_RON = "RON";

        /// <summary>
        /// Russian Rouble 
        /// </summary>
        public const string Russian_Rouble_RUB = "RUB";

        /// <summary>
        /// Rwanda Franc 
        /// </summary>
        public const string Rwanda_Franc_RWF = "RWF";

        /// <summary>
        /// Saudi Arabian Riyal 
        /// </summary>
        public const string Saudi_Arabian_Riyal_SAR = "SAR";

        /// <summary>
        /// Seychelles Rupee 
        /// </summary>
        public const string Seychelles_Rupee_SCR = "SCR";

        /// <summary>
        /// Swedish Krona 
        /// </summary>
        public const string Swedish_Krona_SEK = "SEK";

        /// <summary>
        /// Singapore Dollar 
        /// </summary>
        public const string Singapore_Dollar_SGD = "SGD";

        /// <summary>
        /// St Helena Pound 
        /// </summary>
        public const string St_Helena_Pound_SHP = "SHP";

        /// <summary>
        /// Slovenian Tolar 
        /// </summary>
        public const string Slovenian_Tolar_SIT = "SIT";

        /// <summary>
        /// Sierra Leone Leone 
        /// </summary>
        public const string Sierra_Leone_Leone_SLL = "SLL";

        /// <summary>
        /// Somali Shilling 
        /// </summary>
        public const string Somali_Shilling_SOS = "SOS";

        /// <summary>
        /// Sao Tome Dobra 
        /// </summary>
        public const string Sao_Tome_Dobra_STD = "STD";

        /// <summary>
        /// Syrian Pound 
        /// </summary>
        public const string Syrian_Pound_SYP = "SYP";

        /// <summary>
        /// Swaziland Lilageni 
        /// </summary>
        public const string Swaziland_Lilageni_SZL = "SZL";

        /// <summary>
        /// Thai Baht 
        /// </summary>
        public const string Thai_Baht_THB = "THB";

        /// <summary>
        /// Tunisian Dinar 
        /// </summary>
        public const string Tunisian_Dinar_TND = "TND";

        /// <summary>
        /// Tonga Paanga 
        /// </summary>
        public const string Tonga_Paanga_TOP = "TOP";

        /// <summary>
        /// Turkish Lira 
        /// </summary>
        public const string Turkish_Lira_TRY = "TRY";

        /// <summary>
        /// Trinidad&Tobago Dollar 
        /// </summary>
        public const string Trinidad_And_Tobago_Dollar_TTD = "TTD";

        /// <summary>
        /// Taiwan Dollar 
        /// </summary>
        public const string Taiwan_Dollar_TWD = "TWD";

        /// <summary>
        /// Tanzanian Shilling 
        /// </summary>
        public const string Tanzanian_Shilling_TZS = "TZS";

        /// <summary>
        /// Ukraine Hryvnia 
        /// </summary>
        public const string Ukraine_Hryvnia_UAH = "UAH";

        /// <summary>
        /// Ugandan Shilling 
        /// </summary>
        public const string Ugandan_Shilling_UGX = "UGX";

        /// <summary>
        /// U.S. Dollar 
        /// </summary>
        public const string US_Dollar_USD = "USD";

        /// <summary>
        /// Uruguayan New Peso 
        /// </summary>
        public const string Uruguayan_New_Peso_UYU = "UYU";

        /// <summary>
        /// Vietnam Dong 
        /// </summary>
        public const string Vietnam_Dong_VND = "VND";

        /// <summary>
        /// Vanuatu Vatu 
        /// </summary>
        public const string Vanuatu_Vatu_VUV = "VUV";

        /// <summary>
        /// Samoa Tala 
        /// </summary>
        public const string Samoa_Tala_WST = "WST";

        /// <summary>
        /// CFA Franc (BEAC) 
        /// </summary>
        public const string CFA_Franc_BEAC_XAF = "XAF";

        /// <summary>
        /// Gold Ounces 
        /// </summary>
        public const string Gold_Ounces_XAU = "XAU";

        /// <summary>
        /// East Caribbean Dollar 
        /// </summary>
        public const string East_Caribbean_Dollar_XCD = "XCD";

        /// <summary>
        /// CFA Franc (BCEAO) 
        /// </summary>
        public const string CFA_Franc_BCEAO_XOF = "XOF";

        /// <summary>
        /// Pacific Franc 
        /// </summary>
        public const string Pacific_Franc_XPF = "XPF";

        /// <summary>
        /// Yemen Riyal 
        /// </summary>
        public const string Yemen_Riyal_YER = "YER";

        /// <summary>
        /// South African Rand 
        /// </summary>
        public const string South_African_Rand_ZAR = "ZAR";

        /// <summary>
        /// Zambian Kwacha 
        /// </summary>
        public const string Zambian_Kwacha_ZMK = "ZMW";

        #endregion
    }
}
