using System.Collections.Generic;
using Azihub.GlobalData.Base.Currency.Exceptions;

namespace Azihub.GlobalData.Base.Currency
{
    public class CurrencyFiatCode
    {
        private CurrencyFiatCode(string code)
        {
            Code = code;
        }

        public string Code { get; }

        public override string ToString()
        {
            return Code;
        }

        #region Dictionary
        /// <summary>
        /// Hold all countries in private memory space
        /// </summary>
        private static Dictionary<string, CurrencyFiatCode> Codes { get; } = new Dictionary<string, CurrencyFiatCode>()
        {
            // Generated by SQL:
            /*
            SELECT
	            concat(
                    '{ Iso3FiatCodes.',`code`, 
                    ', new GdCurrencyFiatCode(Iso3FiatCodes.',`code`,') }, // ',
                    REGEXP_REPLACE(name, '\\([A-Z]{3}\\)','')
                ) 
                FROM gd_currencies 
            ORDER BY `code`
            */
            #region Sql Result
            { Iso3FiatCodes.ABK, new CurrencyFiatCode(Iso3FiatCodes.ABK) }, // Abkhazian Apsar
            { Iso3FiatCodes.AED, new CurrencyFiatCode(Iso3FiatCodes.AED) }, // UAE Dirham 
            { Iso3FiatCodes.AFN, new CurrencyFiatCode(Iso3FiatCodes.AFN) }, // Afghanistan Afghani
            { Iso3FiatCodes.ALL, new CurrencyFiatCode(Iso3FiatCodes.ALL) }, // Albanian Lek 
            { Iso3FiatCodes.AMD, new CurrencyFiatCode(Iso3FiatCodes.AMD) }, // Abkhazian apsar
            { Iso3FiatCodes.ANG, new CurrencyFiatCode(Iso3FiatCodes.ANG) }, // Neth Antilles Guilder 
            { Iso3FiatCodes.AOA, new CurrencyFiatCode(Iso3FiatCodes.AOA) }, // Angola Kwanza
            { Iso3FiatCodes.ARS, new CurrencyFiatCode(Iso3FiatCodes.ARS) }, // Argentine Peso 
            { Iso3FiatCodes.AUD, new CurrencyFiatCode(Iso3FiatCodes.AUD) }, // Australian Dollar 
            { Iso3FiatCodes.AWG, new CurrencyFiatCode(Iso3FiatCodes.AWG) }, // Aruba Florin 
            { Iso3FiatCodes.AZN, new CurrencyFiatCode(Iso3FiatCodes.AZN) }, // Azerbaijani Manat
            { Iso3FiatCodes.BAM, new CurrencyFiatCode(Iso3FiatCodes.BAM) }, // Barbados Dollar 
            { Iso3FiatCodes.BBD, new CurrencyFiatCode(Iso3FiatCodes.BBD) }, // Barbados Dollar 
            { Iso3FiatCodes.BDT, new CurrencyFiatCode(Iso3FiatCodes.BDT) }, // Bangladesh Taka 
            { Iso3FiatCodes.BGN, new CurrencyFiatCode(Iso3FiatCodes.BGN) }, // Bulgarian Lev 
            { Iso3FiatCodes.BHD, new CurrencyFiatCode(Iso3FiatCodes.BHD) }, // Bahraini Dinar 
            { Iso3FiatCodes.BIF, new CurrencyFiatCode(Iso3FiatCodes.BIF) }, // Burundi Franc 
            { Iso3FiatCodes.BMD, new CurrencyFiatCode(Iso3FiatCodes.BMD) }, // Bermuda Dollar 
            { Iso3FiatCodes.BND, new CurrencyFiatCode(Iso3FiatCodes.BND) }, // Brunei Dollar 
            { Iso3FiatCodes.BOB, new CurrencyFiatCode(Iso3FiatCodes.BOB) }, // Bolivian Boliviano 
            { Iso3FiatCodes.BRL, new CurrencyFiatCode(Iso3FiatCodes.BRL) }, // Brazilian Real 
            { Iso3FiatCodes.BSD, new CurrencyFiatCode(Iso3FiatCodes.BSD) }, // Bahamian Dollar 
            { Iso3FiatCodes.BTN, new CurrencyFiatCode(Iso3FiatCodes.BTN) }, // Bhutan Ngultrum 
            { Iso3FiatCodes.BWP, new CurrencyFiatCode(Iso3FiatCodes.BWP) }, // Botswana Pula
            { Iso3FiatCodes.BYR, new CurrencyFiatCode(Iso3FiatCodes.BYR) }, // Belarus Ruble 
            { Iso3FiatCodes.BZD, new CurrencyFiatCode(Iso3FiatCodes.BZD) }, // Belize Dollar 
            { Iso3FiatCodes.CAD, new CurrencyFiatCode(Iso3FiatCodes.CAD) }, // Canadian Dollar 
            { Iso3FiatCodes.CDF, new CurrencyFiatCode(Iso3FiatCodes.CDF) }, // Congolese Franc
            { Iso3FiatCodes.CHF, new CurrencyFiatCode(Iso3FiatCodes.CHF) }, // Swiss Franc 
            { Iso3FiatCodes.CLP, new CurrencyFiatCode(Iso3FiatCodes.CLP) }, // Chilean Peso 
            { Iso3FiatCodes.CNY, new CurrencyFiatCode(Iso3FiatCodes.CNY) }, // Chinese Yuan 
            { Iso3FiatCodes.COP, new CurrencyFiatCode(Iso3FiatCodes.COP) }, // Colombian Peso 
            { Iso3FiatCodes.CRC, new CurrencyFiatCode(Iso3FiatCodes.CRC) }, // Costa Rica Colon 
            { Iso3FiatCodes.CUP, new CurrencyFiatCode(Iso3FiatCodes.CUP) }, // Cuban Peso 
            { Iso3FiatCodes.CVE, new CurrencyFiatCode(Iso3FiatCodes.CVE) }, // Cape Verde Escudo
            { Iso3FiatCodes.CZK, new CurrencyFiatCode(Iso3FiatCodes.CZK) }, // Czech Koruna 
            { Iso3FiatCodes.DJF, new CurrencyFiatCode(Iso3FiatCodes.DJF) }, // Dijibouti Franc 
            { Iso3FiatCodes.DKK, new CurrencyFiatCode(Iso3FiatCodes.DKK) }, // Danish Krone 
            { Iso3FiatCodes.DOP, new CurrencyFiatCode(Iso3FiatCodes.DOP) }, // Dominican Peso 
            { Iso3FiatCodes.DZD, new CurrencyFiatCode(Iso3FiatCodes.DZD) }, // Algerian Dinar 
            { Iso3FiatCodes.EGP, new CurrencyFiatCode(Iso3FiatCodes.EGP) }, // Egyptian Pound 
            { Iso3FiatCodes.ERN, new CurrencyFiatCode(Iso3FiatCodes.ERN) }, // Eritrean Nakfa 
            { Iso3FiatCodes.ETB, new CurrencyFiatCode(Iso3FiatCodes.ETB) }, // Ethiopian Birr 
            { Iso3FiatCodes.EUR, new CurrencyFiatCode(Iso3FiatCodes.EUR) }, // Euro 
            { Iso3FiatCodes.FKP, new CurrencyFiatCode(Iso3FiatCodes.FKP) }, // Falkland Islands Pound 
            { Iso3FiatCodes.FJD, new CurrencyFiatCode(Iso3FiatCodes.FJD) }, // Fijian Dollar
            { Iso3FiatCodes.GBP, new CurrencyFiatCode(Iso3FiatCodes.GBP) }, // British Pound 
            { Iso3FiatCodes.GEL, new CurrencyFiatCode(Iso3FiatCodes.GEL) }, // Georgian Lari 
            { Iso3FiatCodes.GHS, new CurrencyFiatCode(Iso3FiatCodes.GHS) }, // Ghanaian Cedi
            { Iso3FiatCodes.GIP, new CurrencyFiatCode(Iso3FiatCodes.GIP) }, // Gibraltar Pound 
            { Iso3FiatCodes.GMD, new CurrencyFiatCode(Iso3FiatCodes.GMD) }, // Gambian Dalasi 
            { Iso3FiatCodes.GNF, new CurrencyFiatCode(Iso3FiatCodes.GNF) }, // Guinea Franc 
            { Iso3FiatCodes.GTQ, new CurrencyFiatCode(Iso3FiatCodes.GTQ) }, // Guatemala Quetzal 
            { Iso3FiatCodes.GWP, new CurrencyFiatCode(Iso3FiatCodes.GWP) }, // Guinea-Bissau peso
            { Iso3FiatCodes.GYD, new CurrencyFiatCode(Iso3FiatCodes.GYD) }, // Guyana Dollar 
            { Iso3FiatCodes.HKD, new CurrencyFiatCode(Iso3FiatCodes.HKD) }, // Hong Kong Dollar 
            { Iso3FiatCodes.HNL, new CurrencyFiatCode(Iso3FiatCodes.HNL) }, // Honduras Lempira 
            { Iso3FiatCodes.HRK, new CurrencyFiatCode(Iso3FiatCodes.HRK) }, // Croatian Kuna 
            { Iso3FiatCodes.HTG, new CurrencyFiatCode(Iso3FiatCodes.HTG) }, // Haiti Gourde 
            { Iso3FiatCodes.HUF, new CurrencyFiatCode(Iso3FiatCodes.HUF) }, // Hungarian ForINT 
            { Iso3FiatCodes.IDR, new CurrencyFiatCode(Iso3FiatCodes.IDR) }, // Indonesian Rupiah 
            { Iso3FiatCodes.ILS, new CurrencyFiatCode(Iso3FiatCodes.ILS) }, // Israeli Shekel 
            { Iso3FiatCodes.INR, new CurrencyFiatCode(Iso3FiatCodes.INR) }, // Indian Rupee 
            { Iso3FiatCodes.IQD, new CurrencyFiatCode(Iso3FiatCodes.IQD) }, // Iraqi Dinar
            { Iso3FiatCodes.IRR, new CurrencyFiatCode(Iso3FiatCodes.IRR) }, // Iran Rial 
            { Iso3FiatCodes.ISK, new CurrencyFiatCode(Iso3FiatCodes.ISK) }, // Iceland Krona 
            { Iso3FiatCodes.JMD, new CurrencyFiatCode(Iso3FiatCodes.JMD) }, // Jamaican Dollar 
            { Iso3FiatCodes.JOD, new CurrencyFiatCode(Iso3FiatCodes.JOD) }, // Jordanian Dinar 
            { Iso3FiatCodes.JPY, new CurrencyFiatCode(Iso3FiatCodes.JPY) }, // Japanese Yen 
            { Iso3FiatCodes.KES, new CurrencyFiatCode(Iso3FiatCodes.KES) }, // Kenyan Shilling 
            { Iso3FiatCodes.KGS, new CurrencyFiatCode(Iso3FiatCodes.KGS) }, // Kyrgyzstani Som
            { Iso3FiatCodes.KHR, new CurrencyFiatCode(Iso3FiatCodes.KHR) }, // Cambodia Riel 
            { Iso3FiatCodes.KMF, new CurrencyFiatCode(Iso3FiatCodes.KMF) }, // Comoros Franc 
            { Iso3FiatCodes.KRW, new CurrencyFiatCode(Iso3FiatCodes.KRW) }, // Korean Won 
            { Iso3FiatCodes.KWD, new CurrencyFiatCode(Iso3FiatCodes.KWD) }, // Kuwaiti Dinar 
            { Iso3FiatCodes.KPW, new CurrencyFiatCode(Iso3FiatCodes.KPW) }, // North Korean Won 
            { Iso3FiatCodes.KYD, new CurrencyFiatCode(Iso3FiatCodes.KYD) }, // Cayman Islands Dollar 
            { Iso3FiatCodes.KZT, new CurrencyFiatCode(Iso3FiatCodes.KZT) }, // Kazakhstan Tenge 
            { Iso3FiatCodes.LAK, new CurrencyFiatCode(Iso3FiatCodes.LAK) }, // Lao Kip 
            { Iso3FiatCodes.LBP, new CurrencyFiatCode(Iso3FiatCodes.LBP) }, // Lebanese Pound 
            { Iso3FiatCodes.LKR, new CurrencyFiatCode(Iso3FiatCodes.LKR) }, // Sri Lanka Rupee 
            { Iso3FiatCodes.LRD, new CurrencyFiatCode(Iso3FiatCodes.LRD) }, // Liberian Dollar
            { Iso3FiatCodes.LSL, new CurrencyFiatCode(Iso3FiatCodes.LSL) }, // Lesotho Loti 
            { Iso3FiatCodes.LTL, new CurrencyFiatCode(Iso3FiatCodes.LTL) }, // Lithuanian Lita 
            { Iso3FiatCodes.LVL, new CurrencyFiatCode(Iso3FiatCodes.LVL) }, // Latvian Lat 
            { Iso3FiatCodes.LYD, new CurrencyFiatCode(Iso3FiatCodes.LYD) }, // Libyan Dinar 
            { Iso3FiatCodes.MAD, new CurrencyFiatCode(Iso3FiatCodes.MAD) }, // Moroccan Dirham 
            { Iso3FiatCodes.MDL, new CurrencyFiatCode(Iso3FiatCodes.MDL) }, // Moldovan Leu 
            { Iso3FiatCodes.MGF, new CurrencyFiatCode(Iso3FiatCodes.MGF) }, // Malagasy Franc 
            { Iso3FiatCodes.MKD, new CurrencyFiatCode(Iso3FiatCodes.MKD) }, // Macedonian Denar 
            { Iso3FiatCodes.MMK, new CurrencyFiatCode(Iso3FiatCodes.MMK) }, // Myanmar Kyat
            { Iso3FiatCodes.MNT, new CurrencyFiatCode(Iso3FiatCodes.MNT) }, // Mongolian Tugrik 
            { Iso3FiatCodes.MOP, new CurrencyFiatCode(Iso3FiatCodes.MOP) }, // Macau Pataca 
            { Iso3FiatCodes.MRO, new CurrencyFiatCode(Iso3FiatCodes.MRO) }, // Mauritania Ougulya 
            { Iso3FiatCodes.MUR, new CurrencyFiatCode(Iso3FiatCodes.MUR) }, // Mauritius Rupee 
            { Iso3FiatCodes.MVR, new CurrencyFiatCode(Iso3FiatCodes.MVR) }, // Maldives Rufiyaa 
            { Iso3FiatCodes.MWK, new CurrencyFiatCode(Iso3FiatCodes.MWK) }, // Malawi Kwacha 
            { Iso3FiatCodes.MXN, new CurrencyFiatCode(Iso3FiatCodes.MXN) }, // Mexican Peso 
            { Iso3FiatCodes.MYR, new CurrencyFiatCode(Iso3FiatCodes.MYR) }, // Malaysian Ringgit 
            { Iso3FiatCodes.MZM, new CurrencyFiatCode(Iso3FiatCodes.MZM) }, // Mozambican Metical
            { Iso3FiatCodes.NAD, new CurrencyFiatCode(Iso3FiatCodes.NAD) }, // Namibian Dollar 
            { Iso3FiatCodes.NGN, new CurrencyFiatCode(Iso3FiatCodes.NGN) }, // Nigerian Naira 
            { Iso3FiatCodes.NIO, new CurrencyFiatCode(Iso3FiatCodes.NIO) }, // Nicaragua Cordoba 
            { Iso3FiatCodes.NOK, new CurrencyFiatCode(Iso3FiatCodes.NOK) }, // Norwegian Krone 
            { Iso3FiatCodes.NPR, new CurrencyFiatCode(Iso3FiatCodes.NPR) }, // Nepalese Rupee 
            { Iso3FiatCodes.NZD, new CurrencyFiatCode(Iso3FiatCodes.NZD) }, // New Zealand Dollar 
            { Iso3FiatCodes.OMR, new CurrencyFiatCode(Iso3FiatCodes.OMR) }, // Omani Rial 
            { Iso3FiatCodes.PAB, new CurrencyFiatCode(Iso3FiatCodes.PAB) }, // Panama Balboa 
            { Iso3FiatCodes.PEN, new CurrencyFiatCode(Iso3FiatCodes.PEN) }, // Peruvian Nuevo Sol 
            { Iso3FiatCodes.PGK, new CurrencyFiatCode(Iso3FiatCodes.PGK) }, // Papua New Guinea Kina 
            { Iso3FiatCodes.PHP, new CurrencyFiatCode(Iso3FiatCodes.PHP) }, // Philippine Peso 
            { Iso3FiatCodes.PKR, new CurrencyFiatCode(Iso3FiatCodes.PKR) }, // Pakistani Rupee 
            { Iso3FiatCodes.PLN, new CurrencyFiatCode(Iso3FiatCodes.PLN) }, // Polish Zloty 
            { Iso3FiatCodes.PYG, new CurrencyFiatCode(Iso3FiatCodes.PYG) }, // Paraguayan Guarani 
            { Iso3FiatCodes.QAR, new CurrencyFiatCode(Iso3FiatCodes.QAR) }, // Qatar Rial 
            { Iso3FiatCodes.RON, new CurrencyFiatCode(Iso3FiatCodes.RON) }, // Romanian New Leu 
            { Iso3FiatCodes.RSD, new CurrencyFiatCode(Iso3FiatCodes.RSD) }, // Serbian Dinar
            { Iso3FiatCodes.RUB, new CurrencyFiatCode(Iso3FiatCodes.RUB) }, // Russian Rouble 
            { Iso3FiatCodes.RWF, new CurrencyFiatCode(Iso3FiatCodes.RWF) }, // Rwanda Franc 
            { Iso3FiatCodes.SAR, new CurrencyFiatCode(Iso3FiatCodes.SAR) }, // Saudi Arabian Riyal 
            { Iso3FiatCodes.SBD, new CurrencyFiatCode(Iso3FiatCodes.SBD) }, // Solomon Islands Dollar
            { Iso3FiatCodes.SCR, new CurrencyFiatCode(Iso3FiatCodes.SCR) }, // Seychelles Rupee 
            { Iso3FiatCodes.SEK, new CurrencyFiatCode(Iso3FiatCodes.SEK) }, // Swedish Krona 
            { Iso3FiatCodes.SDG, new CurrencyFiatCode(Iso3FiatCodes.SDG) }, // Sudanese Pound
            { Iso3FiatCodes.SGD, new CurrencyFiatCode(Iso3FiatCodes.SGD) }, // Singapore Dollar 
            { Iso3FiatCodes.SHP, new CurrencyFiatCode(Iso3FiatCodes.SHP) }, // St Helena Pound 
            { Iso3FiatCodes.SIT, new CurrencyFiatCode(Iso3FiatCodes.SIT) }, // Slovenian Tolar 
            { Iso3FiatCodes.SLL, new CurrencyFiatCode(Iso3FiatCodes.SLL) }, // Sierra Leone Leone 
            { Iso3FiatCodes.SOS, new CurrencyFiatCode(Iso3FiatCodes.SOS) }, // Somali Shilling 
            { Iso3FiatCodes.SRG, new CurrencyFiatCode(Iso3FiatCodes.SRG) }, // Surinamese Guilder 
            { Iso3FiatCodes.SSP, new CurrencyFiatCode(Iso3FiatCodes.SSP) }, // South Sudanese Pound
            { Iso3FiatCodes.STD, new CurrencyFiatCode(Iso3FiatCodes.STD) }, // Sao Tome Dobra 
            { Iso3FiatCodes.SYP, new CurrencyFiatCode(Iso3FiatCodes.SYP) }, // Syrian Pound 
            { Iso3FiatCodes.SZL, new CurrencyFiatCode(Iso3FiatCodes.SZL) }, // Swaziland Lilageni 
            { Iso3FiatCodes.THB, new CurrencyFiatCode(Iso3FiatCodes.THB) }, // Thai Baht 
            { Iso3FiatCodes.TJS, new CurrencyFiatCode(Iso3FiatCodes.TJS) }, // Tajikistani Somoni
            { Iso3FiatCodes.TMM, new CurrencyFiatCode(Iso3FiatCodes.TMM) }, // Turkmenistani Manat
            { Iso3FiatCodes.TND, new CurrencyFiatCode(Iso3FiatCodes.TND) }, // Tunisian Dinar 
            { Iso3FiatCodes.TOP, new CurrencyFiatCode(Iso3FiatCodes.TOP) }, // Tonga Paanga 
            { Iso3FiatCodes.TRY, new CurrencyFiatCode(Iso3FiatCodes.TRY) }, // Turkish Lira 
            { Iso3FiatCodes.TTD, new CurrencyFiatCode(Iso3FiatCodes.TTD) }, // Trinidad&Tobago Dollar 
            { Iso3FiatCodes.TWD, new CurrencyFiatCode(Iso3FiatCodes.TWD) }, // Taiwan Dollar 
            { Iso3FiatCodes.TZS, new CurrencyFiatCode(Iso3FiatCodes.TZS) }, // Tanzanian Shilling 
            { Iso3FiatCodes.UAH, new CurrencyFiatCode(Iso3FiatCodes.UAH) }, // Ukraine Hryvnia 
            { Iso3FiatCodes.UGX, new CurrencyFiatCode(Iso3FiatCodes.UGX) }, // Ugandan Shilling 
            { Iso3FiatCodes.USD, new CurrencyFiatCode(Iso3FiatCodes.USD) }, // U.S. Dollar 
            { Iso3FiatCodes.UYU, new CurrencyFiatCode(Iso3FiatCodes.UYU) }, // Uruguayan New Peso 
            { Iso3FiatCodes.UZS, new CurrencyFiatCode(Iso3FiatCodes.UZS) }, // Uzbekistani Soʻm
            { Iso3FiatCodes.VES, new CurrencyFiatCode(Iso3FiatCodes.VES) }, // Venezuelan Bolívar
            { Iso3FiatCodes.VND, new CurrencyFiatCode(Iso3FiatCodes.VND) }, // Vietnam Dong 
            { Iso3FiatCodes.VUV, new CurrencyFiatCode(Iso3FiatCodes.VUV) }, // Vanuatu Vatu 
            { Iso3FiatCodes.WST, new CurrencyFiatCode(Iso3FiatCodes.WST) }, // Samoa Tala 
            { Iso3FiatCodes.XAF, new CurrencyFiatCode(Iso3FiatCodes.XAF) }, // CFA Franc (BEAC) 
            { Iso3FiatCodes.XAU, new CurrencyFiatCode(Iso3FiatCodes.XAU) }, // Gold Ounces 
            { Iso3FiatCodes.XCD, new CurrencyFiatCode(Iso3FiatCodes.XCD) }, // East Caribbean Dollar 
            { Iso3FiatCodes.XOF, new CurrencyFiatCode(Iso3FiatCodes.XOF) }, // CFA Franc (BCEAO) 
            { Iso3FiatCodes.XPF, new CurrencyFiatCode(Iso3FiatCodes.XPF) }, // Pacific Franc 
            { Iso3FiatCodes.YER, new CurrencyFiatCode(Iso3FiatCodes.YER) }, // Yemen Riyal 
            { Iso3FiatCodes.ZAR, new CurrencyFiatCode(Iso3FiatCodes.ZAR) }, // South African Rand 
            { Iso3FiatCodes.ZMW, new CurrencyFiatCode(Iso3FiatCodes.ZMW) }, // Zambian Kwacha 
            { Iso3FiatCodes.ZWD, new CurrencyFiatCode(Iso3FiatCodes.ZWD) }, // Zimbabwean Dollar
            #endregion
        };
        #endregion

        /// <summary>
        /// Create GdCurrencyFiatCode from string value (case insensitive)
        /// </summary>
        /// <param name="code"></param>
        /// <returns></returns>
        public static CurrencyFiatCode FromString(string code)
        {
            if (string.IsNullOrEmpty(code))
                throw new InvalidCurrencyCodeException(code);


            code = code.Trim().ToUpper();
            if (Codes.TryGetValue(code, out CurrencyFiatCode gdCurrencyFiatCode))
                return gdCurrencyFiatCode;

            throw new InvalidCurrencyCodeException(code);   
        }

        #region List
        /*
        SELECT CONCAT('/// <summary>', CHARACTER(13),
              '/// ',REGEXP_REPLACE(cur.name, '\\([A-Z]{3}\\)',''), CHARACTER(13),
              '/// </summary>', CHARACTER(13),
              'public static CurrencyFiatCode ', REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(cur.name,'.',''), '&', '_And_'), ',', '') , ' ', '_') , '(', '') , ')', '') , '-', '_'), ' => new CurrencyFiatCode(Iso3FiatCodes.',`code`,');', CHARACTER(13), CHARACTER(13))
        FROM gd_currencies cur
        ORDER BY `code`		  		 
        */
        #endregion
        /// <summary>
        /// Abkhazian Apsar
        /// </summary>
        public static CurrencyFiatCode Abkhazian_Apsar => new CurrencyFiatCode(Iso3FiatCodes.ABK);

        /// <summary>
        /// UAE Dirham 
        /// </summary>
        public static CurrencyFiatCode UAE_Dirham_AED => new CurrencyFiatCode(Iso3FiatCodes.AED);

        /// <summary>
        /// Afghanistan Afghani
        /// </summary>
        public static CurrencyFiatCode Afghanistan_Afghani => new CurrencyFiatCode(Iso3FiatCodes.AFN);

        /// <summary>
        /// Albanian Lek 
        /// </summary>
        public static CurrencyFiatCode Albanian_Lek_ALL => new CurrencyFiatCode(Iso3FiatCodes.ALL);

        /// <summary>
        /// Armenian dram
        /// </summary>
        public static CurrencyFiatCode Armenian_dram => new CurrencyFiatCode(Iso3FiatCodes.AMD);

        /// <summary>
        /// Neth Antilles Guilder 
        /// </summary>
        public static CurrencyFiatCode Neth_Antilles_Guilder_ANG => new CurrencyFiatCode(Iso3FiatCodes.ANG);

        /// <summary>
        /// Angolan kwanza
        /// </summary>
        public static CurrencyFiatCode Angolan_kwanza => new CurrencyFiatCode(Iso3FiatCodes.AOA);

        /// <summary>
        /// Argentine Peso 
        /// </summary>
        public static CurrencyFiatCode Argentine_Peso_ARS => new CurrencyFiatCode(Iso3FiatCodes.ARS);

        /// <summary>
        /// Australian Dollar 
        /// </summary>
        public static CurrencyFiatCode Australian_Dollar_AUD => new CurrencyFiatCode(Iso3FiatCodes.AUD);

        /// <summary>
        /// Aruba Florin 
        /// </summary>
        public static CurrencyFiatCode Aruba_Florin_AWG => new CurrencyFiatCode(Iso3FiatCodes.AWG);

        /// <summary>
        /// Azerbaijani Manat
        /// </summary>
        public static CurrencyFiatCode Azerbaijani_Manat => new CurrencyFiatCode(Iso3FiatCodes.AZN);

        /// <summary>
        /// Bosnia and Herzegovina Convert
        /// </summary>
        public static CurrencyFiatCode Bosnia_and_Herzegovina_Convert => new CurrencyFiatCode(Iso3FiatCodes.BAM);

        /// <summary>
        /// Barbados Dollar 
        /// </summary>
        public static CurrencyFiatCode Barbados_Dollar_BBD => new CurrencyFiatCode(Iso3FiatCodes.BBD);

        /// <summary>
        /// Bangladesh Taka 
        /// </summary>
        public static CurrencyFiatCode Bangladesh_Taka_BDT => new CurrencyFiatCode(Iso3FiatCodes.BDT);

        /// <summary>
        /// Bulgarian Lev 
        /// </summary>
        public static CurrencyFiatCode Bulgarian_Lev_BGN => new CurrencyFiatCode(Iso3FiatCodes.BGN);

        /// <summary>
        /// Bahraini Dinar 
        /// </summary>
        public static CurrencyFiatCode Bahraini_Dinar_BHD => new CurrencyFiatCode(Iso3FiatCodes.BHD);

        /// <summary>
        /// Burundi Franc 
        /// </summary>
        public static CurrencyFiatCode Burundi_Franc_BIF => new CurrencyFiatCode(Iso3FiatCodes.BIF);

        /// <summary>
        /// Bermuda Dollar 
        /// </summary>
        public static CurrencyFiatCode Bermuda_Dollar_BMD => new CurrencyFiatCode(Iso3FiatCodes.BMD);

        /// <summary>
        /// Brunei Dollar 
        /// </summary>
        public static CurrencyFiatCode Brunei_Dollar_BND => new CurrencyFiatCode(Iso3FiatCodes.BND);

        /// <summary>
        /// Bolivian Boliviano 
        /// </summary>
        public static CurrencyFiatCode Bolivian_Boliviano_BOB => new CurrencyFiatCode(Iso3FiatCodes.BOB);

        /// <summary>
        /// Brazilian Real 
        /// </summary>
        public static CurrencyFiatCode Brazilian_Real_BRL => new CurrencyFiatCode(Iso3FiatCodes.BRL);

        /// <summary>
        /// Bahamian Dollar 
        /// </summary>
        public static CurrencyFiatCode Bahamian_Dollar_BSD => new CurrencyFiatCode(Iso3FiatCodes.BSD);

        /// <summary>
        /// Bhutan Ngultrum 
        /// </summary>
        public static CurrencyFiatCode Bhutan_Ngultrum_BTN => new CurrencyFiatCode(Iso3FiatCodes.BTN);

        /// <summary>
        /// Botswana Pula
        /// </summary>
        public static CurrencyFiatCode Botswana_Pula => new CurrencyFiatCode(Iso3FiatCodes.BWP);

        /// <summary>
        /// Belarus Ruble 
        /// </summary>
        public static CurrencyFiatCode Belarus_Ruble_BYR => new CurrencyFiatCode(Iso3FiatCodes.BYR);

        /// <summary>
        /// Belize Dollar 
        /// </summary>
        public static CurrencyFiatCode Belize_Dollar_BZD => new CurrencyFiatCode(Iso3FiatCodes.BZD);

        /// <summary>
        /// Canadian Dollar 
        /// </summary>
        public static CurrencyFiatCode Canadian_Dollar_CAD => new CurrencyFiatCode(Iso3FiatCodes.CAD);

        /// <summary>
        /// Swiss Franc 
        /// </summary>
        public static CurrencyFiatCode Swiss_Franc_CHF => new CurrencyFiatCode(Iso3FiatCodes.CHF);

        /// <summary>
        /// Chilean Peso 
        /// </summary>
        public static CurrencyFiatCode Chilean_Peso_CLP => new CurrencyFiatCode(Iso3FiatCodes.CLP);

        /// <summary>
        /// Chinese Yuan 
        /// </summary>
        public static CurrencyFiatCode Chinese_Yuan_CNY => new CurrencyFiatCode(Iso3FiatCodes.CNY);

        /// <summary>
        /// Colombian Peso 
        /// </summary>
        public static CurrencyFiatCode Colombian_Peso_COP => new CurrencyFiatCode(Iso3FiatCodes.COP);

        /// <summary>
        /// Costa Rica Colon 
        /// </summary>
        public static CurrencyFiatCode Costa_Rica_Colon_CRC => new CurrencyFiatCode(Iso3FiatCodes.CRC);

        /// <summary>
        /// Cuban Peso 
        /// </summary>
        public static CurrencyFiatCode Cuban_Peso_CUP => new CurrencyFiatCode(Iso3FiatCodes.CUP);

        /// <summary>
        /// Cape Verde Escudo
        /// </summary>
        public static CurrencyFiatCode Cape_Verde_Escudo => new CurrencyFiatCode(Iso3FiatCodes.CVE);

        /// <summary>
        /// Czech Koruna 
        /// </summary>
        public static CurrencyFiatCode Czech_Koruna_CZK => new CurrencyFiatCode(Iso3FiatCodes.CZK);

        /// <summary>
        /// Dijibouti Franc 
        /// </summary>
        public static CurrencyFiatCode Dijibouti_Franc_DJF => new CurrencyFiatCode(Iso3FiatCodes.DJF);

        /// <summary>
        /// Danish Krone 
        /// </summary>
        public static CurrencyFiatCode Danish_Krone_DKK => new CurrencyFiatCode(Iso3FiatCodes.DKK);

        /// <summary>
        /// Dominican Peso 
        /// </summary>
        public static CurrencyFiatCode Dominican_Peso_DOP => new CurrencyFiatCode(Iso3FiatCodes.DOP);

        /// <summary>
        /// Algerian Dinar 
        /// </summary>
        public static CurrencyFiatCode Algerian_Dinar_DZD => new CurrencyFiatCode(Iso3FiatCodes.DZD);

        /// <summary>
        /// Egyptian Pound 
        /// </summary>
        public static CurrencyFiatCode Egyptian_Pound_EGP => new CurrencyFiatCode(Iso3FiatCodes.EGP);

        /// <summary>
        /// Eritrean Nakfa
        /// </summary>
        public static CurrencyFiatCode Eritrean_Nakfa => new CurrencyFiatCode(Iso3FiatCodes.ERN);

        /// <summary>
        /// Ethiopian Birr 
        /// </summary>
        public static CurrencyFiatCode Ethiopian_Birr_ETB => new CurrencyFiatCode(Iso3FiatCodes.ETB);

        /// <summary>
        /// Euro 
        /// </summary>
        public static CurrencyFiatCode Euro_EUR => new CurrencyFiatCode(Iso3FiatCodes.EUR);

        /// <summary>
        /// Fijian Dollar
        /// </summary>
        public static CurrencyFiatCode Fijian_Dollar => new CurrencyFiatCode(Iso3FiatCodes.FJD);

        /// <summary>
        /// Falkland Islands Pound 
        /// </summary>
        public static CurrencyFiatCode Falkland_Islands_Pound_FKP => new CurrencyFiatCode(Iso3FiatCodes.FKP);

        /// <summary>
        /// British Pound 
        /// </summary>
        public static CurrencyFiatCode British_Pound_GBP => new CurrencyFiatCode(Iso3FiatCodes.GBP);

        /// <summary>
        /// Georgian Lari 
        /// </summary>
        public static CurrencyFiatCode Georgian_Lari_GEL => new CurrencyFiatCode(Iso3FiatCodes.GEL);

        /// <summary>
        /// Ghanaian cedi
        /// </summary>
        public static CurrencyFiatCode Ghanaian_cedi => new CurrencyFiatCode(Iso3FiatCodes.GHS);

        /// <summary>
        /// Gibraltar Pound 
        /// </summary>
        public static CurrencyFiatCode Gibraltar_Pound_GIP => new CurrencyFiatCode(Iso3FiatCodes.GIP);

        /// <summary>
        /// Gambian Dalasi 
        /// </summary>
        public static CurrencyFiatCode Gambian_Dalasi_GMD => new CurrencyFiatCode(Iso3FiatCodes.GMD);

        /// <summary>
        /// Guinea Franc 
        /// </summary>
        public static CurrencyFiatCode Guinea_Franc_GNF => new CurrencyFiatCode(Iso3FiatCodes.GNF);

        /// <summary>
        /// Guatemala Quetzal 
        /// </summary>
        public static CurrencyFiatCode Guatemala_Quetzal_GTQ => new CurrencyFiatCode(Iso3FiatCodes.GTQ);

        /// <summary>
        /// Guinea-Bissau Peso
        /// </summary>
        public static CurrencyFiatCode Guinea_Bissau_Peso => new CurrencyFiatCode(Iso3FiatCodes.GWP);

        /// <summary>
        /// Guyana Dollar 
        /// </summary>
        public static CurrencyFiatCode Guyana_Dollar_GYD => new CurrencyFiatCode(Iso3FiatCodes.GYD);

        /// <summary>
        /// Hong Kong Dollar 
        /// </summary>
        public static CurrencyFiatCode Hong_Kong_Dollar_HKD => new CurrencyFiatCode(Iso3FiatCodes.HKD);

        /// <summary>
        /// Honduras Lempira 
        /// </summary>
        public static CurrencyFiatCode Honduras_Lempira_HNL => new CurrencyFiatCode(Iso3FiatCodes.HNL);

        /// <summary>
        /// Croatian Kuna 
        /// </summary>
        public static CurrencyFiatCode Croatian_Kuna_HRK => new CurrencyFiatCode(Iso3FiatCodes.HRK);

        /// <summary>
        /// Haiti Gourde 
        /// </summary>
        public static CurrencyFiatCode Haiti_Gourde_HTG => new CurrencyFiatCode(Iso3FiatCodes.HTG);

        /// <summary>
        /// Hungarian ForINT 
        /// </summary>
        public static CurrencyFiatCode Hungarian_ForINT_HUF => new CurrencyFiatCode(Iso3FiatCodes.HUF);

        /// <summary>
        /// Indonesian Rupiah 
        /// </summary>
        public static CurrencyFiatCode Indonesian_Rupiah_IDR => new CurrencyFiatCode(Iso3FiatCodes.IDR);

        /// <summary>
        /// Israeli Shekel 
        /// </summary>
        public static CurrencyFiatCode Israeli_Shekel_ILS => new CurrencyFiatCode(Iso3FiatCodes.ILS);

        /// <summary>
        /// Indian Rupee 
        /// </summary>
        public static CurrencyFiatCode Indian_Rupee_INR => new CurrencyFiatCode(Iso3FiatCodes.INR);

        /// <summary>
        /// Iraqi Dinar
        /// </summary>
        public static CurrencyFiatCode Iraqi_Dinar => new CurrencyFiatCode(Iso3FiatCodes.IQD);

        /// <summary>
        /// Iran Rial 
        /// </summary>
        public static CurrencyFiatCode Iran_Rial_IRR => new CurrencyFiatCode(Iso3FiatCodes.IRR);

        /// <summary>
        /// Iceland Krona 
        /// </summary>
        public static CurrencyFiatCode Iceland_Krona_ISK => new CurrencyFiatCode(Iso3FiatCodes.ISK);

        /// <summary>
        /// Jamaican Dollar 
        /// </summary>
        public static CurrencyFiatCode Jamaican_Dollar_JMD => new CurrencyFiatCode(Iso3FiatCodes.JMD);

        /// <summary>
        /// Jordanian Dinar 
        /// </summary>
        public static CurrencyFiatCode Jordanian_Dinar_JOD => new CurrencyFiatCode(Iso3FiatCodes.JOD);

        /// <summary>
        /// Japanese Yen 
        /// </summary>
        public static CurrencyFiatCode Japanese_Yen_JPY => new CurrencyFiatCode(Iso3FiatCodes.JPY);

        /// <summary>
        /// Kenyan Shilling 
        /// </summary>
        public static CurrencyFiatCode Kenyan_Shilling_KES => new CurrencyFiatCode(Iso3FiatCodes.KES);

        /// <summary>
        /// Cambodia Riel 
        /// </summary>
        public static CurrencyFiatCode Cambodia_Riel_KHR => new CurrencyFiatCode(Iso3FiatCodes.KHR);

        /// <summary>
        /// Comoros Franc 
        /// </summary>
        public static CurrencyFiatCode Comoros_Franc_KMF => new CurrencyFiatCode(Iso3FiatCodes.KMF);

        /// <summary>
        /// Korean Won 
        /// </summary>
        public static CurrencyFiatCode Korean_Won_KRW => new CurrencyFiatCode(Iso3FiatCodes.KRW);

        /// <summary>
        /// Kuwaiti Dinar 
        /// </summary>
        public static CurrencyFiatCode Kuwaiti_Dinar_KWD => new CurrencyFiatCode(Iso3FiatCodes.KWD);

        /// <summary>
        /// Cayman Islands Dollar 
        /// </summary>
        public static CurrencyFiatCode Cayman_Islands_Dollar_KYD => new CurrencyFiatCode(Iso3FiatCodes.KYD);

        /// <summary>
        /// Kazakhstan Tenge 
        /// </summary>
        public static CurrencyFiatCode Kazakhstan_Tenge_KZT => new CurrencyFiatCode(Iso3FiatCodes.KZT);

        /// <summary>
        /// Lao Kip 
        /// </summary>
        public static CurrencyFiatCode Lao_Kip_LAK => new CurrencyFiatCode(Iso3FiatCodes.LAK);

        /// <summary>
        /// Lebanese Pound 
        /// </summary>
        public static CurrencyFiatCode Lebanese_Pound_LBP => new CurrencyFiatCode(Iso3FiatCodes.LBP);

        /// <summary>
        /// Sri Lanka Rupee 
        /// </summary>
        public static CurrencyFiatCode Sri_Lanka_Rupee_LKR => new CurrencyFiatCode(Iso3FiatCodes.LKR);

        /// <summary>
        /// Liberian Dollar
        /// </summary>
        public static CurrencyFiatCode Liberian_Dollar => new CurrencyFiatCode(Iso3FiatCodes.LRD);

        /// <summary>
        /// Lesotho Loti 
        /// </summary>
        public static CurrencyFiatCode Lesotho_Loti_LSL => new CurrencyFiatCode(Iso3FiatCodes.LSL);

        /// <summary>
        /// Lithuanian Lita 
        /// </summary>
        public static CurrencyFiatCode Lithuanian_Lita_LTL => new CurrencyFiatCode(Iso3FiatCodes.LTL);

        /// <summary>
        /// Latvian Lat 
        /// </summary>
        public static CurrencyFiatCode Latvian_Lat_LVL => new CurrencyFiatCode(Iso3FiatCodes.LVL);

        /// <summary>
        /// Libyan Dinar 
        /// </summary>
        public static CurrencyFiatCode Libyan_Dinar_LYD => new CurrencyFiatCode(Iso3FiatCodes.LYD);

        /// <summary>
        /// Moroccan Dirham 
        /// </summary>
        public static CurrencyFiatCode Moroccan_Dirham_MAD => new CurrencyFiatCode(Iso3FiatCodes.MAD);

        /// <summary>
        /// Moldovan Leu 
        /// </summary>
        public static CurrencyFiatCode Moldovan_Leu_MDL => new CurrencyFiatCode(Iso3FiatCodes.MDL);

        /// <summary>
        /// Malagasy Franc
        /// </summary>
        public static CurrencyFiatCode Malagasy_Franc => new CurrencyFiatCode(Iso3FiatCodes.MGF);

        /// <summary>
        /// Macedonian Denar 
        /// </summary>
        public static CurrencyFiatCode Macedonian_Denar_MKD => new CurrencyFiatCode(Iso3FiatCodes.MKD);

        /// <summary>
        /// Myanmar Kyat
        /// </summary>
        public static CurrencyFiatCode Myanmar_Kyat => new CurrencyFiatCode(Iso3FiatCodes.MMK);

        /// <summary>
        /// Mongolian Tugrik 
        /// </summary>
        public static CurrencyFiatCode Mongolian_Tugrik_MNT => new CurrencyFiatCode(Iso3FiatCodes.MNT);

        /// <summary>
        /// Macau Pataca 
        /// </summary>
        public static CurrencyFiatCode Macau_Pataca_MOP => new CurrencyFiatCode(Iso3FiatCodes.MOP);

        /// <summary>
        /// Mauritania Ougulya 
        /// </summary>
        public static CurrencyFiatCode Mauritania_Ougulya_MRO => new CurrencyFiatCode(Iso3FiatCodes.MRO);

        /// <summary>
        /// Mauritius Rupee 
        /// </summary>
        public static CurrencyFiatCode Mauritius_Rupee_MUR => new CurrencyFiatCode(Iso3FiatCodes.MUR);

        /// <summary>
        /// Maldives Rufiyaa 
        /// </summary>
        public static CurrencyFiatCode Maldives_Rufiyaa_MVR => new CurrencyFiatCode(Iso3FiatCodes.MVR);

        /// <summary>
        /// Malawi Kwacha 
        /// </summary>
        public static CurrencyFiatCode Malawi_Kwacha_MWK => new CurrencyFiatCode(Iso3FiatCodes.MWK);

        /// <summary>
        /// Mexican Peso 
        /// </summary>
        public static CurrencyFiatCode Mexican_Peso_MXN => new CurrencyFiatCode(Iso3FiatCodes.MXN);

        /// <summary>
        /// Malaysian Ringgit 
        /// </summary>
        public static CurrencyFiatCode Malaysian_Ringgit_MYR => new CurrencyFiatCode(Iso3FiatCodes.MYR);

        /// <summary>
        /// Namibian Dollar 
        /// </summary>
        public static CurrencyFiatCode Namibian_Dollar_NAD => new CurrencyFiatCode(Iso3FiatCodes.NAD);

        /// <summary>
        /// Nigerian Naira 
        /// </summary>
        public static CurrencyFiatCode Nigerian_Naira_NGN => new CurrencyFiatCode(Iso3FiatCodes.NGN);

        /// <summary>
        /// Nicaragua Cordoba 
        /// </summary>
        public static CurrencyFiatCode Nicaragua_Cordoba_NIO => new CurrencyFiatCode(Iso3FiatCodes.NIO);

        /// <summary>
        /// Norwegian Krone 
        /// </summary>
        public static CurrencyFiatCode Norwegian_Krone_NOK => new CurrencyFiatCode(Iso3FiatCodes.NOK);

        /// <summary>
        /// Nepalese Rupee 
        /// </summary>
        public static CurrencyFiatCode Nepalese_Rupee_NPR => new CurrencyFiatCode(Iso3FiatCodes.NPR);

        /// <summary>
        /// New Zealand Dollar 
        /// </summary>
        public static CurrencyFiatCode New_Zealand_Dollar_NZD => new CurrencyFiatCode(Iso3FiatCodes.NZD);

        /// <summary>
        /// Omani Rial 
        /// </summary>
        public static CurrencyFiatCode Omani_Rial_OMR => new CurrencyFiatCode(Iso3FiatCodes.OMR);

        /// <summary>
        /// Panama Balboa 
        /// </summary>
        public static CurrencyFiatCode Panama_Balboa_PAB => new CurrencyFiatCode(Iso3FiatCodes.PAB);

        /// <summary>
        /// Peruvian Nuevo Sol 
        /// </summary>
        public static CurrencyFiatCode Peruvian_Nuevo_Sol_PEN => new CurrencyFiatCode(Iso3FiatCodes.PEN);

        /// <summary>
        /// Papua New Guinea Kina 
        /// </summary>
        public static CurrencyFiatCode Papua_New_Guinea_Kina_PGK => new CurrencyFiatCode(Iso3FiatCodes.PGK);

        /// <summary>
        /// Philippine Peso 
        /// </summary>
        public static CurrencyFiatCode Philippine_Peso_PHP => new CurrencyFiatCode(Iso3FiatCodes.PHP);

        /// <summary>
        /// Pakistani Rupee 
        /// </summary>
        public static CurrencyFiatCode Pakistani_Rupee_PKR => new CurrencyFiatCode(Iso3FiatCodes.PKR);

        /// <summary>
        /// Polish Zloty 
        /// </summary>
        public static CurrencyFiatCode Polish_Zloty_PLN => new CurrencyFiatCode(Iso3FiatCodes.PLN);

        /// <summary>
        /// Paraguayan Guarani 
        /// </summary>
        public static CurrencyFiatCode Paraguayan_Guarani_PYG => new CurrencyFiatCode(Iso3FiatCodes.PYG);

        /// <summary>
        /// Qatar Rial 
        /// </summary>
        public static CurrencyFiatCode Qatar_Rial_QAR => new CurrencyFiatCode(Iso3FiatCodes.QAR);

        /// <summary>
        /// Romanian New Leu 
        /// </summary>
        public static CurrencyFiatCode Romanian_New_Leu_RON => new CurrencyFiatCode(Iso3FiatCodes.RON);

        /// <summary>
        /// Serbian Dinar
        /// </summary>
        public static CurrencyFiatCode Serbian_Dinar => new CurrencyFiatCode(Iso3FiatCodes.RSD);

        /// <summary>
        /// Russian Rouble 
        /// </summary>
        public static CurrencyFiatCode Russian_Rouble_RUB => new CurrencyFiatCode(Iso3FiatCodes.RUB);

        /// <summary>
        /// Rwanda Franc 
        /// </summary>
        public static CurrencyFiatCode Rwanda_Franc_RWF => new CurrencyFiatCode(Iso3FiatCodes.RWF);

        /// <summary>
        /// Saudi Arabian Riyal 
        /// </summary>
        public static CurrencyFiatCode Saudi_Arabian_Riyal_SAR => new CurrencyFiatCode(Iso3FiatCodes.SAR);

        /// <summary>
        /// Seychelles Rupee 
        /// </summary>
        public static CurrencyFiatCode Seychelles_Rupee_SCR => new CurrencyFiatCode(Iso3FiatCodes.SCR);

        /// <summary>
        /// Sudanese Pound
        /// </summary>
        public static CurrencyFiatCode Sudanese_Pound => new CurrencyFiatCode(Iso3FiatCodes.SDG);

        /// <summary>
        /// Swedish Krona 
        /// </summary>
        public static CurrencyFiatCode Swedish_Krona_SEK => new CurrencyFiatCode(Iso3FiatCodes.SEK);

        /// <summary>
        /// Singapore Dollar 
        /// </summary>
        public static CurrencyFiatCode Singapore_Dollar_SGD => new CurrencyFiatCode(Iso3FiatCodes.SGD);

        /// <summary>
        /// St Helena Pound 
        /// </summary>
        public static CurrencyFiatCode St_Helena_Pound_SHP => new CurrencyFiatCode(Iso3FiatCodes.SHP);

        /// <summary>
        /// Slovenian Tolar 
        /// </summary>
        public static CurrencyFiatCode Slovenian_Tolar_SIT => new CurrencyFiatCode(Iso3FiatCodes.SIT);

        /// <summary>
        /// Sierra Leone Leone 
        /// </summary>
        public static CurrencyFiatCode Sierra_Leone_Leone_SLL => new CurrencyFiatCode(Iso3FiatCodes.SLL);

        /// <summary>
        /// Somali Shilling 
        /// </summary>
        public static CurrencyFiatCode Somali_Shilling_SOS => new CurrencyFiatCode(Iso3FiatCodes.SOS);

        /// <summary>
        /// Sao Tome Dobra 
        /// </summary>
        public static CurrencyFiatCode Sao_Tome_Dobra_STD => new CurrencyFiatCode(Iso3FiatCodes.STD);

        /// <summary>
        /// Syrian Pound 
        /// </summary>
        public static CurrencyFiatCode Syrian_Pound_SYP => new CurrencyFiatCode(Iso3FiatCodes.SYP);

        /// <summary>
        /// Swaziland Lilageni 
        /// </summary>
        public static CurrencyFiatCode Swaziland_Lilageni_SZL => new CurrencyFiatCode(Iso3FiatCodes.SZL);

        /// <summary>
        /// Thai Baht 
        /// </summary>
        public static CurrencyFiatCode Thai_Baht_THB => new CurrencyFiatCode(Iso3FiatCodes.THB);

        /// <summary>
        /// Tunisian Dinar 
        /// </summary>
        public static CurrencyFiatCode Tunisian_Dinar_TND => new CurrencyFiatCode(Iso3FiatCodes.TND);

        /// <summary>
        /// Tonga Paanga 
        /// </summary>
        public static CurrencyFiatCode Tonga_Paanga_TOP => new CurrencyFiatCode(Iso3FiatCodes.TOP);

        /// <summary>
        /// Turkish Lira 
        /// </summary>
        public static CurrencyFiatCode Turkish_Lira_TRY => new CurrencyFiatCode(Iso3FiatCodes.TRY);

        /// <summary>
        /// Trinidad&Tobago Dollar 
        /// </summary>
        public static CurrencyFiatCode Trinidad_And_Tobago_Dollar_TTD => new CurrencyFiatCode(Iso3FiatCodes.TTD);

        /// <summary>
        /// Taiwan Dollar 
        /// </summary>
        public static CurrencyFiatCode Taiwan_Dollar_TWD => new CurrencyFiatCode(Iso3FiatCodes.TWD);

        /// <summary>
        /// Tanzanian Shilling 
        /// </summary>
        public static CurrencyFiatCode Tanzanian_Shilling_TZS => new CurrencyFiatCode(Iso3FiatCodes.TZS);

        /// <summary>
        /// Ukraine Hryvnia 
        /// </summary>
        public static CurrencyFiatCode Ukraine_Hryvnia_UAH => new CurrencyFiatCode(Iso3FiatCodes.UAH);

        /// <summary>
        /// Ugandan Shilling 
        /// </summary>
        public static CurrencyFiatCode Ugandan_Shilling_UGX => new CurrencyFiatCode(Iso3FiatCodes.UGX);

        /// <summary>
        /// U.S. Dollar 
        /// </summary>
        public static CurrencyFiatCode US_Dollar_USD => new CurrencyFiatCode(Iso3FiatCodes.USD);

        /// <summary>
        /// Uruguayan New Peso 
        /// </summary>
        public static CurrencyFiatCode Uruguayan_New_Peso_UYU => new CurrencyFiatCode(Iso3FiatCodes.UYU);

        /// <summary>
        /// Vietnam Dong 
        /// </summary>
        public static CurrencyFiatCode Vietnam_Dong_VND => new CurrencyFiatCode(Iso3FiatCodes.VND);

        /// <summary>
        /// Vanuatu Vatu 
        /// </summary>
        public static CurrencyFiatCode Vanuatu_Vatu_VUV => new CurrencyFiatCode(Iso3FiatCodes.VUV);

        /// <summary>
        /// Samoa Tala 
        /// </summary>
        public static CurrencyFiatCode Samoa_Tala_WST => new CurrencyFiatCode(Iso3FiatCodes.WST);

        /// <summary>
        /// CFA Franc (BEAC) 
        /// </summary>
        public static CurrencyFiatCode CFA_Franc_BEAC_XAF => new CurrencyFiatCode(Iso3FiatCodes.XAF);

        /// <summary>
        /// Gold Ounces 
        /// </summary>
        public static CurrencyFiatCode Gold_Ounces_XAU => new CurrencyFiatCode(Iso3FiatCodes.XAU);

        /// <summary>
        /// East Caribbean Dollar 
        /// </summary>
        public static CurrencyFiatCode East_Caribbean_Dollar_XCD => new CurrencyFiatCode(Iso3FiatCodes.XCD);

        /// <summary>
        /// CFA Franc (BCEAO) 
        /// </summary>
        public static CurrencyFiatCode CFA_Franc_BCEAO_XOF => new CurrencyFiatCode(Iso3FiatCodes.XOF);

        /// <summary>
        /// Pacific Franc 
        /// </summary>
        public static CurrencyFiatCode Pacific_Franc_XPF => new CurrencyFiatCode(Iso3FiatCodes.XPF);

        /// <summary>
        /// Yemen Riyal 
        /// </summary>
        public static CurrencyFiatCode Yemen_Riyal_YER => new CurrencyFiatCode(Iso3FiatCodes.YER);

        /// <summary>
        /// South African Rand 
        /// </summary>
        public static CurrencyFiatCode South_African_Rand_ZAR => new CurrencyFiatCode(Iso3FiatCodes.ZAR);

        /// <summary>
        /// Zambian Kwacha 
        /// </summary>
        public static CurrencyFiatCode Zambian_Kwacha_ZMK => new CurrencyFiatCode(Iso3FiatCodes.ZMW);

        /// <summary>
        /// Zimbabwean Dollar
        /// </summary>
        public static CurrencyFiatCode Zimbabwean_Dollar => new CurrencyFiatCode(Iso3FiatCodes.ZWD);
    }
}