using System.Collections.Generic;
using Azihub.GlobalData.Base.Currency.Exceptions;

namespace Azihub.GlobalData.Base.Currency
{
    public class CurrencyFiatCode
    {
        private CurrencyFiatCode(string code)
        {
            Code = code;
        }

        public string Code { get; }

        public override string ToString()
        {
            return Code;
        }

        public CurrencyFiat GetCurrencyFiat()
        {
            return CurrencyFiatList.Get(this);
        }

        #region Dictionary
        /// <summary>
        /// Hold all countries in private memory space
        /// </summary>
        private static Dictionary<string, CurrencyFiatCode> Codes { get; } = new Dictionary<string, CurrencyFiatCode>()
        {
            // Generated by SQL:
            /*
            SELECT
	            concat(
                    '{ Iso3FiatCodes.',`code`, 
                    ', new GdCurrencyFiatCode(Iso3FiatCodes.',`code`,') }, // ',
                    REGEXP_REPLACE(name, '\\([A-Z]{3}\\)','')
                ) 
                FROM gd_currencies 
            ORDER BY `code`
            */
            #region Sql Result
            { Iso3FiatCodes.ABK, new CurrencyFiatCode(Iso3FiatCodes.ABK) }, // Abkhazian Apsar
            { Iso3FiatCodes.AED, new CurrencyFiatCode(Iso3FiatCodes.AED) }, // UAE Dirham 
            { Iso3FiatCodes.AFN, new CurrencyFiatCode(Iso3FiatCodes.AFN) }, // Afghanistan Afghani
            { Iso3FiatCodes.ALL, new CurrencyFiatCode(Iso3FiatCodes.ALL) }, // Albanian Lek 
            { Iso3FiatCodes.AMD, new CurrencyFiatCode(Iso3FiatCodes.AMD) }, // Abkhazian apsar
            { Iso3FiatCodes.ANG, new CurrencyFiatCode(Iso3FiatCodes.ANG) }, // Neth Antilles Guilder 
            { Iso3FiatCodes.AOA, new CurrencyFiatCode(Iso3FiatCodes.AOA) }, // Angola Kwanza
            { Iso3FiatCodes.ARS, new CurrencyFiatCode(Iso3FiatCodes.ARS) }, // Argentine Peso 
            { Iso3FiatCodes.AUD, new CurrencyFiatCode(Iso3FiatCodes.AUD) }, // Australian Dollar 
            { Iso3FiatCodes.AWG, new CurrencyFiatCode(Iso3FiatCodes.AWG) }, // Aruba Florin 
            { Iso3FiatCodes.AZN, new CurrencyFiatCode(Iso3FiatCodes.AZN) }, // Azerbaijani Manat
            { Iso3FiatCodes.BAM, new CurrencyFiatCode(Iso3FiatCodes.BAM) }, // Barbados Dollar 
            { Iso3FiatCodes.BBD, new CurrencyFiatCode(Iso3FiatCodes.BBD) }, // Barbados Dollar 
            { Iso3FiatCodes.BDT, new CurrencyFiatCode(Iso3FiatCodes.BDT) }, // Bangladesh Taka 
            { Iso3FiatCodes.BGN, new CurrencyFiatCode(Iso3FiatCodes.BGN) }, // Bulgarian Lev 
            { Iso3FiatCodes.BHD, new CurrencyFiatCode(Iso3FiatCodes.BHD) }, // Bahraini Dinar 
            { Iso3FiatCodes.BIF, new CurrencyFiatCode(Iso3FiatCodes.BIF) }, // Burundi Franc 
            { Iso3FiatCodes.BMD, new CurrencyFiatCode(Iso3FiatCodes.BMD) }, // Bermuda Dollar 
            { Iso3FiatCodes.BND, new CurrencyFiatCode(Iso3FiatCodes.BND) }, // Brunei Dollar 
            { Iso3FiatCodes.BOB, new CurrencyFiatCode(Iso3FiatCodes.BOB) }, // Bolivian Boliviano 
            { Iso3FiatCodes.BRL, new CurrencyFiatCode(Iso3FiatCodes.BRL) }, // Brazilian Real 
            { Iso3FiatCodes.BSD, new CurrencyFiatCode(Iso3FiatCodes.BSD) }, // Bahamian Dollar 
            { Iso3FiatCodes.BTN, new CurrencyFiatCode(Iso3FiatCodes.BTN) }, // Bhutan Ngultrum 
            { Iso3FiatCodes.BWP, new CurrencyFiatCode(Iso3FiatCodes.BWP) }, // Botswana Pula
            { Iso3FiatCodes.BYR, new CurrencyFiatCode(Iso3FiatCodes.BYR) }, // Belarus Ruble 
            { Iso3FiatCodes.BZD, new CurrencyFiatCode(Iso3FiatCodes.BZD) }, // Belize Dollar 
            { Iso3FiatCodes.CAD, new CurrencyFiatCode(Iso3FiatCodes.CAD) }, // Canadian Dollar 
            { Iso3FiatCodes.CDF, new CurrencyFiatCode(Iso3FiatCodes.CDF) }, // Congolese Franc
            { Iso3FiatCodes.CHF, new CurrencyFiatCode(Iso3FiatCodes.CHF) }, // Swiss Franc 
            { Iso3FiatCodes.CLP, new CurrencyFiatCode(Iso3FiatCodes.CLP) }, // Chilean Peso 
            { Iso3FiatCodes.CNY, new CurrencyFiatCode(Iso3FiatCodes.CNY) }, // Chinese Yuan 
            { Iso3FiatCodes.COP, new CurrencyFiatCode(Iso3FiatCodes.COP) }, // Colombian Peso 
            { Iso3FiatCodes.CRC, new CurrencyFiatCode(Iso3FiatCodes.CRC) }, // Costa Rica Colon 
            { Iso3FiatCodes.CUP, new CurrencyFiatCode(Iso3FiatCodes.CUP) }, // Cuban Peso 
            { Iso3FiatCodes.CVE, new CurrencyFiatCode(Iso3FiatCodes.CVE) }, // Cape Verde Escudo
            { Iso3FiatCodes.CZK, new CurrencyFiatCode(Iso3FiatCodes.CZK) }, // Czech Koruna 
            { Iso3FiatCodes.DJF, new CurrencyFiatCode(Iso3FiatCodes.DJF) }, // Dijibouti Franc 
            { Iso3FiatCodes.DKK, new CurrencyFiatCode(Iso3FiatCodes.DKK) }, // Danish Krone 
            { Iso3FiatCodes.DOP, new CurrencyFiatCode(Iso3FiatCodes.DOP) }, // Dominican Peso 
            { Iso3FiatCodes.DZD, new CurrencyFiatCode(Iso3FiatCodes.DZD) }, // Algerian Dinar 
            { Iso3FiatCodes.EGP, new CurrencyFiatCode(Iso3FiatCodes.EGP) }, // Egyptian Pound 
            { Iso3FiatCodes.ERN, new CurrencyFiatCode(Iso3FiatCodes.ERN) }, // Eritrean Nakfa 
            { Iso3FiatCodes.ETB, new CurrencyFiatCode(Iso3FiatCodes.ETB) }, // Ethiopian Birr 
            { Iso3FiatCodes.EUR, new CurrencyFiatCode(Iso3FiatCodes.EUR) }, // Euro 
            { Iso3FiatCodes.FKP, new CurrencyFiatCode(Iso3FiatCodes.FKP) }, // Falkland Islands Pound 
            { Iso3FiatCodes.FJD, new CurrencyFiatCode(Iso3FiatCodes.FJD) }, // Fijian Dollar
            { Iso3FiatCodes.GBP, new CurrencyFiatCode(Iso3FiatCodes.GBP) }, // British Pound 
            { Iso3FiatCodes.GEL, new CurrencyFiatCode(Iso3FiatCodes.GEL) }, // Georgian Lari 
            { Iso3FiatCodes.GHS, new CurrencyFiatCode(Iso3FiatCodes.GHS) }, // Ghanaian Cedi
            { Iso3FiatCodes.GIP, new CurrencyFiatCode(Iso3FiatCodes.GIP) }, // Gibraltar Pound 
            { Iso3FiatCodes.GMD, new CurrencyFiatCode(Iso3FiatCodes.GMD) }, // Gambian Dalasi 
            { Iso3FiatCodes.GNF, new CurrencyFiatCode(Iso3FiatCodes.GNF) }, // Guinea Franc 
            { Iso3FiatCodes.GTQ, new CurrencyFiatCode(Iso3FiatCodes.GTQ) }, // Guatemala Quetzal 
            { Iso3FiatCodes.GWP, new CurrencyFiatCode(Iso3FiatCodes.GWP) }, // Guinea-Bissau peso
            { Iso3FiatCodes.GYD, new CurrencyFiatCode(Iso3FiatCodes.GYD) }, // Guyana Dollar 
            { Iso3FiatCodes.HKD, new CurrencyFiatCode(Iso3FiatCodes.HKD) }, // Hong Kong Dollar 
            { Iso3FiatCodes.HNL, new CurrencyFiatCode(Iso3FiatCodes.HNL) }, // Honduras Lempira 
            { Iso3FiatCodes.HRK, new CurrencyFiatCode(Iso3FiatCodes.HRK) }, // Croatian Kuna 
            { Iso3FiatCodes.HTG, new CurrencyFiatCode(Iso3FiatCodes.HTG) }, // Haiti Gourde 
            { Iso3FiatCodes.HUF, new CurrencyFiatCode(Iso3FiatCodes.HUF) }, // Hungarian ForINT 
            { Iso3FiatCodes.IDR, new CurrencyFiatCode(Iso3FiatCodes.IDR) }, // Indonesian Rupiah 
            { Iso3FiatCodes.ILS, new CurrencyFiatCode(Iso3FiatCodes.ILS) }, // Israeli Shekel 
            { Iso3FiatCodes.INR, new CurrencyFiatCode(Iso3FiatCodes.INR) }, // Indian Rupee 
            { Iso3FiatCodes.IQD, new CurrencyFiatCode(Iso3FiatCodes.IQD) }, // Iraqi Dinar
            { Iso3FiatCodes.IRR, new CurrencyFiatCode(Iso3FiatCodes.IRR) }, // Iran Rial 
            { Iso3FiatCodes.ISK, new CurrencyFiatCode(Iso3FiatCodes.ISK) }, // Iceland Krona 
            { Iso3FiatCodes.JMD, new CurrencyFiatCode(Iso3FiatCodes.JMD) }, // Jamaican Dollar 
            { Iso3FiatCodes.JOD, new CurrencyFiatCode(Iso3FiatCodes.JOD) }, // Jordanian Dinar 
            { Iso3FiatCodes.JPY, new CurrencyFiatCode(Iso3FiatCodes.JPY) }, // Japanese Yen 
            { Iso3FiatCodes.KES, new CurrencyFiatCode(Iso3FiatCodes.KES) }, // Kenyan Shilling 
            { Iso3FiatCodes.KGS, new CurrencyFiatCode(Iso3FiatCodes.KGS) }, // Kyrgyzstani Som
            { Iso3FiatCodes.KHR, new CurrencyFiatCode(Iso3FiatCodes.KHR) }, // Cambodia Riel 
            { Iso3FiatCodes.KMF, new CurrencyFiatCode(Iso3FiatCodes.KMF) }, // Comoros Franc 
            { Iso3FiatCodes.KRW, new CurrencyFiatCode(Iso3FiatCodes.KRW) }, // Korean Won 
            { Iso3FiatCodes.KWD, new CurrencyFiatCode(Iso3FiatCodes.KWD) }, // Kuwaiti Dinar 
            { Iso3FiatCodes.KPW, new CurrencyFiatCode(Iso3FiatCodes.KPW) }, // North Korean Won 
            { Iso3FiatCodes.KYD, new CurrencyFiatCode(Iso3FiatCodes.KYD) }, // Cayman Islands Dollar 
            { Iso3FiatCodes.KZT, new CurrencyFiatCode(Iso3FiatCodes.KZT) }, // Kazakhstan Tenge 
            { Iso3FiatCodes.LAK, new CurrencyFiatCode(Iso3FiatCodes.LAK) }, // Lao Kip 
            { Iso3FiatCodes.LBP, new CurrencyFiatCode(Iso3FiatCodes.LBP) }, // Lebanese Pound 
            { Iso3FiatCodes.LKR, new CurrencyFiatCode(Iso3FiatCodes.LKR) }, // Sri Lanka Rupee 
            { Iso3FiatCodes.LRD, new CurrencyFiatCode(Iso3FiatCodes.LRD) }, // Liberian Dollar
            { Iso3FiatCodes.LSL, new CurrencyFiatCode(Iso3FiatCodes.LSL) }, // Lesotho Loti 
            { Iso3FiatCodes.LTL, new CurrencyFiatCode(Iso3FiatCodes.LTL) }, // Lithuanian Lita 
            { Iso3FiatCodes.LVL, new CurrencyFiatCode(Iso3FiatCodes.LVL) }, // Latvian Lat 
            { Iso3FiatCodes.LYD, new CurrencyFiatCode(Iso3FiatCodes.LYD) }, // Libyan Dinar 
            { Iso3FiatCodes.MAD, new CurrencyFiatCode(Iso3FiatCodes.MAD) }, // Moroccan Dirham 
            { Iso3FiatCodes.MDL, new CurrencyFiatCode(Iso3FiatCodes.MDL) }, // Moldovan Leu 
            { Iso3FiatCodes.MGF, new CurrencyFiatCode(Iso3FiatCodes.MGF) }, // Malagasy Franc 
            { Iso3FiatCodes.MKD, new CurrencyFiatCode(Iso3FiatCodes.MKD) }, // Macedonian Denar 
            { Iso3FiatCodes.MMK, new CurrencyFiatCode(Iso3FiatCodes.MMK) }, // Myanmar Kyat
            { Iso3FiatCodes.MNT, new CurrencyFiatCode(Iso3FiatCodes.MNT) }, // Mongolian Tugrik 
            { Iso3FiatCodes.MOP, new CurrencyFiatCode(Iso3FiatCodes.MOP) }, // Macau Pataca 
            { Iso3FiatCodes.MRO, new CurrencyFiatCode(Iso3FiatCodes.MRO) }, // Mauritania Ougulya 
            { Iso3FiatCodes.MUR, new CurrencyFiatCode(Iso3FiatCodes.MUR) }, // Mauritius Rupee 
            { Iso3FiatCodes.MVR, new CurrencyFiatCode(Iso3FiatCodes.MVR) }, // Maldives Rufiyaa 
            { Iso3FiatCodes.MWK, new CurrencyFiatCode(Iso3FiatCodes.MWK) }, // Malawi Kwacha 
            { Iso3FiatCodes.MXN, new CurrencyFiatCode(Iso3FiatCodes.MXN) }, // Mexican Peso 
            { Iso3FiatCodes.MYR, new CurrencyFiatCode(Iso3FiatCodes.MYR) }, // Malaysian Ringgit 
            { Iso3FiatCodes.MZM, new CurrencyFiatCode(Iso3FiatCodes.MZM) }, // Mozambican Metical
            { Iso3FiatCodes.NAD, new CurrencyFiatCode(Iso3FiatCodes.NAD) }, // Namibian Dollar 
            { Iso3FiatCodes.NGN, new CurrencyFiatCode(Iso3FiatCodes.NGN) }, // Nigerian Naira 
            { Iso3FiatCodes.NIO, new CurrencyFiatCode(Iso3FiatCodes.NIO) }, // Nicaragua Cordoba 
            { Iso3FiatCodes.NOK, new CurrencyFiatCode(Iso3FiatCodes.NOK) }, // Norwegian Krone 
            { Iso3FiatCodes.NPR, new CurrencyFiatCode(Iso3FiatCodes.NPR) }, // Nepalese Rupee 
            { Iso3FiatCodes.NZD, new CurrencyFiatCode(Iso3FiatCodes.NZD) }, // New Zealand Dollar 
            { Iso3FiatCodes.OMR, new CurrencyFiatCode(Iso3FiatCodes.OMR) }, // Omani Rial 
            { Iso3FiatCodes.PAB, new CurrencyFiatCode(Iso3FiatCodes.PAB) }, // Panama Balboa 
            { Iso3FiatCodes.PEN, new CurrencyFiatCode(Iso3FiatCodes.PEN) }, // Peruvian Nuevo Sol 
            { Iso3FiatCodes.PGK, new CurrencyFiatCode(Iso3FiatCodes.PGK) }, // Papua New Guinea Kina 
            { Iso3FiatCodes.PHP, new CurrencyFiatCode(Iso3FiatCodes.PHP) }, // Philippine Peso 
            { Iso3FiatCodes.PKR, new CurrencyFiatCode(Iso3FiatCodes.PKR) }, // Pakistani Rupee 
            { Iso3FiatCodes.PLN, new CurrencyFiatCode(Iso3FiatCodes.PLN) }, // Polish Zloty 
            { Iso3FiatCodes.PYG, new CurrencyFiatCode(Iso3FiatCodes.PYG) }, // Paraguayan Guarani 
            { Iso3FiatCodes.QAR, new CurrencyFiatCode(Iso3FiatCodes.QAR) }, // Qatar Rial 
            { Iso3FiatCodes.RON, new CurrencyFiatCode(Iso3FiatCodes.RON) }, // Romanian New Leu 
            { Iso3FiatCodes.RSD, new CurrencyFiatCode(Iso3FiatCodes.RSD) }, // Serbian Dinar
            { Iso3FiatCodes.RUB, new CurrencyFiatCode(Iso3FiatCodes.RUB) }, // Russian Rouble 
            { Iso3FiatCodes.RWF, new CurrencyFiatCode(Iso3FiatCodes.RWF) }, // Rwanda Franc 
            { Iso3FiatCodes.SAR, new CurrencyFiatCode(Iso3FiatCodes.SAR) }, // Saudi Arabian Riyal 
            { Iso3FiatCodes.SBD, new CurrencyFiatCode(Iso3FiatCodes.SBD) }, // Solomon Islands Dollar
            { Iso3FiatCodes.SCR, new CurrencyFiatCode(Iso3FiatCodes.SCR) }, // Seychelles Rupee 
            { Iso3FiatCodes.SEK, new CurrencyFiatCode(Iso3FiatCodes.SEK) }, // Swedish Krona 
            { Iso3FiatCodes.SDG, new CurrencyFiatCode(Iso3FiatCodes.SDG) }, // Sudanese Pound
            { Iso3FiatCodes.SGD, new CurrencyFiatCode(Iso3FiatCodes.SGD) }, // Singapore Dollar 
            { Iso3FiatCodes.SHP, new CurrencyFiatCode(Iso3FiatCodes.SHP) }, // St Helena Pound 
            { Iso3FiatCodes.SIT, new CurrencyFiatCode(Iso3FiatCodes.SIT) }, // Slovenian Tolar 
            { Iso3FiatCodes.SLL, new CurrencyFiatCode(Iso3FiatCodes.SLL) }, // Sierra Leone Leone 
            { Iso3FiatCodes.SOS, new CurrencyFiatCode(Iso3FiatCodes.SOS) }, // Somali Shilling 
            { Iso3FiatCodes.SRG, new CurrencyFiatCode(Iso3FiatCodes.SRG) }, // Surinamese Guilder 
            { Iso3FiatCodes.SSP, new CurrencyFiatCode(Iso3FiatCodes.SSP) }, // South Sudanese Pound
            { Iso3FiatCodes.STD, new CurrencyFiatCode(Iso3FiatCodes.STD) }, // Sao Tome Dobra 
            { Iso3FiatCodes.SYP, new CurrencyFiatCode(Iso3FiatCodes.SYP) }, // Syrian Pound 
            { Iso3FiatCodes.SZL, new CurrencyFiatCode(Iso3FiatCodes.SZL) }, // Swaziland Lilageni 
            { Iso3FiatCodes.THB, new CurrencyFiatCode(Iso3FiatCodes.THB) }, // Thai Baht 
            { Iso3FiatCodes.TJS, new CurrencyFiatCode(Iso3FiatCodes.TJS) }, // Tajikistani Somoni
            { Iso3FiatCodes.TMM, new CurrencyFiatCode(Iso3FiatCodes.TMM) }, // Turkmenistani Manat
            { Iso3FiatCodes.TND, new CurrencyFiatCode(Iso3FiatCodes.TND) }, // Tunisian Dinar 
            { Iso3FiatCodes.TOP, new CurrencyFiatCode(Iso3FiatCodes.TOP) }, // Tonga Paanga 
            { Iso3FiatCodes.TRY, new CurrencyFiatCode(Iso3FiatCodes.TRY) }, // Turkish Lira 
            { Iso3FiatCodes.TTD, new CurrencyFiatCode(Iso3FiatCodes.TTD) }, // Trinidad&Tobago Dollar 
            { Iso3FiatCodes.TWD, new CurrencyFiatCode(Iso3FiatCodes.TWD) }, // Taiwan Dollar 
            { Iso3FiatCodes.TZS, new CurrencyFiatCode(Iso3FiatCodes.TZS) }, // Tanzanian Shilling 
            { Iso3FiatCodes.UAH, new CurrencyFiatCode(Iso3FiatCodes.UAH) }, // Ukraine Hryvnia 
            { Iso3FiatCodes.UGX, new CurrencyFiatCode(Iso3FiatCodes.UGX) }, // Ugandan Shilling 
            { Iso3FiatCodes.USD, new CurrencyFiatCode(Iso3FiatCodes.USD) }, // U.S. Dollar 
            { Iso3FiatCodes.UYU, new CurrencyFiatCode(Iso3FiatCodes.UYU) }, // Uruguayan New Peso 
            { Iso3FiatCodes.UZS, new CurrencyFiatCode(Iso3FiatCodes.UZS) }, // Uzbekistani Soʻm
            { Iso3FiatCodes.VES, new CurrencyFiatCode(Iso3FiatCodes.VES) }, // Venezuelan Bolívar
            { Iso3FiatCodes.VND, new CurrencyFiatCode(Iso3FiatCodes.VND) }, // Vietnam Dong 
            { Iso3FiatCodes.VUV, new CurrencyFiatCode(Iso3FiatCodes.VUV) }, // Vanuatu Vatu 
            { Iso3FiatCodes.WST, new CurrencyFiatCode(Iso3FiatCodes.WST) }, // Samoa Tala 
            { Iso3FiatCodes.XAF, new CurrencyFiatCode(Iso3FiatCodes.XAF) }, // CFA Franc (BEAC) 
            { Iso3FiatCodes.XAU, new CurrencyFiatCode(Iso3FiatCodes.XAU) }, // Gold Ounces 
            { Iso3FiatCodes.XCD, new CurrencyFiatCode(Iso3FiatCodes.XCD) }, // East Caribbean Dollar 
            { Iso3FiatCodes.XOF, new CurrencyFiatCode(Iso3FiatCodes.XOF) }, // CFA Franc (BCEAO) 
            { Iso3FiatCodes.XPF, new CurrencyFiatCode(Iso3FiatCodes.XPF) }, // Pacific Franc 
            { Iso3FiatCodes.YER, new CurrencyFiatCode(Iso3FiatCodes.YER) }, // Yemen Riyal 
            { Iso3FiatCodes.ZAR, new CurrencyFiatCode(Iso3FiatCodes.ZAR) }, // South African Rand 
            { Iso3FiatCodes.ZMW, new CurrencyFiatCode(Iso3FiatCodes.ZMW) }, // Zambian Kwacha 
            { Iso3FiatCodes.ZWD, new CurrencyFiatCode(Iso3FiatCodes.ZWD) }, // Zimbabwean Dollar
            #endregion
        };
        #endregion

        /// <summary>
        /// Create GdCurrencyFiatCode from string value (case insensitive)
        /// </summary>
        /// <param name="code"></param>
        /// <returns></returns>
        public static CurrencyFiatCode FromString(string code)
        {
            if (string.IsNullOrEmpty(code))
                throw new InvalidCurrencyCodeException(code);


            code = code.Trim().ToUpper();
            if (Codes.TryGetValue(code, out CurrencyFiatCode gdCurrencyFiatCode))
                return gdCurrencyFiatCode;

            throw new InvalidCurrencyCodeException(code);   
        }
    }
}