using System.Collections.Generic;
using System.Linq;
using GlobalData.Base.Country.Exceptions;

namespace GlobalData.Base.Country
{
    public static class GdCountryList
    {
        /// <summary>
        /// Complete country data parsed from CSV to C# code
        /// </summary>
        private static Dictionary<string, GdCountry> GdCountryDict { get; } = new()
        {
            { Iso2Codes.AB, new GdCountry("Abkhazia", null, null, "AB", "ABK", "ABK", 7840, new uint[] { 7840, 7940 }) },
            { Iso2Codes.AC, new GdCountry("Ascension Island", null, null, "AC", "ASC", "SHP", 247, new uint[] { 247 }) },
            { Iso2Codes.AD, new GdCountry("Andorra", null, null, "AD", "AND", "EUR", 376, new uint[] { 376 }) },
            { Iso2Codes.AE, new GdCountry("United Arab Emirates", null, null, "AE", "ARE", "AED", 971, new uint[] { 971 }) },
            { Iso2Codes.AF, new GdCountry("Afghanistan", null, null, "AF", "AFG", "AFN", 93, new uint[] { 93 }) },
            { Iso2Codes.AG, new GdCountry("Antigua And Barbuda", null, null, "AG", "ATG", "XCD", 1268, new uint[] { 1268 }) },
            { Iso2Codes.AI, new GdCountry("Anguilla", null, null, "AI", "AIA", "XCD", 1264, new uint[] { 1264 }) },
            { Iso2Codes.AL, new GdCountry("Albania", null, null, "AL", "ALB", "ALL", 355, new uint[] { 355 }) },
            { Iso2Codes.AM, new GdCountry("Armenia", null, null, "AM", "ARM", "AMD", 374, new uint[] { 374 }) },
            { Iso2Codes.AN, new GdCountry("Netherlands Antilles", null, null, "AN", "ANT", "ANG", 599, new uint[] { 599 }) },
            { Iso2Codes.AO, new GdCountry("Angola", null, null, "AO", "AGO", "AOA", 244, new uint[] { 244 }) },
            { Iso2Codes.AQ, new GdCountry("Antarctica", null, null, "AQ", "ATA", "NOK", 672, new uint[] { 6721 }) },
            { Iso2Codes.AR, new GdCountry("Argentina", null, null, "AR", "ARG", "ARS", 54, new uint[] { 54 }) },
            { Iso2Codes.AS, new GdCountry("American Samoa", null, null, "AS", "ASM", "USD", 1684, new uint[] { 1684 }) },
            { Iso2Codes.AT, new GdCountry("Austria", null, null, "AT", "AUT", "EUR", 43, new uint[] { 43 }) },
            { Iso2Codes.AU, new GdCountry("Australia", null, null, "AU", "AUS", "AUD", 61, new uint[] { 61 }) },
            { Iso2Codes.AW, new GdCountry("Aruba", null, null, "AW", "ABW", "AWG", 297, new uint[] { 297 }) },
            { Iso2Codes.AX, new GdCountry("Aland Islands", null, null, "AX", "ALA", "EUR", 35818, new uint[] { 35818 }) },
            { Iso2Codes.AZ, new GdCountry("Azerbaijan", null, null, "AZ", "AZE", "AZN", 994, new uint[] { 994 }) },
            { Iso2Codes.BA, new GdCountry("Bosnia And Herzegovina", null, null, "BA", "BIH", "BAM", 387, new uint[] { 387 }) },
            { Iso2Codes.BB, new GdCountry("Barbados", null, null, "BB", "BRB", "BBD", 1246, new uint[] { 1246 }) },
            { Iso2Codes.BD, new GdCountry("Bangladesh", null, null, "BD", "BGD", "BDT", 880, new uint[] { 880 }) },
            { Iso2Codes.BE, new GdCountry("Belgium", null, null, "BE", "BEL", "EUR", 32, new uint[] { 32 }) },
            { Iso2Codes.BF, new GdCountry("Burkina Faso", null, null, "BF", "BFA", "XAF", 226, new uint[] { 226 }) },
            { Iso2Codes.BG, new GdCountry("Bulgaria", null, null, "BG", "BGR", "BGN", 359, new uint[] { 359 }) },
            { Iso2Codes.BH, new GdCountry("Bahrain", null, null, "BH", "BHR", "BHD", 973, new uint[] { 973 }) },
            { Iso2Codes.BI, new GdCountry("Burundi", null, null, "BI", "BDI", "BIF", 257, new uint[] { 257 }) },
            { Iso2Codes.BJ, new GdCountry("Benin", null, null, "BJ", "BEN", "XAF", 229, new uint[] { 229 }) },
            { Iso2Codes.BM, new GdCountry("Bermuda", null, null, "BM", "BMU", "BMD", 1441, new uint[] { 1441 }) },
            { Iso2Codes.BN, new GdCountry("Brunei Darussalam", null, null, "BN", "BRN", "BND", 673, new uint[] { 673 }) },
            { Iso2Codes.BO, new GdCountry("Bolivia", null, null, "BO", "BOL", "BOB", 591, new uint[] { 591 }) },
            { Iso2Codes.BR, new GdCountry("Brazil", null, null, "BR", "BRA", "BRL", 55, new uint[] { 55 }) },
            { Iso2Codes.BS, new GdCountry("Bahamas", null, null, "BS", "BHS", "BSD", 1242, new uint[] { 1242 }) },
            { Iso2Codes.BT, new GdCountry("Bhutan", null, null, "BT", "BTN", "BTN", 975, new uint[] { 975 }) },
            { Iso2Codes.BW, new GdCountry("Botswana", null, null, "BW", "BWA", "BWP", 267, new uint[] { 267 }) },
            { Iso2Codes.BY, new GdCountry("Belarus", null, null, "BY", "BLR", "BYR", 375, new uint[] { 375 }) },
            { Iso2Codes.BZ, new GdCountry("Belize", null, null, "BZ", "BLZ", "BZD", 501, new uint[] { 501 }) },
            { Iso2Codes.CA, new GdCountry("Canada", null, null, "CA", "CAN", "CAD", 1, new uint[] { 1403, 1250, 1604, 1807, 1519, 1204, 1506, 1709, 1867, 1902, 1705, 1613, 1416, 1905, 1514, 1450, 1418, 1819, 1306, 1778, 1226, 1289, 1438, 1581, 1587, 1647, 1780, 1849 }) },
            { Iso2Codes.CC, new GdCountry("Cocos (Keeling) Islands", null, null, "CC", "CCK", "AUD", 6189162, new uint[] { 6189162 }) },
            { Iso2Codes.CD, new GdCountry("Congo, Democratic Republic of the", null, null, "CD", "COD", "CDF", 243, new uint[] { 243 }) },
            { Iso2Codes.CF, new GdCountry("Central African Republic", null, null, "CF", "CAF", "XAF", 236, new uint[] { 236 }) },
            { Iso2Codes.CG, new GdCountry("Congo, Republic of the", null, null, "CG", "COG", "XAF", 242, new uint[] { 242 }) },
            { Iso2Codes.CH, new GdCountry("Switzerland", null, null, "CH", "CHE", "CHF", 41, new uint[] { 41 }) },
            { Iso2Codes.CI, new GdCountry("Ivory Coast", "Republic of", null, "CI", "CIV", "XAF", 225, new uint[] { 225 }) },
            { Iso2Codes.CK, new GdCountry("Cook Islands", null, null, "CK", "COK", "NZD", 682, new uint[] { 682 }) },
            { Iso2Codes.CL, new GdCountry("Chile", null, null, "CL", "CHL", "CLP", 56, new uint[] { 56 }) },
            { Iso2Codes.CM, new GdCountry("Cameroon", null, null, "CM", "CMR", "XAF", 237, new uint[] { 237 }) },
            { Iso2Codes.CN, new GdCountry("China", null, null, "CN", "CHN", "CNY", 86, new uint[] { 86 }) },
            { Iso2Codes.CO, new GdCountry("Colombia", null, null, "CO", "COL", "COP", 57, new uint[] { 57 }) },
            { Iso2Codes.CR, new GdCountry("Costa Rica", null, null, "CR", "CRI", "CRC", 506, new uint[] { 506 }) },
            { Iso2Codes.CU, new GdCountry("Cuba", null, null, "CU", "CUB", "CUP", 53, new uint[] { 53 }) },
            { Iso2Codes.CV, new GdCountry("Cape Verde", null, null, "CV", "CPV", "CVE", 238, new uint[] { 238 }) },
            { Iso2Codes.CX, new GdCountry("Christmas Island", null, null, "CX", "CXR", "AUD", 618, new uint[] { 618 }) },
            { Iso2Codes.CY, new GdCountry("Cyprus", null, null, "CY", "CYP", "EUR", 357, new uint[] { 357 }) },
            { Iso2Codes.CZ, new GdCountry("Czech Republic", null, null, "CZ", "CZE", "CZK", 420, new uint[] { 420 }) },
            { Iso2Codes.DE, new GdCountry("Germany", null, null, "DE", "DEU", "EUR", 49, new uint[] { 49 }) },
            { Iso2Codes.DJ, new GdCountry("Djibouti", null, null, "DJ", "DJI", "DJF", 253, new uint[] { 253 }) },
            { Iso2Codes.DK, new GdCountry("Denmark", null, null, "DK", "DNK", "DKK", 45, new uint[] { 45 }) },
            { Iso2Codes.DM, new GdCountry("Dominica", null, null, "DM", "DMA", "XCD", 1767, new uint[] { 1767 }) },
            { Iso2Codes.DO, new GdCountry("Dominican Republic", null, null, "DO", "DOM", "DOP", 1809, new uint[] { 1809, 1829 }) },
            { Iso2Codes.DZ, new GdCountry("Algeria", null, null, "DZ", "DZA", "DZD", 213, new uint[] { 213 }) },
            { Iso2Codes.EC, new GdCountry("Ecuador", null, null, "EC", "ECU", "USD", 593, new uint[] { 593 }) },
            { Iso2Codes.EE, new GdCountry("Estonia", null, null, "EE", "EST", "EUR", 372, new uint[] { 372 }) },
            { Iso2Codes.EG, new GdCountry("Egypt", null, null, "EG", "EGY", "EGP", 20, new uint[] { 20 }) },
            { Iso2Codes.EH, new GdCountry("Western Sahara", null, null, "EH", "ESH", "MAD", 212, new uint[] { 2125288, 2125289 }) },
            { Iso2Codes.ER, new GdCountry("Eritrea", null, null, "ER", "ERI", "ERN", 291, new uint[] { 291 }) },
            { Iso2Codes.ES, new GdCountry("Spain", null, null, "ES", "ESP", "EUR", 34, new uint[] { 34 }) },
            { Iso2Codes.ET, new GdCountry("Ethiopia", null, null, "ET", "ETH", "ETB", 251, new uint[] { 251 }) },
            { Iso2Codes.FI, new GdCountry("Finland", null, null, "FI", "FIN", "EUR", 358, new uint[] { 358 }) },
            { Iso2Codes.FJ, new GdCountry("Fiji", null, null, "FJ", "FJI", "FJD", 679, new uint[] { 679 }) },
            { Iso2Codes.FK, new GdCountry("Falkland Islands", null, null, "FK", "FLK", "FKP", 500, new uint[] { 500 }) },
            { Iso2Codes.FM, new GdCountry("Micronesia", "Federated States Of", null, "FM", "FSM", "USD", 691, new uint[] { 691 }) },
            { Iso2Codes.FO, new GdCountry("Faroe Islands", null, null, "FO", "FRO", "DKK", 298, new uint[] { 298 }) },
            { Iso2Codes.FR, new GdCountry("France", null, null, "FR", "FRA", "EUR", 33, new uint[] { 33 }) },
            { Iso2Codes.GA, new GdCountry("Gabon", null, null, "GA", "GAB", "XAF", 241, new uint[] { 241 }) },
            { Iso2Codes.GB, new GdCountry("United Kingdom", null, null, "GB", "GBR", "GBP", 44, new uint[] { 44 }) },
            { Iso2Codes.GD, new GdCountry("Grenada", null, null, "GD", "GRD", "XCD", 1473, new uint[] { 1473 }) },
            { Iso2Codes.GE, new GdCountry("Georgia", null, null, "GE", "GEO", "GEL", 995, new uint[] { 995 }) },
            { Iso2Codes.GF, new GdCountry("French Guiana", null, null, "GF", "GUF", "EUR", 594, new uint[] { 594 }) },
            { Iso2Codes.GG, new GdCountry("Guernsey", null, null, "GG", "GGY", "GBP", 441481, new uint[] { 441481 }) },
            { Iso2Codes.GH, new GdCountry("Ghana", null, null, "GH", "GHA", "GHS", 233, new uint[] { 233 }) },
            { Iso2Codes.GI, new GdCountry("Gibraltar", null, null, "GI", "GIB", "GIP", 350, new uint[] { 350 }) },
            { Iso2Codes.GL, new GdCountry("Greenland", null, null, "GL", "GRL", "DKK", 299, new uint[] { 299 }) },
            { Iso2Codes.GM, new GdCountry("Gambia", null, null, "GM", "GMB", "GMD", 220, new uint[] { 220 }) },
            { Iso2Codes.GN, new GdCountry("Guinea, Republic of", "Republic of", null, "GN", "GIN", "GNF", 224, new uint[] { 224 }) },
            { Iso2Codes.GO, new GdCountry("Global System", null, null, "GO", "GMS", "USD", 881, new uint[] { 881, 882, 879 }) },
            { Iso2Codes.GP, new GdCountry("Guadeloupe", null, null, "GP", "GLP", "EUR", 590, new uint[] { 590 }) },
            { Iso2Codes.GQ, new GdCountry("Equatorial Guinea", null, null, "GQ", "GNQ", "XAF", 240, new uint[] { 240 }) },
            { Iso2Codes.GR, new GdCountry("Greece", null, null, "GR", "GRC", "EUR", 30, new uint[] { 30 }) },
            { Iso2Codes.GS, new GdCountry("South Georgia", null, " And The South Sandwich Islands", "GS", "SGS", "GBP", 500, new uint[] { 50090 }) },
            { Iso2Codes.GT, new GdCountry("Guatemala", null, null, "GT", "GTM", "GTQ", 502, new uint[] { 502 }) },
            { Iso2Codes.GU, new GdCountry("Guam", null, null, "GU", "GUM", "USD", 1671, new uint[] { 1671 }) },
            { Iso2Codes.GW, new GdCountry("Guinea-Bissau", null, null, "GW", "GNB", "GWP", 245, new uint[] { 245 }) },
            { Iso2Codes.GY, new GdCountry("Guyana", null, null, "GY", "GUY", "GYD", 592, new uint[] { 592 }) },
            { Iso2Codes.HK, new GdCountry("Hong Kong", null, null, "HK", "HKG", "HKD", 852, new uint[] { 852 }) },
            { Iso2Codes.HN, new GdCountry("Honduras", null, null, "HN", "HND", "HNL", 504, new uint[] { 504 }) },
            { Iso2Codes.HR, new GdCountry("Croatia", null, null, "HR", "HRV", "HRK", 385, new uint[] { 385 }) },
            { Iso2Codes.HT, new GdCountry("Haiti", null, null, "HT", "HTI", "HTG", 509, new uint[] { 509 }) },
            { Iso2Codes.HU, new GdCountry("Hungary", null, null, "HU", "HUN", "HUF", 36, new uint[] { 36 }) },
            { Iso2Codes.ID, new GdCountry("Indonesia", null, null, "ID", "IDN", "IDR", 62, new uint[] { 62 }) },
            { Iso2Codes.IE, new GdCountry("Ireland", null, null, "IE", "IRL", "EUR", 353, new uint[] { 353 }) },
            { Iso2Codes.IL, new GdCountry("Israel", null, null, "IL", "ISR", "ILS", 972, new uint[] { 972 }) },
            { Iso2Codes.IM, new GdCountry("Isle of Man", null, null, "IM", "IMN", "GBP", 441624, new uint[] { 441624 }) },
            { Iso2Codes.IN, new GdCountry("India", null, null, "IN", "IND", "INR", 91, new uint[] { 91 }) },
            { Iso2Codes.IO, new GdCountry("British Indian Ocean Territory", null, null, "IO", "IOT", "USD", 246, new uint[] { 246 }) },
            { Iso2Codes.IQ, new GdCountry("Iraq", null, null, "IQ", "IRQ", "IQD", 964, new uint[] { 964 }) },
            { Iso2Codes.IR, new GdCountry("Iran", "Islamic Republic of", null, "IR", "IRN", "IRR", 98, new uint[] { 98 }) },
            { Iso2Codes.IS, new GdCountry("Iceland", null, null, "IS", "ISL", "ISK", 354, new uint[] { 354 }) },
            { Iso2Codes.IT, new GdCountry("Italy", null, null, "IT", "ITA", "EUR", 39, new uint[] { 39 }) },
            { Iso2Codes.JE, new GdCountry("Jersey", null, null, "JE", "JEY", "GBP", 441534, new uint[] { 441534 }) },
            { Iso2Codes.JM, new GdCountry("Jamaica", null, null, "JM", "JAM", "JMD", 1876, new uint[] { 1876 }) },
            { Iso2Codes.JO, new GdCountry("Jordan", null, null, "JO", "JOR", "JOD", 962, new uint[] { 962 }) },
            { Iso2Codes.JP, new GdCountry("Japan", null, null, "JP", "JPN", "JPY", 81, new uint[] { 81 }) },
            { Iso2Codes.KE, new GdCountry("Kenya", null, null, "KE", "KEN", "KES", 254, new uint[] { 254 }) },
            { Iso2Codes.KG, new GdCountry("Kyrgyzstan", null, null, "KG", "KGZ", "KGS", 996, new uint[] { 996 }) },
            { Iso2Codes.KH, new GdCountry("Cambodia", null, null, "KH", "KHM", "KHR", 855, new uint[] { 855 }) },
            { Iso2Codes.KI, new GdCountry("Kiribati", null, null, "KI", "KIR", "AUD", 686, new uint[] { 686 }) },
            { Iso2Codes.KM, new GdCountry("Comoros", null, "The Democratic Republic Of The", "KM", "COM", "KMF", 269, new uint[] { 269 }) },
            { Iso2Codes.KN, new GdCountry("Saint Kitts And Nevis", null, null, "KN", "KNA", "XCD", 1869, new uint[] { 1869 }) },
            { Iso2Codes.KP, new GdCountry("Korea, North", null, null, "KP", "PRK", "KPW", 850, new uint[] { 850 }) },
            { Iso2Codes.KR, new GdCountry("Korea, South", null, null, "KR", "KOR", "KRW", 82, new uint[] { 82 }) },
            { Iso2Codes.KW, new GdCountry("Kuwait", null, null, "KW", "KWT", "KWD", 965, new uint[] { 965 }) },
            { Iso2Codes.KY, new GdCountry("Cayman Islands", null, null, "KY", "CYM", "KYD", 1345, new uint[] { 1345 }) },
            { Iso2Codes.KZ, new GdCountry("Kazakhstan", null, null, "KZ", "KAZ", "KZT", 77, new uint[] { 77 }) },
            { Iso2Codes.LA, new GdCountry("Laos", null, "People's Democratic Republic", "LA", "LAO", "LAK", 856, new uint[] { 856 }) },
            { Iso2Codes.LB, new GdCountry("Lebanon", null, null, "LB", "LBN", "LBP", 961, new uint[] { 961 }) },
            { Iso2Codes.LC, new GdCountry("Saint Lucia", null, null, "LC", "LCA", "XCD", 1758, new uint[] { 1758 }) },
            { Iso2Codes.LI, new GdCountry("Liechtenstein", null, null, "LI", "LIE", "CHF", 423, new uint[] { 423 }) },
            { Iso2Codes.LK, new GdCountry("Sri Lanka", null, null, "LK", "LKA", "LKR", 94, new uint[] { 94 }) },
            { Iso2Codes.LR, new GdCountry("Liberia", null, null, "LR", "LBR", "LRD", 231, new uint[] { 231 }) },
            { Iso2Codes.LS, new GdCountry("Lesotho", null, null, "LS", "LSO", "LSL", 266, new uint[] { 266 }) },
            { Iso2Codes.LT, new GdCountry("Lithuania", null, null, "LT", "LTU", "EUR", 370, new uint[] { 370 }) },
            { Iso2Codes.LU, new GdCountry("Luxembourg", null, null, "LU", "LUX", "EUR", 352, new uint[] { 352 }) },
            { Iso2Codes.LV, new GdCountry("Latvia", null, null, "LV", "LVA", "LVL", 371, new uint[] { 371 }) },
            { Iso2Codes.LY, new GdCountry("Libya", null, null, "LY", "LBY", "LYD", 218, new uint[] { 218 }) },
            { Iso2Codes.MA, new GdCountry("Morocco", null, null, "MA", "MAR", "MAD", 212, new uint[] { 212 }) },
            { Iso2Codes.MC, new GdCountry("Monaco", null, null, "MC", "MCO", "EUR", 377, new uint[] { 377 }) },
            { Iso2Codes.MD, new GdCountry("Moldova", "Republic Of", null, "MD", "MDA", "MDL", 373, new uint[] { 373 }) },
            { Iso2Codes.ME, new GdCountry("Montenegro", "Republic of", null, "ME", "MNE", "EUR", 382, new uint[] { 382 }) },
            { Iso2Codes.MG, new GdCountry("Madagascar", null, null, "MG", "MDG", "MGF", 261, new uint[] { 261 }) },
            { Iso2Codes.MH, new GdCountry("Marshall islands", null, null, "MH", "MHL", "USD", 692, new uint[] { 692 }) },
            { Iso2Codes.MK, new GdCountry("Macedonia", "The Former Yugoslav Republic Of", null, "MK", "MKD", "MKD", 389, new uint[] { 389 }) },
            { Iso2Codes.ML, new GdCountry("Mali", null, null, "ML", "MLI", "XAF", 223, new uint[] { 223 }) },
            { Iso2Codes.MM, new GdCountry("Myanmar", null, null, "MM", "MMR", "MMK", 95, new uint[] { 95 }) },
            { Iso2Codes.MN, new GdCountry("Mongolia", null, null, "MN", "MNG", "MNT", 976, new uint[] { 976 }) },
            { Iso2Codes.MO, new GdCountry("Macau", null, null, "MO", "MAC", "MOP", 853, new uint[] { 853 }) },
            { Iso2Codes.MP, new GdCountry("Northern Mariana Islands", null, null, "MP", "MNP", "USD", 1670, new uint[] { 1670 }) },
            { Iso2Codes.MQ, new GdCountry("Martinique", null, null, "MQ", "MTQ", "EUR", 596, new uint[] { 596 }) },
            { Iso2Codes.MR, new GdCountry("Mauritania", null, null, "MR", "MRT", "MRO", 222, new uint[] { 222 }) },
            { Iso2Codes.MS, new GdCountry("Montserrat", null, null, "MS", "MSR", "XCD", 1664, new uint[] { 1664 }) },
            { Iso2Codes.MT, new GdCountry("Malta", null, null, "MT", "MLT", "EUR", 356, new uint[] { 356 }) },
            { Iso2Codes.MU, new GdCountry("Mauritius", null, null, "MU", "MUS", "MUR", 230, new uint[] { 230 }) },
            { Iso2Codes.MV, new GdCountry("Maldives", null, null, "MV", "MDV", "MVR", 960, new uint[] { 960 }) },
            { Iso2Codes.MW, new GdCountry("Malawi", null, null, "MW", "MWI", "MWK", 265, new uint[] { 265 }) },
            { Iso2Codes.MX, new GdCountry("Mexico", null, null, "MX", "MEX", "MXN", 52, new uint[] { 52 }) },
            { Iso2Codes.MY, new GdCountry("Malaysia", null, null, "MY", "MYS", "MYR", 60, new uint[] { 60 }) },
            { Iso2Codes.MZ, new GdCountry("Mozambique", null, null, "MZ", "MOZ", "MZM", 258, new uint[] { 258 }) },
            { Iso2Codes.NA, new GdCountry("Namibia", null, null, "NA", "NAM", "NAD", 264, new uint[] { 264 }) },
            { Iso2Codes.NC, new GdCountry("New Caledonia", null, null, "NC", "NCL", "XPF", 687, new uint[] { 687 }) },
            { Iso2Codes.NE, new GdCountry("Niger", null, null, "NE", "NER", "XOF", 227, new uint[] { 227 }) },
            { Iso2Codes.NF, new GdCountry("Norfolk Island", null, null, "NF", "NFK", "AUD", 672, new uint[] { 6723 }) },
            { Iso2Codes.NG, new GdCountry("Nigeria", null, null, "NG", "NGA", "NGN", 234, new uint[] { 234 }) },
            { Iso2Codes.NI, new GdCountry("Nicaragua", null, null, "NI", "NIC", "NIO", 505, new uint[] { 505 }) },
            { Iso2Codes.NL, new GdCountry("Netherlands, The", null, null, "NL", "NLD", "EUR", 31, new uint[] { 31 }) },
            { Iso2Codes.NO, new GdCountry("Norway", null, null, "NO", "NOR", "NOK", 47, new uint[] { 47 }) },
            { Iso2Codes.NP, new GdCountry("Nepal", null, null, "NP", "NPL", "NPR", 977, new uint[] { 977 }) },
            { Iso2Codes.NR, new GdCountry("Nauru", null, null, "NR", "NRU", "AUD", 674, new uint[] { 674 }) },
            { Iso2Codes.NU, new GdCountry("Niue", null, null, "NU", "NIU", "NZD", 683, new uint[] { 683 }) },
            { Iso2Codes.NZ, new GdCountry("New Zealand", null, null, "NZ", "NZL", "NZD", 64, new uint[] { 64 }) },
            { Iso2Codes.OM, new GdCountry("Oman", null, null, "OM", "OMN", "OMR", 968, new uint[] { 968 }) },
            { Iso2Codes.PA, new GdCountry("Panama", null, null, "PA", "PAN", "PAB", 507, new uint[] { 507 }) },
            { Iso2Codes.PE, new GdCountry("Peru", null, null, "PE", "PER", "PEN", 51, new uint[] { 51 }) },
            { Iso2Codes.PF, new GdCountry("French Polynesia", null, null, "PF", "PYF", "XPF", 689, new uint[] { 689 }) },
            { Iso2Codes.PG, new GdCountry("Papua New Guinea", null, null, "PG", "PNG", "PGK", 675, new uint[] { 675 }) },
            { Iso2Codes.PH, new GdCountry("Philippines", null, null, "PH", "PHL", "PHP", 63, new uint[] { 63 }) },
            { Iso2Codes.PK, new GdCountry("Pakistan", null, null, "PK", "PAK", "PKR", 92, new uint[] { 92 }) },
            { Iso2Codes.PL, new GdCountry("Poland", null, null, "PL", "POL", "PLN", 48, new uint[] { 48 }) },
            { Iso2Codes.PM, new GdCountry("Saint Pierre and Miquelon", null, null, "PM", "SPM", "EUR", 508, new uint[] { 508 }) },
            { Iso2Codes.PN, new GdCountry("Pitcairn Islands", null, null, "PN", "PCN", "NZD", 649, new uint[] { 649 }) },
            { Iso2Codes.PR, new GdCountry("Puerto Rico", null, null, "PR", "PRI", "USD", 1787, new uint[] { 1787, 1939 }) },
            { Iso2Codes.PS, new GdCountry("Palestine", null, null, "PS", "PSE", "JOD ", 970, new uint[] { 970 }) },
            { Iso2Codes.PT, new GdCountry("Portugal", null, null, "PT", "PRT", "EUR", 351, new uint[] { 351 }) },
            { Iso2Codes.PW, new GdCountry("Palau", null, null, "PW", "PLW", "USD", 680, new uint[] { 680 }) },
            { Iso2Codes.PY, new GdCountry("Paraguay", null, null, "PY", "PRY", "PYG", 595, new uint[] { 595 }) },
            { Iso2Codes.QA, new GdCountry("Qatar", null, null, "QA", "QAT", "QAR", 974, new uint[] { 974 }) },
            { Iso2Codes.RE, new GdCountry("Reunion", null, null, "RE", "REU", "EUR", 262, new uint[] { 262262, 262692 }) },
            { Iso2Codes.RO, new GdCountry("Romania", null, null, "RO", "ROU", "RON", 40, new uint[] { 40 }) },
            { Iso2Codes.RS, new GdCountry("Serbia", "Republic of", null, "RS", "SRB", "RSD", 381, new uint[] { 381 }) },
            { Iso2Codes.RU, new GdCountry("Russia", null, "Federation", "RU", "RUS", "RUB", 7, new uint[] { 71, 72, 73, 74, 75, 76, 78, 79 }) },
            { Iso2Codes.RW, new GdCountry("Rwanda", null, null, "RW", "RWA", "RWF", 250, new uint[] { 250 }) },
            { Iso2Codes.SA, new GdCountry("Saudi Arabia", null, null, "SA", "SAU", "SAR", 966, new uint[] { 966 }) },
            { Iso2Codes.SB, new GdCountry("Solomon Islands", null, null, "SB", "SLB", "SBD", 677, new uint[] { 677 }) },
            { Iso2Codes.SC, new GdCountry("Seychelles", null, null, "SC", "SYC", "SCR", 248, new uint[] { 248 }) },
            { Iso2Codes.SD, new GdCountry("Sudan", null, null, "SD", "SDN", "SDG", 249, new uint[] { 249 }) },
            { Iso2Codes.SE, new GdCountry("Sweden", null, null, "SE", "SWE", "SEK", 46, new uint[] { 46 }) },
            { Iso2Codes.SG, new GdCountry("Singapore", null, null, "SG", "SGP", "SGD", 65, new uint[] { 65 }) },
            { Iso2Codes.SH, new GdCountry("Saint Helena", null, null, "SH", "SHN", "SHP", 290, new uint[] { 2901, 2902, 2903, 2904, 2905, 2906, 2907, 2909 }) },
            { Iso2Codes.SI, new GdCountry("Slovenia", null, null, "SI", "SVN", "EUR", 386, new uint[] { 386 }) },
            { Iso2Codes.SK, new GdCountry("Slovakia", null, null, "SK", "SVK", "EUR", 421, new uint[] { 421 }) },
            { Iso2Codes.SL, new GdCountry("Sierra Leone", null, null, "SL", "SLE", "SLL", 232, new uint[] { 232 }) },
            { Iso2Codes.SM, new GdCountry("San Marino", null, null, "SM", "SMR", "EUR", 378, new uint[] { 378 }) },
            { Iso2Codes.SN, new GdCountry("Senegal", null, null, "SN", "SEN", "XOF", 221, new uint[] { 221 }) },
            { Iso2Codes.SO, new GdCountry("Somalia", null, null, "SO", "SOM", "SOS", 252, new uint[] { 252 }) },
            { Iso2Codes.SR, new GdCountry("Suriname", null, null, "SR", "SUR", "SRG", 597, new uint[] { 597 }) },
            { Iso2Codes.SS, new GdCountry("South Sudan", null, null, "SS", "SSD", "SSP", 211, new uint[] { 211 }) },
            { Iso2Codes.ST, new GdCountry("Sao Tome and Principe", null, null, "ST", "STP", "STD", 239, new uint[] { 239 }) },
            { Iso2Codes.SV, new GdCountry("El Salvador", null, null, "SV", "SLV", "USD", 503, new uint[] { 503 }) },
            { Iso2Codes.SX, new GdCountry("Sint Maarten", null, null, "SX", "SXM", "ANG", 1721, new uint[] { 1721 }) },
            { Iso2Codes.SY, new GdCountry("Syria", null, null, "SY", "SYR", "SYP", 963, new uint[] { 963 }) },
            { Iso2Codes.SZ, new GdCountry("Swaziland", null, null, "SZ", "SWZ", "SZL", 268, new uint[] { 268 }) },
            { Iso2Codes.TA, new GdCountry("Tristan da Cunha", null, null, "TA", "TAA", "GBP", 290, new uint[] { 2908 }) },
            { Iso2Codes.TC, new GdCountry("Turks And Caicos Islands", null, null, "TC", "TCA", "USD", 1649, new uint[] { 1649 }) },
            { Iso2Codes.TD, new GdCountry("Chad", null, null, "TD", "TCD", "XAF", 235, new uint[] { 235 }) },
            { Iso2Codes.TG, new GdCountry("Togo", null, null, "TG", "TGO", "XAF", 228, new uint[] { 228 }) },
            { Iso2Codes.TH, new GdCountry("Thailand", null, null, "TH", "THA", "THB", 66, new uint[] { 66 }) },
            { Iso2Codes.TJ, new GdCountry("Tajikistan", null, null, "TJ", "TJK", "TJS", 992, new uint[] { 992 }) },
            { Iso2Codes.TK, new GdCountry("Tokelau", null, null, "TK", "TKL", "NZD", 690, new uint[] { 690 }) },
            { Iso2Codes.TL, new GdCountry("East Timor", null, null, "TL", "TMP", "USD", 670, new uint[] { 670 }) },
            { Iso2Codes.TM, new GdCountry("Turkmenistan", null, null, "TM", "TKM", "TMM", 993, new uint[] { 993 }) },
            { Iso2Codes.TN, new GdCountry("Tunisia", null, null, "TN", "TUN", "TND", 216, new uint[] { 216 }) },
            { Iso2Codes.TO, new GdCountry("Tonga", null, null, "TO", "TON", "TOP", 676, new uint[] { 676 }) },
            { Iso2Codes.TR, new GdCountry("Turkey", null, null, "TR", "TUR", "TRY", 90, new uint[] { 90 }) },
            { Iso2Codes.TT, new GdCountry("Trinidad And Tobago", null, null, "TT", "TTO", "TTD", 1868, new uint[] { 1868 }) },
            { Iso2Codes.TV, new GdCountry("Tuvalu", null, null, "TV", "TUV", "AUD", 688, new uint[] { 688 }) },
            { Iso2Codes.TW, new GdCountry("Taiwan", null, "Province Of China", "TW", "TWN", "TWD", 886, new uint[] { 886 }) },
            { Iso2Codes.TZ, new GdCountry("Tanzania", "United Republic Of", null, "TZ", "TZA", "TZS", 255, new uint[] { 255 }) },
            { Iso2Codes.UA, new GdCountry("Ukraine", null, null, "UA", "UKR", "UAH", 380, new uint[] { 380 }) },
            { Iso2Codes.UG, new GdCountry("Uganda", null, null, "UG", "UGA", "UGX", 256, new uint[] { 256 }) },
            { Iso2Codes.US, new GdCountry("United States", null, "of America", "US", "USA", "USD", 1, new uint[] { 1256, 1327, 1364, 1385, 1442, 1456, 1458, 1500, 1531, 1533, 1534, 1681, 1700, 1747, 1822, 1833, 1844, 1880, 1881, 1882, 1900, 1907, 1205, 1251, 1334, 1479, 1501, 1870, 1480, 1520, 1602, 1623, 1928, 1209, 1213, 1310, 1323, 1408, 1415, 1424, 1510, 1530, 1559, 1562, 1619, 1626, 1650, 1657, 1661, 1707, 1714, 1760, 1805, 1818, 1831, 1858, 1909, 1916, 1925, 1949, 1951, 1303, 1719, 1720, 1970, 1203, 1475, 1860, 1959, 1202, 1302, 1239, 1305, 1321, 1352, 1386, 1407, 1561, 1689, 1727, 1754, 1772, 1786, 1813, 1850, 1863, 1904, 1941, 1954, 1229, 1404, 1470, 1478, 1678, 1706, 1762, 1770, 1912, 1808, 1319, 1515, 1563, 1641, 1712, 1208, 1217, 1224, 1309, 1312, 1331, 1618, 1630, 1708, 1773, 1779, 1815, 1847, 1219, 1260, 1317, 1574, 1765, 1812, 1316, 1620, 1785, 1913, 1270, 1502, 1606, 1859, 1225, 1318, 1337, 1504, 1985, 1339, 1351, 1413, 1508, 1617, 1774, 1781, 1857, 1978, 1227, 1240, 1301, 1410, 1443, 1207, 1231, 1248, 1269, 1313, 1517, 1586, 1616, 1734, 1810, 1906, 1947, 1989, 1218, 1320, 1507, 1612, 1651, 1763, 1952, 1314, 1417, 1573, 1636, 1660, 1816, 1228, 1601, 1662, 1769, 1406, 1252, 1336, 1704, 1828, 1910, 1919, 1980, 1984, 1701, 1308, 1402, 1603, 1201, 1551, 1609, 1732, 1848, 1856, 1862, 1908, 1973, 1505, 1575, 1702 }) },
            { Iso2Codes.UY, new GdCountry("Uruguay", null, null, "UY", "URY", "UYU", 598, new uint[] { 598 }) },
            { Iso2Codes.UZ, new GdCountry("Uzbekistan", null, null, "UZ", "UZB", "UZS", 998, new uint[] { 998 }) },
            { Iso2Codes.VA, new GdCountry("Vatican City", null, "(Vatican City State)", "VA", "VAT", "EUR", 3906698, new uint[] { 3906698 }) },
            { Iso2Codes.VC, new GdCountry("Saint Vincent and the Grenadines", null, null, "VC", "VCT", "XCD", 1784, new uint[] { 1784 }) },
            { Iso2Codes.VE, new GdCountry("Venezuela", null, null, "VE", "VEN", "VES", 58, new uint[] { 58 }) },
            { Iso2Codes.VG, new GdCountry("British Virgin Islands", null, null, "VG", "VGB", "USD", 1284, new uint[] { 1284 }) },
            { Iso2Codes.VI, new GdCountry("US Virgin Islands", "U.S.", null, "VI", "VIR", "USD", 1340, new uint[] { 1340 }) },
            { Iso2Codes.VN, new GdCountry("Vietnam", null, null, "VN", "VNM", "VND", 84, new uint[] { 84 }) },
            { Iso2Codes.VU, new GdCountry("Vanuatu", null, null, "VU", "VUT", "VUV", 678, new uint[] { 678 }) },
            { Iso2Codes.WF, new GdCountry("Wallis And Futuna", null, null, "WF", "WLF", "XPF", 681, new uint[] { 681 }) },
            { Iso2Codes.WS, new GdCountry("Samoa", null, null, "WS", "WSM", "WST", 685, new uint[] { 685 }) },
            { Iso2Codes.XK, new GdCountry("Kosovo", "Republic of", null, "XK", "UNK", "EUR", 383, new uint[] { 383 }) },
            { Iso2Codes.XN, new GdCountry("Inmarsat", null, null, "XN", "XNM", "USD", 87, new uint[] { 870, 871, 872, 873, 874 }) },
            { Iso2Codes.YE, new GdCountry("Yemen", null, null, "YE", "YEM", "YER", 967, new uint[] { 967 }) },
            { Iso2Codes.YT, new GdCountry("Mayotte", null, null, "YT", "MYT", "EUR", 262, new uint[] { 262269, 262639 }) },
            { Iso2Codes.ZA, new GdCountry("South Africa", null, null, "ZA", "ZAF", "ZAR", 27, new uint[] { 27 }) },
            { Iso2Codes.ZM, new GdCountry("Zambia", null, null, "ZM", "ZMB", "ZMW", 260, new uint[] { 260 }) },
            { Iso2Codes.ZW, new GdCountry("Zimbabwe", null, null, "ZW", "ZWE", "ZWD", 263, new uint[] { 263 }) },
        };

        static GdCountryList()
        {
        }

        /// <summary>
        /// Get a GdCountry by Iso2 Code.
        /// </summary>
        /// <param name="gdCountryCode"></param>
        /// <returns>Instance of GdCountry</returns>
        public static GdCountry Get(GdCountryIso2Code gdCountryCode)
        {
            if (GdCountryDict.TryGetValue(gdCountryCode.Code, out GdCountry value))
                return value;

            throw new InvalidCountryCodeException(gdCountryCode.Code);
        }

        public static GdCountry[] GetAll()
        {
            return GdCountryDict.Values.ToArray();
        }
    }
}